### ISSUE TITLE
xDebug - creating a remote debug file

### ISSUE THREAD

**Issue by Kwapi** [lando/lando#1006]
lando v3.0.0-beta.45 on macOS 10.11.6

lando.yml
```name: pearson
recipe: wordpress
config:
  webroot: .
  xdebug: true
  php: '7.0'
  conf:

      
      php: config/php.ini
```

php.ini
```
xdebug.remote_log=/xdebug.log
```

Ever since I updated from version 38 to 40+ xDebug stopped working whereas previously it was pretty much plug&play. I'm using PHPStorm and there seems to be no connection. `phpinfo()` shows that xdebug is enabled and has got everything switched on.

So I thought I'd look into the log files to see if there's anything out of the ordinary there. Unfortunately the default config doesn't seem to be setting the xdebug remote debug file. I tried adding a custom `php.ini` (see above) but I'm getting this on lando start:
```
Xdebug could not open the remote debug file '/xdebug.log'.
```

Is there a way to create and read xdebug logs? I've read all threads on xdebug here but I can't get xdebug to work.

**Comment by pirog** [comment]
@Kwapi we havent changed the xdebug setup for A LONG time and based on our user metrics, error reports and internal usage *im pretty sure* its working the same. 

I'm guessing you dont want to put the remote log `/xdebug.log` since this location is owned by `root` and im guessing `xdebug` is running as `www-data`

**Comment by Tigatok** [comment]
Hi there, I am also having an issue with this. I am using this configuration:
`name: liveperson-8
recipe: drupal8
config:
  webroot: web
  xdebug: true
  conf:
    php: .lando/php.ini`

with php.ini as 
`[PHP]

;;;;;;;;;;;;;;;
;IMPORTANT;
;PLACE THIS FILE UNDER .vscode foder;
;SO IT DOESNT GET COMMITTED;
;;;;;;;;;;;;;;;

xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.remote_enable = on
xdebug.remote_host = 10.0.2.15
xdebug.idekey = PHPSTORM
xdebug.remote_connect_back = 1`

There is 0 action. I have also tried just 
xdebug: true 

instead of the extra php.ini file. Here is output of php -i for xdebug section

`xdebug

xdebug support => enabled
Version => 2.6.0
IDE Key => PHPSTORM

Supported protocols
DBGp - Common DeBuGger Protocol

Directive => Local Value => Master Value
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.extended_info => On => On
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => /tmp => /tmp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => PHPSTORM => PHPSTORM
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => On => On
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => 10.0.2.15 => 10.0.2.15
xdebug.remote_log => no value => no value
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
`

Any help is appreciated :)

**Comment by Kwapi** [comment]
Thanks for the tip @pirog 

I changed the directory to `xdebug.remote_log=/app/xdebug.log` and I'm getting log files now :)

Here's what my logs look like:
```
Log opened at 2018-06-06 09:34:40
I: Connecting to configured address/port: host.docker.internal:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///app/index.php" language="PHP" xdebug:language_version="7.1.17" protocol_version="1.0" appid="1775" idekey="PHPSTORM"><engine version="2.6.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>

-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="stopping" reason="ok"></response>

Log closed at 2018-06-06 09:34:40
```

It seems that the connection stops automatically? I'll try with Atom to rule out a PHPStorm error but I'm not sure what else to do?

**Comment by Tigatok** [comment]
FWIW I think something on my local Apache set up was mixing up with my lando apache. I changed to nginx, and everything works fine now.
