### ISSUE TITLE
Export docker compose file in a project

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#1039]
Feature Request
===============
To export the docker-compose file within the root of a lando project. The reasons for this are:
- comparison/to modify it for production usage
- possible future integration with amazee.io hosting
- validation of advanced configuration, such as overrides, in the compose file
- and maybe more.
So mainly for devops/development purposes.

Now we have to keep searching for the last generated compose file in ~/user/.lando/compose/project/project-x.yml.

We want to have an export option to first validate that some customization has been exported "correctly" instead of keep rebuilding it and waiting for lando to complete the rebuild.
With just an export option you could just export an compose file to a set location to review it, based on your last changes in .lando.yml.

**Comment by pirog** [comment]
@jbertoen i doubt we will support this directly in lando because in many cases the end user doesnt know anything about docker, docker-compose, etc. 

that said i would definitely ping @serundeputy, @dustinleblanc and me directly in slack because we likely are going to be expanding our plugin ecosystem heading into 2019 and this sounds like it would be a great plugin

**Comment by betz** [comment]
I would love this feature.
To be able to spin up a setup for different environments like staging or even production.
Having different .lando.yml files per environment for example.

**Comment by pirog** [comment]
This is unlikely to end up in lando core but could be a good plugin once we launch that ecosystem

**Comment by rushhourmedia** [comment]
+1 for this feature

**Comment by UltraBob** [comment]
+1

**Comment by chrillep** [comment]
+1
