### ISSUE TITLE
Disable https urls

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1049]
I get delay just before Lando finishes project initialization. I'm assuming it's because it's trying to connect to all of the urls but https is red for me. I don't use it so could I just disable this somehow? Tried the "ssl: false" flag but didn't seem to work.

**Comment by molybden123** [comment]
Mayby use an enternal vpn? Openvpn ftw

**Comment by pirog** [comment]
im going to echo @dustinleblanc here but also add a few things

1. its highly unlikely we will have a blanket way to disable ssl since this really shouldnt be a problematic feature 
2. you may be able to achieve some of what you want by modifying the proxy config https://docs.devwithlando.io/config/proxy.html but im guessing you would be better served by discovering the underlying issue

try out some of the examples in our repo and see if you get the same behavior. that should help you locate the culprit
