### ISSUE TITLE
Lando in WSL can't connect to remote docker daemon

### ISSUE THREAD

**Issue by garrettw** [lando/lando#1072]
I'm running Windows 10 Home with Ubuntu 16.04 in WSL (for Lando and Docker CLI), and I also have an Ubuntu 18.04 VM in VMware Player (for Docker daemon).
In WSL Ubuntu, I have lando "v3.0.0-beta.47" installed.
Essentially, I'm just trying to use lando with a remote docker daemon -- but it can't connect.

**Tell us about your `.lando.yml`**
```yml
name: myapp
recipe: wordpress
config:
  webroot: .
services:
  database:
    type: mariadb
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our default config.

**~/.bashrc**
```bash
...
export DOCKER_HOST=tcp://192.168.72.129:2375
```

**~/.lando/config.yml**
```yml
engineConfig:
  socketPath: null
  host: 192.168.72.129
  port: 2375
```

**Tell us about the command you were running**

`docker info` works fine,
but `lando start` gives me this:
```
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

**Tell us about the error you got**
Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

https://hastebin.com/ojapawijip.swift

**Tell us generally about your bug**

I tried to create a new lando app using `lando start` but it couldn't connect to remote docker daemon.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Maybe -- who knows

Does this bug prevent you from using lando?
yes

**Comment by archfz** [comment]
Same issue here.

**Comment by archfz** [comment]
Solved it with export LANDO_ENGINE_CONFIG='{"host": "localhost", "port":"2375"}'

**Comment by garrettw** [comment]
I don't understand, why would it not pull that from my `config.yml`?

**Comment by eleftrik** [comment]
Same issue here, on Windows 10 Pro.
After `export LANDO_ENGINE_CONFIG='{"host": "localhost", "port":"2375"}'` I got

```
$ lando start
warn: Whoops! Lando has detected that Docker is not turned on!
warn: Give us a few moments while we try to start it up for you
warn: Docker has started but we are waiting for a connection
warn: You should be good to go momentarily!
error during connect: Get http://localhost:2375/v1.37/info: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.

```

Of course Docker is running.

**Comment by dustinleblanc** [comment]
@garrettw your error isn't related to not being able to contact docker, its related to file permissions issues with reading/executing the scripts. Keep in mind on WIndows, we only support using Docker for Windows, so this is very ymmv territory

@eleftrik is your Docker host setup to accept insecure connections? You are hitting it via HTTP.

**Comment by garrettw** [comment]
> this is very ymmv territory
@dustinleblanc yep I know. But which side of Docker (CLI or daemon) do you think the permissions issue stems from? Or do you have any idea how I could determine that?

**Comment by eleftrik** [comment]
@dustinleblanc Honestly I don't know, I guess so, because of "http://" URL. Anyway, I'm using it only for local development.

Is it related to this issue?

**Comment by iBobik** [comment]
Generally will be nice if Lando support Docker Machine env variables: #1101

**Comment by dustinleblanc** [comment]
Trying to use anything other than what we have now will increase the complexity of maintaining Lando so I doubt we'll do much to alter the current behavior. We _did_ make some changes that allow you to connect to the daemon over TLS if you set the environment variables but it has proved less than useful because remote docker doesn't really let you do volume mounting in quite the same ways

**Comment by iBobik** [comment]
I understand it could add more complexity, but that complexity is in other Docker clients and I think consistency has a value (users expect some behavior).

About volumes: There is a lot of use-cases where "remote" machine runs locally and common locations are mounted (home directory), so it will not be problem. Other usecases can be covered by a visible warning (e.g. "Lando does not care about volumes binding for remote machines, so it could not work.")

So it could be implemented it this minimal variant - only change connection to network socket if there are environment variables.


Jan Pobořil
https://honza.poboril.cz/

10. 12. 2018 v 15:42, Dustin LeBlanc <notifications@github.com>:

**Comment by pirog** [comment]
@iBobik Lando *purposefully* ignores any `DOCKER` environment variables the user might be using because officially we only support using docker with its factory default settings and this provides the maximum stability and lowest maintenance cost.

And while Lando is *technically* a docker client insofar as it talks to a docker server it is a very very different than things that are advertised exclusively as "docker client" so i dont think it makes sense for Lando to have the same expectations as say dockerode. Furthermore, while we do expose some of the underlying docker config and acknowledge its existence as the container engine of lando it still is more or less an implementation detail eg users do not/should not need to know docker exists, what it is, that its part of lando, etc.

im going to close this out for basically housekeeping purposes and because we dont have any immediate plans to officially support WSL or non-default docker configurations. that said feel free to continue the discussion and we will check in periodically

**Comment by w-biggs** [comment]
I was also getting this error - it's because the Docker container wants to modify files in the WSL filesystem - specifically `~/.lando` - which is read-only to Windows processes. Setting `LANDO_CORE_USERCONFROOT` to a location within a drive shared with Docker fixed the issue for me.

**Comment by philwilliammee** [comment]
@w-biggs can you expand on your solution? where do you set LANDO_CORE_USERCONFROOT?

**Comment by plato1123** [comment]
Anyone know where you set LANDO_CORE_USERCONFROOT??
