### ISSUE TITLE
Don't prompt for latest version for every command

### ISSUE THREAD

**Issue by hussainweb** [lando/lando#1077]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.45 on Mac OS X High Sierra
(I read the instructions to try on the latest version, but this problem is going to come up only on an older version.)

**Tell us about your `.lando.yml`**

I am happy to share this but this is irrelevant. If not, please let me know and I will update.

**Tell us about the command you were running**

```bash
lando info | jq
```

**Tell us about the error you got**

It's not an error.

**Tell us generally about your bug**

Certain Lando commands always output a message that shows there is an update available. I am fine if this happens once in a while (like once in a day or something), but this happens for every run.

The problem is, apart from being annoying, is that I can't pass JSON output to something like `jq`. For example, I commonly run `lando info | jq` but because of this message, JSON parsing fails.

**Tell us more**

One idea I can think of is sending this output to stderr. I'd rather this become more intelligent and only output this message once a day or something similar.

I understand that you want to encourage updates but 300 MB updates aren't practical every time they are out. Besides, changes in beta46 and beta47 are completely irrelevant for me. It would be a different story if you had releases without Docker (so that the dmg file is smaller) but that's a different issue. In any case, I'd suggest making this update notification a bit more intelligent.

Does this bug prevent you from using lando?

Not really.

**Comment by marcaddeo** [comment]
Yeah, it would be nice if Lando handled it's output a bit better. I also wanted to pipe `lando list` to `jq` in order to allow my local Drush alias to detect if it's inside of a Lando based directory. I couldn't do it because of the update message. I instead have to rely on reading `~/.lando/cache/registry` which is not as reliable.

Sending that to `stderr` would be a good start, but there's other issues I've noticed with output as well.

For example, if you type `lando start` and then start typing your next command `git status`, for example, your next command you've typed gets swallowed by Lando. Most unix utilities do not act like this, and stop capturing `stdin` when not necessary.

**Comment by uberhacker** [comment]
Not sure why #183 was closed but related?

**Comment by pirog** [comment]
Going to close this in favor of #1000
