### ISSUE TITLE
Problem with pantheon recipe, advanced page cache , and varnish proxy header limits configuration.

### ISSUE THREAD

**Issue by bob-hinrichs** [lando/lando#1142]
Bug Report
==========

running pantheon recipe, on a mac High Sierra (likely not mac-specific), running Drupal 7 with pantheon advanced page cache.
v3.0.0-beta.47

**Tell us about your `.lando.yml`**
name: cse-1
recipe: pantheon
config:
  framework: drupal
  site: cse1
  id: edc7f73f-ddbb-404b-a5e2-e8890ee8c86a

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe
api_version: 1

php_version: 7.1

web_docroot: true

Paste in a series of commands that caused the bug.
Firing up a somewhat complex site that issues a healthy number of cache tags.  It does not take many to cause lando to fail.  The pantheon advanced page cache threshold is MUCH more data than is being allowed by the edge service.  Fix is below.

**Tell us about the error you got**

Varnish chokes on some pages and issues a 503 for some pages because the Drupal backend issues a HTTP reply header that exceeds the default size allowed by varnish.

Does this bug prevent you from using lando?
It reduces its value because we cannot test the site with edge URL.

**TELL US HOW TO FIX IT**

If you enter the varnish container in a bash shell and run a curl command to retrieve this url (using 'nginx' in place of cse1.lndo.site in the example URL), you'll get a response.

However, if you tail the varnish log (by running "varnishlog") and then try to request the URL in your browser, varnishlog will show it complains about the HTTP header size returned by drupal.

There's probably an easier way to remedy this, but the workaround I have for now is the following, which involves editing the varnish configuration:

(1) Go into the varnish container:

docker exec -it cse1_edge_1

(2) install vim (or whatever cli text editor you prefer)

apt-get update && apt-get install -y vim

(3) Edit the chaperone config file (chaperone is used to start varnish with specific parameters) so that the following line is change from

PARAM_VALUE: "${PARAM_VALUE:--p default_ttl=3600 -p default_grace=3600}",

to:

PARAM_VALUE: "${PARAM_VALUE:--p default_ttl=3600 -p default_grace=3600 -p http_resp_hdr_len=32768}",

**Comment by dustinleblanc** [comment]
Do you have `http.response.debug_cacheability_headers: true` in your development.services.yml and are you loading that file? I've run into this frequently on Pantheon sites as it increases the size of the headers beyond what Styx can handle. This will often fail locally and not on Pantheon because you only include the file locally.

**Comment by possiBri** [comment]
Hi I'm also experiencing this issue. As far as I can tell we don't have the Pantheon Advanced Page Cache module (unless I'm misunderstanding what you're referring to) so I was hoping to get some clarity on how I can debug this issue to determine the root cause. I suspect it's related to query timeouts, but since it's only happening on my local it's hard to be totally sure. Any suggestions/guidance are greatly appreciated!

**Comment by torgospizza** [comment]
I ran into this issue, and disabled the Pantheon Advanced Page Cache module solved it for us as well. Happy to attempt other methods of debugging to get this fixed. Thanks!

**Comment by pirog** [comment]
you probably want to disable the  Pantheon Advanced Page Cache module locally but i think we should also just bump the max varnish header size

**Comment by pirog** [comment]
set `http_resp_hdr_len` to `64000` because yolo
