### ISSUE TITLE
Option to start lando in non-daemon mode

### ISSUE THREAD

**Issue by mstruebing** [lando/lando#1147]
Hello, as a User I want to be able to start lando in a `foreground-mode` or a `non-daemon-mode` similiar to `docker-compose up` instead of `docker-compose up -d` because it would be a better developer experience for me when using lando i.e. I can see logs immediately and I can not forget to stop it and let the container running when I'm finished with the work on this project.

**Comment by dustinleblanc** [comment]
@mstruebing you can simply run `lando start && lando logs -f` to get this kind of functionality. I don't foresee us dumping you straight into the log stream, even as an optional parameter since the work around is so easy. If we get a bunch of other feedback that this is useful for a ton of people though, maybe we can consider it.
