### ISSUE TITLE
Start multiple project instances at once

### ISSUE THREAD

**Issue by milkovsky** [lando/lando#1167]
**Goal:** I would like to start multiple project instances at once to work in different feature branches in parallel.

**Given:**
I have 2 identical git checkouts of the same project.
Every checkout has the .lando.yml file
```
name: "myapp"
recipe: drupal8
```
If I do lando start in every folder, the "myapp" containers get overridden, when I start the 2nd project.

Is there any solution to start the same checkout 2 times using lando?

Related issues:
- https://github.com/lando/lando/issues/749
- https://github.com/lando/lando/issues/357

**Comment by milkovsky** [comment]
One possibility can be to support environment variables in the .lando.yml file as it was mentioned at https://github.com/lando/lando/issues/749.

The yaml file could look like this:
```
name: "${APP_NAME}"
recipe: drupal8
```
Every checkout could have a custom .env file in gitignore with:
```
APP_NAME=myapp1
APP_NAME=myapp2
```

Is it possible currently?

**Comment by milkovsky** [comment]
Option 2: use .lando.overrides.yml file like in docker-compose. Is it possible with lando?

**Comment by dustinleblanc** [comment]
@milkovsky, the easiest way to do this right now is just to give the second instance of the app a different name. The aforementioned features would probably work too long term, but for a quick work around, modifying the file for the second instance is the way to go. I am going to close this as a support request since the actual changes to lando are discussed as other tickets, let us know if you need more help in our slack channel or by discussing some of those other issues inside their comment threads. Thanks!
