### ISSUE TITLE
Can't seem to run more than 1 project at once

### ISSUE THREAD

**Issue by ibdf** [lando/lando#1224]
Lando -> v3.0.0-beta.47

Before version 3 I used to be able to start multiple lando projects at once. Now whenever I start a second project with ~ lando start,  the first project is gone.
When I look at the running containers in docker (~ docker ps), I only see the latest project I started.

I'm using lando with the default wordpress recipe, the only change in the lando.yml file is the project name.
I'm on a Mac / Mojave, but have been experiencing this issue before I upgraded to Mojave.

**Comment by ccharlton** [comment]
After you start the second lando app: when you run `lando list`, do you see `"running": false` on the app you were first running?

**Comment by ccharlton** [comment]
Secondly, have you tried upgrading to version v3.0.0-rc1?

**Comment by ibdf** [comment]
I completely forgot about this. My issue went away with one of the updates. I cant pinpoint what was going on, but it's now solved. Thanks.

**Comment by jhoell** [comment]
This same issue happens to me every single day (Lando -> v3.0.0-rc.17)

**Comment by pirog** [comment]
@jhoell you are going to need to do a much better job describing what you are seeing and giving steps to replicate. If you do not it is very difficult and costly for us to try and assist.

**Comment by jhoell** [comment]
@pirog sorry but what I was saying is that my issue is exactly the same as the OP. What more info do you need? I used to be able to run multiple lando sites locally every day no problem. Since about v3.0.0-rc.15 I can no longer do that. I lando start one site, everything is fine and works as normal. I lando start another site and the the first site almost immediately no longer runs in the browser.

**Comment by pirog** [comment]
@jhoell if it was _exactly_ the same im guessing it would have also been solved in that seemed to be the case for the OP.

Specifically what i mean is actually writing out the steps i can take to reproduce what you are seeing. 

I, and a large percentage of our users, run more than one project simultaneously so my suspicion is there is some about what you are doing in particular that is causing what you are seeing.

**Comment by jhoell** [comment]
Step 1: lando start Site #1
Step 2: load https lando url of Site #1 in browser
Step 3: lando start Site #2
Step 4: load https lando url of Site #2 in browser
Step 5: reload browser window of Site #1
Step 6: receive error in browser "This site can’t be reached eastern-propane-new.lndo.site refused to connect."

I've been using lando every day for the last year and a half for my job. It's always worked great. This issue has just started happening within the last couple of months and it's really slowing down my workflow.

**Comment by pirog** [comment]
@jhoell yeah again _those steps_ do not replicate the problem me or the vast majority of people using lando so you are going to need to provide _actual steps to replicate._  it's going to be something that you are doing differently than everybody else. i know that doesnt narrow it down a ton but we can't help you if we cant see the problem.

For example: I have no idea what kind of sites you are running. I don't know if you've tried to destroy them and recreate them. Do they happen with _any_ two sites or just _two specific sites_, etc, etc

We haven't changed code a lot in the last two months so i think its highly unlikely its something directly caused by lando itself. Doesn't mean impossible but we'd expect A LOT more error reports on this problem if this were a widespread concern.

**Comment by jhoell** [comment]
Hi @pirog, It is all sites that I work with. They are all Pantheon WordPress sites. 

I've just tried lando destroy on 2 specific sites, then lando rebuild on both. The same issue happens.

Let me know if there's any other information I can provide. Thanks.

**Comment by ccharlton** [comment]
@jhoell is the site id/name of the two Lando Apps/Sites different? Make sure they're both not sharing the same site ID/Name `eastern-propane-new`. That scenario happens when you clone an additional copy of a site that Lando already knows about; the workaround for that is just to edit the `.lando.yml` file and change the 'name' key to be unique.

**Comment by jhoell** [comment]
@ccharlton thanks for the idea, but no, all sites have unique ID/names.
