### ISSUE TITLE
After lando init and lando start we have xdebug enabled by default, but xdebug.remote_enabled = 0

### ISSUE THREAD

**Issue by marceldobrica** [lando/lando#1245]
Feature Requests and Bug Reports
--------------------------------
How to reproduce.
Create a folder, lando init (web, drupal8, as default options)
Lando start.

By default we have xdebug enabled, with some defaults:
xdebug.remote_enable | Off | Off
xdebug.remote_host | localhost | localhost

I don't understand why such defaults. If we have xdebug enabled by default why not with good ones ?
To have xdebug correct configured we have to write:
services:
  appserver:
    xdebug: true

Thank you all for support

**Comment by marceldobrica** [comment]
**It should be nice to have a more modular approach in lando.**
For example a lando.yml file may have 
name: some_name
recipe: drupal8
config:
  xdebug: true|false (with remote enabled and remote_host configured and default true)
  whkhtmltopdf: true/false (default false);
  phantomjs: true/false (default false);
  node: true/false (default false) - node inside main container (for example for Four Kitchens emulsify theme)
Some of these options are already defined but some of them not yet even, for example, whkhtmltopdf and phantomjs are already set in phanteon recipe.
...
also, for example, a lando.yml file like this one:
recipe: phanteon
config:
 framework: drupal8
 php:7.2 
will install phanteon recipe (with phantomjs and whkhtmltopdf) but with php 7.0. A better modular approach should install php 7.2....

**Comment by dustinleblanc** [comment]
There is an existing ticket about the confusion with xdebug config, if you search for xdebug in the issues you can probably find it. We want to actually fix things so that xdebug config is completely removed when it is off. As for the other ideas, like adding those extra services as options. I'd be inclined to say that it's better for Lando to not have to maintain config for these items and rather rely on the user to enable these in their own config (via build hooks or customizing the docker file). Checkout our advanced docs for clues on how to do that. Thanks!
