### ISSUE TITLE
Quicker way to download

### ISSUE THREAD

**Issue by gregbia** [lando/lando#1258]
I want to test Lando on a mac using dmg, as I'm not very experienced with the other methods but I'm waiting 2-3 hours (sometimes jumping to 15 hours) for the download to finish.  My download speed is 44 Mbps.

**Comment by gregbia** [comment]
Why put a large file on github? Its slow

**Comment by philltran** [comment]
Have you tried using homebrew cask to download and manage Lando? I am not sure if that would help your DL speed issue, but it downloads via terminal instead of web browser.

44Mbps speed shouldn't take hours  to download. 

Instructions for installing homebrew are at: https://brew.sh/
Then you can install lando using` brew cask install lando` int he terminal

**Comment by dustinleblanc** [comment]
Lando should typically download in a minute or two at most on most connections. Sorry to hear that is the case @gregbia, however, its not something I've even experienced myself or had other reports of. @philltran I imagine that the homebrew cask is pulling from our releases anyway, but I could be wrong.

**Comment by gusdecool** [comment]
I also have the same problem, tried using `brew cask install lando` as @philltran suggested. Then found out the cask aldo downloading at the same endpoint with github releases which mean still slow.
