### ISSUE TITLE
Environment variables reloading

### ISSUE THREAD

**Issue by kristoftorfs** [lando/lando#1265]
Feature Request
===============

Please explain your request and its importance in the form of a user story.

Whenever I make a change in my projects' `.env` file I need to rebuild the entire project. This can be very time-consuming, and would be better if changing environment variables would only require a restart.

Please provide some detail on how lando can help solve this problem

I noticed that in the generated docker-compose files you include all environment variables under the `environment` option. While this is fine for all LANDO_* variables, it would be better to use the `env_file` option of docker-compose for project variables, which would make it so that only a project restart is required to reload the variables.

**Comment by dustinleblanc** [comment]
Thanks @kristoftorfs! I agree that it'd be nice to not have to rebuild to reload environment variables. Thanks also for the implementation suggestion.

**Comment by pirog** [comment]
@kristoftorfs we are switching over to something like this https://github.com/lando/lando/pull/974#issuecomment-453836939 in RC2 however AFAICT it still requires a `rebuild` for those changes to take. 

It is by design that changes to your landofile require a rebuild so that restarts do not mutate your containers and produce unexpected results. Recognize this can be annoying if you are changing environment variables around a lot but generally we do not expect or encourage users to be rebuilding their app very often.
