### ISSUE TITLE
Write to disk performance issues

### ISSUE THREAD

**Issue by chrisarcherhydrant** [lando/lando#1277]
Lando is great and arguably the best local development tool I've seen in a while.  But it seems to have one big issue which is speed, which is more of a docker issue than Lando.  

The main noticeable speed issues are: 

1. When installing a fresh Drupal site from config, when you are installing a Drupal site from config with Lando it can take up to an hour but with other tools such as DevDecktop it takes 10 - 15 mins tops.
2. Trying to edit a large view can be sluggish.
3. When doing DB updates this can again take time.

With these, I have also had from time to time NGNIX 503 timeout issues.

Has anybody found a suitable, deployable solution for these issues?

**Comment by vielhuber** [comment]
Same problem here.

Is there an option to completely disable syncing / mounting of special folders? That should improve the performance drastically.

**Comment by chrisarcherhydrant** [comment]
I'm not sure there is, plus disabling syncing / mounting, defeats the point of using Lando.  There is Docker Sync but not had a look at that yet http://docker-sync.io

**Comment by dustinleblanc** [comment]
@chrisarcherhydrant see #763 

We've talked this one into the grave :smile:

That said, I think this is something we'd love to to more work on, I've experimented a bit with some named volume hacks, but we haven't decided on anything yet. The easiest answer is 'use linux' but I understand that's not always possible :)

The issue is with upstream docker for mac and docker for windows in general. DevDesktop does not use docker and is therefore not susceptible to this issue.

If you want to chat about it further, head over to that other issue
