### ISSUE TITLE
Request: Exclude functional tests from repository. Make test path to Lando bin absolute.

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1296]
In PR https://github.com/lando/lando/pull/1246 you can see that my functional tests require executing Lando from various directories. The functional test generator expects the Lando command to be executed from within the app root and therefore replaces references to `lando` with `node ../../bin/lando.js`.

As you can see in the PR I was able to work around this by caching the path to Lando in a variable and working some bash magic, however, it overcomplicates the `readme.md` of the example and adds bash logic that is only relevant to the functional test, and not the greater Lando user base.

My proposal is:

1. Because functional tests are recreated upon `yarn test:functional` that they be excluded from the repository.
2. Replacing references to `lando` with `node $absolutePath/bin/lando.js`

**Comment by pirog** [comment]
@tylerssn we ended up following 1 in your list of proposals in our RC2 branch. We ended up spinning off the functional testing framework into another project called LEIA https://github.com/lando/leia which just assumes what you need is in `PATH` somewhere. This adds a little extra complexity in so far as the user needs to make sure the correct thing is being used EG the source version of lando being used instead of one provided by one of our installers but simplifies everything else quite a bit
