### ISSUE TITLE
Proposal: Fewer images to save space!

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1340]
This might be a bit of work but would it make sense to create base images that are configurable on demand?  For instance, instead of having separate images for specific versions of services, would it be possible to have the ability to switch to the version you need in the container instead?  More clearly, instead of having separate images for every version of php, provide one image that includes all php versions and just enable the version you need in the container.  Below is an example of why this might be important to consider:
```
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
devwithlando/php                  5.4-fpm             d3c80a1d225b        9 days ago          1.02GB
devwithlando/php                  7.1-apache          41398cc0e064        9 days ago          847MB
devwithlando/pantheon-appserver   7.1                 3fa775c27c0c        13 days ago         1.46GB
devwithlando/pantheon-appserver   7.0                 4639ea7c10bc        13 days ago         1.45GB
devwithlando/pantheon-appserver   5.6                 7006949a564e        2 weeks ago         1.44GB
devwithlando/php                  5.6-apache          1c1f528b1994        2 weeks ago         833MB
devwithlando/php                  5.6-fpm             5c96e95c7a79        3 weeks ago         824MB
```
As you can see, we currently have separate Pantheon images for each version of php and separate versions of apache/nginx/php as well.  I imagine if this was possible, I could regularly save several GBs of valuable disk space.

**Comment by pirog** [comment]
@uberhacker this is unlikely to happen. 

We actually did exactly this in kalabox, with a php consolidation utility to show for it called [php brewer](https://github.com/thinktandem/phpbrewer), the problem is that while it does save you some storage it makes basically everything else WAY more complicated and tricky. For example managing multiple versions of php in one container is not going to be the same as managing multiple versions of nginx in another, this doesnt scale well as you add more and more services and versions. It's also a problem that the docker community has more or less come to a consensus on: solve it by having images with tags for different versions.

This also would introduce two models that we use to manage service versions eg Docker and our own thing. 

So, ultimately it's a lot of work and extra complexity for not a ton of gain especially as we try to shrink and lock down the core API that will be the lando stable release
