### ISSUE TITLE
Bash conditional statements fail in .lando.yml

### ISSUE THREAD

**Issue by westonruter** [lando/lando#1377]
I'm trying it out and I'm seeing what may be a regression in RC2 running commands from `.lando.yml`. I have a section like:

```services:
  appserver:
# ...
    run:
      - if [ ! -e $LANDO_MOUNT/public/core-dev ]; then git clone https://github.com/WordPress/wordpress-develop.git $LANDO_MOUNT/public/core-dev; fi
```

When I do `lando rebuild` I'm getting a failure:

> OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"if\": executable file not found in $PATH": unknown

This worked fine in RC1.

I'm running v3.0.0-rc.2 on MacOS 10.14.2.

**Comment by pirog** [comment]
@westonruter its worth pointing out that this syntax was never _officially_ supported so _technically_ i dont think this is a regression. That said im guessing a lot of people have done t_his sort of thing_ since it happenstance worked in the past.

Some cursory investigation here shows that the following **does** work

```yaml
run: 
  - /bin/sh -c "if [ ! -z $LANDO_MOUNT ]; then echo stuff; fi"
```

I think this implementation might be preferred even if its not as readable as it was before because we probably dont want to assume `sh` or `bash` under the hood and leave that up to the user

```yaml
run: 
  - /bin/bash -c "if [ ! -z $LANDO_MOUNT ]; then echo stuff; fi"
```

You also can do something like this to make things more readable
```yaml
  run:
      - |
        /bin/sh -c "
        if [ ! -z $LANDO_MOUNT ]; then
          echo stuff;
          echo
        fi
        echo things
        "
```

I think the best pathway here is just document this in our core build step docs as well as the RC2 guide to make the following more clear

1. We recommend you put complex BASH/SH things into a script and invoke that
2. If you dont want to do that you will need to wrap it in `bash` or `sh` as above

**Comment by pirog** [comment]
Ok this is now documented here
https://docs.devwithlando.io/config/services.html#using-scripty-things

and here
https://docs.devwithlando.io/guides/updating-to-rc2.html#build-steps
