### ISSUE TITLE
How to override appserver_nginx in drupal 8 recipe?

### ISSUE THREAD

**Issue by troseman** [lando/lando#1487]
I'd like to override the volume for the nginx service created with the drupal 8 recipe.
Here's my attempt:

~~~~
services:
  appserver:
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app:nocopy"
  appserver_nginx:
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app:nocopy"
~~~~

I get a syntax error on lando rebuild because of the appserver_nginx block.

error: TypeError: Cannot read property 'split' of undefined
    at exports.parseConfig._.map.map.service (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)

What's the right way to target the nginx in appserver for an override of volume?
btw, the appserver override works fine. I tried putting a services block under appserver but that didn't work and I know it's the old syntax. thanks

**Comment by pirog** [comment]
Great question here @troseman but i think this actually should be a bug. 

With the exception of use in `proxy` config we don't actually want users overriding "lando managed"  services. I think what we want is for users to be able to do 

```yaml
services:
  appserver:
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app:nocopy"
```

And have those overrides apply to both the `appserver` and any other "derivative" or "companion" services lando spins up internally to go with said service. That said, this doesn't seem to be the actual behavior currently.

**Comment by troseman** [comment]
that would work perfectly, thanks!

**Comment by pirog** [comment]
@troseman this is now in https://github.com/lando/lando/releases/tag/v3.0.0-rc.13 

and you can see an example/test of how it works over at
https://github.com/lando/lando/blob/master/examples/php/.lando.yml#L22

note that in that example the overrides for `appserver` will also show up in `appserver_nginx`, with the exception of the overridden image since that would likely not be a good idea ;)

**Comment by arcataroger** [comment]
> @troseman this is now in https://github.com/lando/lando/releases/tag/v3.0.0-rc.13
> 
> and you can see an example/test of how it works over at
> https://github.com/lando/lando/blob/master/examples/php/.lando.yml#L22
> 

The override in that link doesn't show a volume mapping.

I'm trying to do:

`  appserver:
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app:cached"
`

But get the following errors:

> Cannot create container for service appserver: create .: volume name is too short, names should be at least two alphanumeric characters
> ERROR: Encountered errors while bringing up the project.
> WARNING: The LANDO_VOLUME variable is not set. Defaulting to a blank string.

My objective is to try to speed up Docker on OSX for a Pantheon recipe. Lando is currently unusably slow, and I read through #763 as much as I could, but you seem to say not to use docker-sync, so I'm hoping this might help a bit in the meantime =/

What's the proper way to override a volume inside the appserver_nginx for pantheon so that it can be cached?

**Comment by rwohleb** [comment]
I would also like to know how to do an override on the volume mapping. Alternatively, just being able to swap from delegated to cached would be beneficial.

**Comment by pirog** [comment]
Beneficial in what way? Delegated is the most performant option.

**Comment by rwohleb** [comment]
As per https://docs.docker.com/docker-for-mac/osxfs-caching/, “cached” is good for read-heavy workloads. Delegated and cached may frequently have similar performance characteristics, and delegated can often be better, but this can change across Docker for Mac versions. Additionally, they are working on adding caching options (https://github.com/docker/for-mac/issues/1592#issuecomment-609704778) so allowing for an override by advanced users, even if unsupported, would be beneficial.

**Comment by pirog** [comment]
@rwohleb we are pretty familiar with the docs but thanks. we havent observed a situation where cached provides better performance than delegated. regardless, the excludes feature documented over [here](https://docs.lando.dev/config/performance.html#configuration) will likely provide you with the best performance boost although it comes with caveats.

if and when there are different caching options provided by docker we will reevaluate how lando uses them.

**Comment by pirog** [comment]
@arcataroger no because we are already doing the most performant volume mounting option that is available eg the override that you want to do is likely going to make things slower, not faster. in the best case scenario it will be about the same.

our recommendation is to utilize the feature documented [here](https://docs.lando.dev/config/performance.html#configuration) if the underlying docker file sharing performance is not acceptable.

beyond that we recommended people check out #763 if they have interest in the file sharing performance

**Comment by rwohleb** [comment]
@pirog, apologies if that came across as suggesting you don’t know the docs. I’m sure you do many MANY times greater than I do. I was merely trying to be succinct.

I don't think that arcataroger or I are looking for any new feature to be added to allow us to easily change the mount. Nothing like the exclude support. I am just looking for feedback on how one might do this through the existing override system, if even possible. I want to test performance for my specific usage/load patterns as the guarantee differences between cached and delegated could affect it in certain scenarios. I won’t know until I try.

**Comment by pirog** [comment]
@rwohleb no worries, just saying we've read them a few times ;)

So, this works for me for setting the`/app` mount on the `appserver` and `appserver_nginx` from `delegated` to `cached` on a basic pantheon recipe

```
name: landobot-drupal7
recipe: pantheon
config:
  framework: drupal
  site: landobot-drupal7
  id: 6e8d4bb2-dd6f-4640-9d12-d95a942c34ca
  edge: false
services:
  appserver:
    overrides:
      volumes:
        - ./:/app:cached
```

However, given the problem noted in #2029 it might be desirable to provide easier per-service configurability of the app mount eg something like

``````
services:
  appserver:
    app_mount: delegated|cached|consistent|default|disabled|tbdfutureoption
```
