### ISSUE TITLE
Please provide OSX package without docker

### ISSUE THREAD

**Issue by sharique** [lando/lando#1509]
With docker package included in the Lando setup,  it becomes very big, since you are releasing frequently, with such a big package it a long time to download, hence it becomes very difficult to keep up to with releases. 
A lot of people already have docker install, so it makes sense to have a package without docker included.
Also, it will save expensive bandwidth for mobile network user (I use it while working from home).

**Comment by pirog** [comment]
@sharique this is already covered by #1414 although for different reasons.

I will also say that we will never officially support an unbundled lando installer because its important for us to explicitly pin our docker dependencies. A user already having docker installed doesnt mean that lando will automatically work. If they have a version of Docker from two years ago that is probably going to be a problem and that translates to additional support noise on our end.

It's also worth pointing out that

1. If bandwidth and/or download time is a big concern of yours then any docker based solution is likely going to be problematic
2. You can control whether you download the new version or not
