### ISSUE TITLE
Ability to execute build steps on different services in a specific order

### ISSUE THREAD

**Issue by nicrodgers** [lando/lando#1524]
As a lando user, I want to configure the order build steps run across different services, so that if a script is dependent on another script running first, everything works ok.

For example, one project has two build steps.
1. create database fixtures on db service
2. run java job to populate database with current data, using java service

Step 2 must run after step 1, otherwise it will fail because the database fixtures don't exist.

**Comment by dasginganinja** [comment]
+1

I have a multi-step build process and would be interested in this as well. 

1. appserver: `composer install`
2. node: `cd web/themes/custom/emulsify && yarn install`
3. appserver: `cd web/themes/custom/emulsify && composer install -n patternlab [...]`
4. node: `cd web/themes/custom/emulsify && gulp compile`
5. appserver: `drush si`

**Comment by pirog** [comment]
@nicrodgers @dasginganinja its highly unlikely we will support this feature because its already possible to achieve this sort of thing using existing lando or docker mechanisms and given that it seems like a ton of extra engineering work on our end

1. build steps are designed to install server dependencies and should not be coupled to the state of other services,
2. event commands can already be run sequentially 
3. tooling commands can already be run sequentially 
4. if you really need a build step to depend on the state of another service you can override said serivces and use the "depends_on" docker compose key

Definitely check out the docs for build steps and events for more reading.
