### ISSUE TITLE
Drush doesn't use the alias file define in ~/.drush/site-aliases/ 

### ISSUE THREAD

**Issue by Calystod** [lando/lando#1621]
Hello,

I'm using the last version of lando 3.0.0-rc16 and I have a problem with aliases for Drush. Like we're using drush outside of lando sometimes, we don't have put aliases in the directory /drush/ to don't use this aliases file if we are outside of lando like root are different.

So, we have our aliases file in our $HOME/.drush on our machine, and it works.

For lando, we have add the following line:

```
appserver:
    build:
      - /bin/sh -c "mkdir -p ~/.drush/site-aliases"
      - /bin/sh -c "ln -sf /app/drush_lando/my_project.aliases.drushrc.php ~/.drush/site-aliases/my_project.drushrc.php"
```
If I go on the lando container via `lando ssh` and verify if the file have been correctly copy, that fine, it's present. But when I use drush inside lando, it doesn't find aliases so my commands failed.

If I use `lando drush sa`, I don't have my define aliases and if I do a `lando drush status`, the parameter "Drush alias files" is empty.

The Drush version in lando is 8.2.3, same thing on my computer.

I don't know if something is missing in my configuration or if it's a bug of lando or drush.

**Comment by daniortega** [comment]
Hello, I have the same issue. Same configuration in lando.myl, when rebuild I have the alias file inside container, but when I execute 

> lando drush sa

 inside app (not inside lando container) returns  

> [success] No site aliases found.

**Comment by zuernBernhard** [comment]
Had the same problem here. I did not want ,my hole ~/.drush from the host within Lando and decided to go another way: 

I put the Site-Aliases in the repository but not under /web one live above /app/drush/*.yml and Drush was not able to find them. 

Turns out drush is not scanning the drush folder above the web-root (Drupal-root) but a sites folder within it: 

```
www-data@b81f291f7464:~$ drush -vvv sa
 [preflight] Config paths: /app/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /app/web/drush/sites,/app/drush/sites
```

after moving from /drush/<youralias>.yml to /drush/sites/<youralias.yml>  a 

```
lando drush sa
```

lists all those aliases as expected. 

In this case Drush 9 was used. If you have another version of drush perhaps a 

```
drush -vvv sa
```

can tell you there drush is looking for aliases in the filesystem.
