### ISSUE TITLE
How can I set the PHP 7 executable path for VS Code?

### ISSUE THREAD

**Issue by blu-regard** [lando/lando#1640]
When using VS Code and PHP IntelliSense plugin they are looking for a PHP 7 executable. 
`"php.validate.executablePath": null`

I'm running a Drupal 7 recipe and I've tried /usr/local/bin/php

My native OS is Windows 10.

**Comment by jorismulliez** [comment]
Hello,

I find a workaround in order to point to php through lando.
You have to create an executable sh wrapper : 
```
#!/bin/sh
lando php "$@"
```

and use it in your settings : 
```
{
    "php.executablePath": "/path/to/lando-php-wrapper.sh",
    "php.validate.executablePath": "/path/to/lando-php-wrapper.sh"
}
```

The caveat is that vscode won't allow you to set this settings at a "project" level.
So if you have some projects under lando, some others under vagrant and more locally, you'll have to edit your global settings each time you switch.

**Comment by amaisano** [comment]
@jorismulliez this kind of works, but the vscode Intellisense extension keeps failing to start the Language server. Separately, I'm trying to get this to work with the `php-cs` extension as well, but it's proving difficult.

**Comment by Aldo-f** [comment]
I got a ``spawn UNKNOWN`` error.

Placed the ``lando-php-wrapper.sh``  inside ``.vscode``

This is my settings.json
``` json
{
  "php.validate.executablePath": ".vscode/lando-php-wrapper.sh"
}
```

Path is correct, else the errror is something like:

```
Cannot validate since 
d:\Users\project-folder\wrong\path\lando-php-wrapper.sh is not a valid php executable. 
Use the setting 'php.validate.executablePath' to configure the PHP executable.
```
