### ISSUE TITLE
Spin up a dedicated sharing tunnel service for just lando

### ISSUE THREAD

**Issue by milkovsky** [lando/lando#1675]
`lando share -u http://localhost:32831` returns an error `tunnel server offline: Request failed with status code 502, retry 1s`.

OS: Ubuntu 18.04.2 LTS
Lando version: v3.0.0-rc.17
Docker version: 18.09.4, build d14af54266

I am using recepie drupal8.
I have checked my appserver url using `lando info` - it is https://localhost:32831.
I run `lando share -u http://localhost:32831`
Terminal output:
```lando share -u http://localhost:32831 -v
info: Bootstraping...
info: config bootstrap beginning...
info: config bootstrap completed.
info: tasks bootstrap beginning...
info: tasks bootstrap completed.
info: engine bootstrap beginning...
info: engine bootstrap completed.
info: app bootstrap beginning...
info: app bootstrap completed.
info: Bootstrap completed.
info: App config files found at ["/home/alex/projects/nd/.lando.yml"]
About to share your app to a whole new world!
info: App netdoktor is ready!
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
tunnel server offline: Request failed with status code 502, retry 1s
```

My `.lando.yml` file:

```
name: example
recipe: drupal8

config:
  webroot: docroot
  xdebug: true

env_file:
  - .env

services:
  appserver:
    config:
      conf: setup/appserver/php.ini
    build_as_root:
      # Install npm
      - curl -sL https://deb.nodesource.com/setup_11.x | bash - && apt-get install -y nodejs
  database:
    config:
      confd: setup/database/mysql
  db_migration:
    type: mysql:5.7
    creds:
      user: example
      password: example
      database: migration

tooling:
  npm:
    service: appserver
  mysql:
    service: database
  drush:
    cmd: /app/vendor/drush/drush/drush

proxy:
  appserver:
    - example.lndo.site
    - ch.example.lndo.site

```

**Comment by mcaluag-sph** [comment]
It seems like this is not really a lando bug but looks like localtunnel.me is down

**Comment by pirog** [comment]
@milkovsky im guessing @mcaluag-sph is correct here. i'm going to change this to a feature request for us to launch our own sharing tunnel instead of relying on the free one.

**Comment by mcaluag-sph** [comment]
I'm excited to hear this plan of spinning up a dedicated sharing tunnel service for Lando. In any case, localtunnel.me is back and the share command works as advertised. It'd be good if options can be provided to also use other tunnelling services like ngrok, other than the dedicated one and localtunnel.

**Comment by pirog** [comment]
@mcaluag-sph it's highly unlikely we will provide different options beyond the dedicated service but those are things you could certainly provide yourself

**Comment by ElijahLynn** [comment]
:+1: localtunnel.me has only 1 server for the whole world and the maintainer has specifically said this is not a priority and a side project for them.

https://github.com/localtunnel/localtunnel/issues/261#issuecomment-407550521

> I am glad to hear this project is useful! However, I must also note that this project is a low priority side project for me. I come back to it from time to time (this is why some issues get closed, etc) but generally I would not expect a fast response from me here.
> 
> For those that do find the project useful but suffer from the flaky public server; the server is open source https://github.com/localtunnel/server and I recommend that if you have serious needs you set it up yourself. The client has a command line argument to use other servers.
> 
> I will continue to run the public server and make small tweaks here or there if I desire - however I would not consider this project actively maintained.

**Comment by pirog** [comment]
@ElijahLynn yup! the second paragraph in your quote is the plan!

**Comment by pirog** [comment]
It might be necessary to power up to ngrok to make this better

**Comment by pirog** [comment]
@mikemilano our current implementation of `lando share` is FUBAR because the free `localtunnel.me` server is down and no longer being maintained eg its EOL. This means we need to figure out a new implementation of `lando share`. 

My intuition says the path of least resistance here is for us to launch our own `localtunnel` server and just use that. The server part is open source and im guessing we could easily include it in the lando repo and launch it on platform.sh like we do for our other lando web properties. This would probably make development easier eg `lando start` -> `point lando share to local sharing server` -> `edit /etc/hosts as needed or do other local dns magic` -> `test lando share`.
https://github.com/localtunnel/server

On the flip side we could consider switching to something like `ngrok` however unknowns and there are how do we distribute the `ngrok` binary as part of Lando, guessing that will be tricky and what is the usage model. looks like we would probably need some sort of paid `ngrok` plan.

Regardless of which of the above we choose we should also take this opportunity to improve the `lando share` command. Right now you need to do something like this

```
lando share -u http://localhost:32785
```
see: https://docs.lando.dev/basics/share.html

This usually requires a user step beforehand to find the needed localhost port. It would be better if you could just run `lando share` and have lando spin up tunnels for any services in your landofile that have exposure over `http`. Optionally you could specify or exclude services with some kind of option.

**Comment by pirog** [comment]
@mikemilano im going to close this out in favor of internal tracking elsewhere
