### ISSUE TITLE
WSL2 engine Docker support

### ISSUE THREAD

**Issue by Cybercraft** [lando/lando#1723]
Hi,

As a Windows lando user, i've receive a mail (all Docker users has receive this mail) that suggest me to use WSL2 Engine available in the new technical preview.

It sound great but i've no idea if Lando will support the feature...

**Comment by DanielKulbe** [comment]
I tried to get my application running with a path inside WSL2. 

I have some additional volumes defined like
- 'lando/vhost.conf:/etc/nginx/sites-enabled/www.conf'

When the .lando file is compiled into docker-compose files it says
- '\\wsl$\Ubuntu-18.04\daniel\workspace\lando\vhost.conf:/etc/nginx/sites-enabled/www.conf'

As the Path contains a unescaped '$' the whole configuration breaks. This '$' should be escaped with another '$' Symbol.

**Comment by marsjaninzmarsa** [comment]
Plz unstale it, Win 2004 and WSL2 will land shortly...

**Comment by dustinleblanc** [comment]
fwiw, I am currently running Lando from source with WSL2 as my daily driver.It works great using Windows 10 2004 with the Docker 2.2.0.5 desktop client (set to WSL2 engine).

Some specific things to make this work it's best:

* Don't clone your app into the /mnt/c/ sub-directories (these are your windows FS mounted in WSL. Use the WSL home path (~ or /home/unixusername) as your root and you'll get much faster file io.
* IF you are going to install from a deb, you need to pass some flags to make Lando not complain about dependencies.
* VS Code has some nice integrations with WSL that make it a good text-editor to use

Since I'm using this fulltime, there will likely be more improvements to come to make it easier to use WSL2 on Windows, especially considering it goes GA next month.

**Comment by marfillaster** [comment]
To use Docker for Windows in WSL2, download the deb installer and install without docker-ce dependency.
```
sudo dpkg -i --ignore-depends=docker-ce lando-v3.0.0-rrc.3.deb
```

**Comment by dustinleblanc** [comment]
fwiw I've now got Lando running 100% purely via WSL2 and native-to-wsl docker, which makes performance WAYYYYY better than using the WSL2 integration from Docker desktop.

**Comment by mrweiner** [comment]
Wow that's awesome! I'd love to get this set up but have no idea where to start. Any resources or steps to setup that you could share?

**Comment by serundeputy** [comment]
@dustinleblanc Is this something that could use a Guide?

**Comment by dustinleblanc** [comment]
Yeah @serundeputy it's definitely something that could use some pretty in-depth content to talk about how I've got my windows setup dialed. It was a painful journey to get here, but so far since last weekend, its been stable. I should do a guide at a minimum

**Comment by web-assistant** [comment]
I'm fairly new to Lando. I have just updated Windows to version 2004 build. I'd like to try using WSL2. Can anyone point me to some information about how to do this?

**Comment by marfillaster** [comment]
@web-assistant 

I've been able to lando on WSL2 using Windows 10 Docker Desktop
1. Install the Windows Subsystem for Linux https://docs.microsoft.com/en-us/windows/wsl/install-win10
2. Install Docker Desktop on Windows Home https://docs.docker.com/docker-for-windows/install-windows-home/
3. Download latest .deb(For Ubuntu/Debian like distro) Lando release from https://github.com/lando/lando/releases
4. Install Lando in WSL2
    ```
    sudo dpkg -i --ignore-depends=docker-ce lando-v3.0.0-rrc.3.deb
    ```

**Comment by web-assistant** [comment]
@marfillaster thank you. I will give that a try 👍

**Comment by web-assistant** [comment]
@marfillaster Sorry, I'm quite new to Lando and Docker. I have WSL2 running in Windows. In Docker I settings I checked "Use the WSL 2 based engine" and also in Resources > WSL Integration I enabled 'Ubunto'. When I do Lando rebuild it completes but builds using Debian. How do I get it to build using Ubuntu, or is this completely the wrong way to do it?

> Install Lando in WSL2 w/o docker-ce

Can you provide more detail about doing this? Again, apologies, this is all quite new to me

**Comment by marfillaster** [comment]
@web-assistant 
1. Download https://github.com/lando/lando/releases/download/v3.0.3/lando-v3.0.3.deb
2. Open terminal (I highly recommend installing [Windows Terminal from Store](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)), enter bash
3. sudo dpkg -i --ignore-depends=docker-ce lando-v3.0.3.deb

**Comment by web-assistant** [comment]
@marfillaster Thanks again for the help. I did the above. When I run `lando rebuild` I get the following error: 

> Unhandled rejection Error: ENOENT: no such file or directory, scandir '/home/user_name/.ssh'

**Comment by marfillaster** [comment]
You probably need to setup an ssh key within bash.

https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Also make sure that you lando init inside bash too and preferably inside
your $HOME directory. If it still having issue, try to factory reset Docker
Desktop and review the appropriate settings that it's using WSL backend.

**Comment by web-assistant** [comment]
@marfillaster Thank you. I have it working!!

Probably a separate issue, I'm using 'drupal7' as the recipe in the .lando.yml file. I'm expecting drush to work but if I do `drush status` I get the error:

> Command 'drush' not found, did you mean:
> 
> command 'rush' from deb rush
> 
> Try: sudo apt install <deb name>

I just need to solve this problem and I'm good to go 😃

**Comment by web-assistant** [comment]
@marfillaster I deleted my previous question. It's all now working! Thanks again for all your help. Very much appreciated  😁👍

**Comment by GoonerW** [comment]
> 
> 
> @web-assistant
> 
>     3. sudo dpkg -i --ignore-depends=docker-ce lando-v3.0.3.deb

The problem with that approach is that every subsequent apt-get update will fail because a package is installed with an unmet dependency.  I used [this hack ](https://serverfault.com/a/506993/159910) to remove it once it was installed but there has to be a better way of dealing with this.  Optional dependency (not sure if that's possible) or release the .deb file without docker-ce as a dependency (surely one would need Docker installed either way anyway)?

**Comment by dustinleblanc** [comment]
So the way I got around this issue was to legit just install Docker in WSL. Screw Docker Desktop. It is way, way more performant now. My CPU usage and battery drain are soooooooo much better than they were using the Docker Desktop setup

I believe I followed this article for the setup: https://dev.to/bartr/install-docker-on-windows-subsystem-for-linux-v2-ubuntu-5dl7

I am even thinking https://github.com/lando/hyperdrive would legit work, and I am about to test that using an extra WSL2 environment (I'll set it up using Debian as a test case).

Using this method, the docker-ce dependency is installed and the only weird thing is that I have to do `sudo service docker start` before I can bring Lando up in the morning.

**Comment by dustinleblanc** [comment]
Just to add, Hyperdrive + WSL2 is instamagix

**Comment by ptmkenny** [comment]
After installing Docker in WSL2, I decided to go all the way and install PHPStorm too. This [is what Docker is recommending](https://www.docker.com/blog/docker-desktop-wsl-2-best-practices/) for best performance.

This assumes you already have Ubuntu installed with WSL2.

To do this, you need to install an X Server in Windows.  I used [VxcSrv](https://sourceforge.net/projects/vcxsrv/).

After installing, configure like this:

1. One large window (you can use multiple windows, but if you are going to use a desktop like Xfce4 you will get a mess).
2. Display number: 0
3. Start no client
4. Clipboard, primary selection, native opengl, and disable access control should all be enabled

When the Windows Defender firewall prompts come up, you need to make sure that xlaunch.exe and VcXsrv are both given access. If they somehow get blocked, you may waste an hour of your time debugging things before fixing it in the Advanced settings of Windows firewall. :)

Next, you need to get the GUI running in Ubuntu. I took the lazy way and installed the Xubuntu pack:

`sudo apt-get install xubuntu-desktop`

After installing you can launch with `startxfce4`.

Then you can open Firefox inside Ubuntu and download PHPStorm from the Jetbrains website.

This is really magical.

**Comment by GoonerW** [comment]
I'm on the opposite side of the coin.  I'm using WSL2 to host Lando/Docker (without installing Docker inside WSL2) and developing with VSCode and the RemoteWSL extensions.

Has there been any benchmark tests done with WSL2 and Docker outside vs inside WSL2?

**Comment by mrweiner** [comment]
Still working through getting everything set up, but @dustinleblanc suggestion for hyperdrive and @ptmkenny outline have been incredibly helpful. Just want to add a couple of notes.

- I've never used vxcsrv or the like before so had no idea how to get things running. This got me up and running no problem https://autoize.com/xfce4-desktop-environment-and-x-server-for-ubuntu-on-wsl-2/. You then need to open the Xlaunch application to actually run the X Server
- If everything ends up blurry in the server window, give this a shot: https://sourceforge.net/p/vcxsrv/discussion/986201/thread/86c22a03/. Seems like Cinnamon or Gnome might have better hidpi handling once you enable that setting, but `sudo cinnamon` was is throwing some errors that I don't want to figure out right now.

**Comment by mrweiner** [comment]
@ptmkenny have you managed to get xdebug working properly? I've opened up https://github.com/lando/lando/issues/2304 with some issues I'm facing.

**Comment by marfillaster** [comment]
@mrweiner if you're using PHP debug extension with Remote - WSL extension
in VSCode, you should set `hostname` to 0.0.0.0 in `launch.json`.

**Comment by ptmkenny** [comment]
@mrweiner 

Enabling Xdebug

This assumes you already did everything described in my previous post.

1. In PHPStorm, File -> Settings -> PHP -> CLI Interpreter -> `...` button
2. Press `+` button to add a new interpreter
3. 'from Docker'
4. 'Docker' radio button
5. For Server, click `New`
6. Choose `Docker` and connect by `Unix socket`, click OK
7. Wait for **image name** to populate
8. Choose `devwithlando/pantheonappserver` or whatever your appserver is
9. Click OK
10. Go to Settings -> Languages & Frameworks -> PHP and delete everything from **Include path** (you can use CTRL+A and the `-` button to select all and then delete in one action)
11. Install an xdebug browser extension (https://www.jetbrains.com/help/phpstorm/browser-debugging-extensions.html)
12. Toggle on browser extension, PHPStorm Xdebug
13. Reload your site; prompt appears from localhost in xdebug, accept
14. Path map must be fixed; go to Settings -> Languages & Frameworks -> PHP -> Servers and find localhost; set your project directory's **absolute path on server** to `/app`

That's what worked for me.

**Comment by ptmkenny** [comment]
How to fix high resolution scaling issues in VcXsrv with Xfce4.

Resolution scaling
* Only needed if you use a high resolution monitor in Windows and VcXsrv is blurry

1. Go to C:\Program Files\VcXsrv.
2. Right-click on vcxsrv.exe, choose Properties.
3. On the Compatibility tab, click "Change High DPI Settings."
4. Check the box for "Override high DPI scaling behavior" and choose "Application."
5. Do steps 2-4 for Xserve.exe in the same folder.
6. In Ubuntu, startxfce4.
7. Go to Applications -> Settings -> Settings Manager.
8. Go to Appearance -> Settings and set Window Scaling to 2x.

**Comment by ptmkenny** [comment]
Just another note for future documentation-- after installing docker, you have to reboot the system (`wsl --shutdown` from Windows) in order to get your linux user account into the docker group.  So if you install without rebooting, it won't work and will give a strange error when all you really have to do is reboot.

**Comment by mrweiner** [comment]
@ptmkenny thanks, that did it -- don't know how I missed the Unix Socket option for docker. This is much cleaner than the daemon.json solution I sorted out. Thank you.

Interestingly, I don't have the Window Scaling option available under Appearance -> Settings. Still looking around for a solution.

**Comment by mrweiner** [comment]
Alright I got everything set up on a clean Ubuntu 20.04. This got me the most recent version of XFCE so the scaling option is present. A few notes.

Hyperdive doesn't work out of the box due to how the docker package is defined. If you want to use it, for now at least, you'll need to do this before running hyperdrive to get the compatible/expected version of the docker package:

1. sudo apt update
2. sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
3. curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
4. sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
5. sudo apt update
6. sudo apt install docker-ce docker-ce-cli containerd.io

I got stuck hanging forever when `xubuntu-desktop` was setting up `mlocate`. By default, WSL indexes the entire windows machine as well as the linux machine since it's hooked up via `/mnt/c`. This can be helpful, but will cause this indexing to take forever. If you don't mind limiting this then (via https://github.com/Microsoft/WSL/issues/369#issuecomment-264543972) -- before installing xubuntu-desktop:

1. Add `/mnt` to the `PRUNEPATHS` variable in `/etc/updatedb.conf` to exclude bash from indexing files outside of the Ubuntu file space.
2. sudo updatedb.

PHPStorm also wouldn't recognize Xdebug in my CLI interpreter. You can fix this with [these steps](https://untoldhq.com/blog/2019/08/02/when-lando-phpstorm-and-xdebug-setup-gets-hairy):

1. `lando start` to get the machine running
2. `lando ssh` into the container
3. `ls /usr/local/etc/php/conf.d` and confirm that the file `docker-php-ext-xdebug.ini` is present
4. `cat /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini` and copy the path to the zend_extension that's returned.
5. Paste that path into the Debugger Extension field in your CLI Interpreter settings.
6. Click the refresh button next to the PHP Executable field.
7. Click Apply, ok, whatever that button is to save the settings.

**Comment by dustinleblanc** [comment]
@mrweiner Hyperdrive should work on the 18.04 image without having to do anything custom. Sounds like we'll want to update it at some point to support 20.04, but I don't think docker has technically released their repo for 20.04 yet anyway, so all of us intrepid folks are just shoe-horning the bionic repo in.

Y'all went above and beyond with setting up PHPStorm and all that, I had just resigned myself to using VSCode and/or Neovim inside WSL.

Also @GoonerW, no benchmark on Docker Desktop craziness vs inside WSL docker. I used the old fashioned ['Butt dyno'](https://www.urbandictionary.com/define.php?term=butt-dyno) to conclude that the performance is much better. At a minimum, the heat and battery drain are night and day different, and operations feel faster too. We're still not at bare-metal Linux speed, but we're closer than I've ever been with this kind of thing.

**Comment by mrweiner** [comment]
@dustinleblanc yup hyperdrive worked fine on 18.04, no problem. I actually didn't realize how recently 20.04 was released so makes sense that features are still flowing in in general.

Excited to see how this all works out -- been itching to get WSL2 working for a couple of "problem child" projects. At the very least, `composer install` ran like a dream, haha.

**Comment by GoonerW** [comment]
@dustinleblanc 
composer install et. al. with Drupal 8 are noticeably faster.

**Comment by arturolinares** [comment]
Docksal issue queue has a performance analysis comparing vs WSL: https://github.com/docksal/docksal/issues/1055#issuecomment-624925472

I've been using vscode in WSL2 for a while now, but I switched from vscode to  Sublime Text using an X server (because the editor speed is awesome, and it now supports LSP). Works perfect, even on a HiDPI screen. I'm using an alias to scale it correctly: `alias subl=GDK_DPI_SCALE=1 GDK_SCALE=2 /usr/bin/subl`.

I don't know why it works yet, but when trying to open a browser from sublime, it opens my browser in Windows. Like @ptmkenny said, it is really magical.

**Comment by GoonerW** [comment]
You can run windows commands from WSL2 as well.

Are you referring to running VSCode "within" WSL2 or on Windows with the Remote WSL2 extension?

**Comment by arturolinares** [comment]
With the remote extension. Works pretty well, but I got tired of seeing a bunch of node servers eating my laptop memory. 

I like vscode, but I feel it has slowly transformed from an editor to an IDE.

**Comment by JensYvanDeCraecker** [comment]
Just use lando.exe in the shell - or - create a custom file in the bin folder of your Windows installation with the following contents: 

`#!/bin/sh
lando.exe "$@"`

Now you can just use for example 'lando start' from the shell.

**Comment by GoonerW** [comment]
Never thought of that.  Interesting.

**Comment by JensYvanDeCraecker** [comment]
Had to google it myself :)

**Comment by GoonerW** [comment]
Google only led me here though I'm running into issues (haven't been able to successfully start anything yet.

**Comment by JensYvanDeCraecker** [comment]
Btw using windows lando in wsl only works with projects located in your windows filesystem because of the hidden wsl$ network share creates an issue with the variable substitution of docker-compose.

**Comment by JensYvanDeCraecker** [comment]
But I guess these are some simple issues to solve..

**Comment by GoonerW** [comment]
Figures.  You get better performance if the files are in the linux filesystem anyway

**Comment by JensYvanDeCraecker** [comment]
Already noticed that

**Comment by dustinleblanc** [comment]
Yeah I just 100% leave windows behind. My terminal just opens up a shell inside the WSL2 Ubuntu, my VSCODE just goes straight to remote inside WSL, for all intents and purposes, I've just replicated my Linux dev environment and all the non-dev stuff (browsers, media editing programs, games, my code editor, etc) run in Windows.

The real winner here is my wallet. I managed to set up a pretty dope dev machine on a screaming fast laptop that cost under $1500. 8 Core Ryzen 4 processor, 6gb Nvidia RTX graphics, 1TB SSD storage, all day battery life, all for about the price of a very low spec MacBook Pro. The journey to get here was perilous, but it finally feels stable and performant

**Comment by ptmkenny** [comment]
After upgrading to 3.0.6, the proxy URLs were working inside WSL, but not from Windows (before, they were working for both).  So after trying various things, I wiped the docker install inside WSL and reinstalled `3.0.5` and also tried `3.0.6`, but I can't figure out any way to access the proxies in Windows again.  Any ideas?

**Comment by mrweiner** [comment]
@ptmkenny I'm still on 3.0.5 but fwiw I have this issue every so often in a while. Usually I try the following in order and one of em works eventually. 

1. Always start my project with lando rebuild instead of lando start. Seems to be some correlation there (and also avoids issues with xdebug not watching for incoming connections).
2. Failing that, `lando rebuild -y`
3. `sudo service docker restart` then `lando rebuild -y`
4. in powershell `wsl --shutdown`, then start up WSL/docker/lando again
5. restart machine and start from 1

**Comment by dchaffin** [comment]
@ptmkenny - Did you get your proxy URLs working in Windows yet? I can get one of them to work if I append the port (i.e. https://mysite.lndo.site:32790), but my other URLs aren't working and the port changes every time Lando starts, so not needing that would be a huge help. Thanks!

**Comment by GoonerW** [comment]
Not that I don't believe you're experiencing the issues you're describing but I've had none of those.  https://mysite.lndo.site has worked flawlessly for me and so has lando start, no need for the rebuild each time or restarting Docker.

Something must be different in our setups.

**Comment by mrweiner** [comment]
@GoonerW well it's hard to say unless you tell us what your setup is ;)

**Comment by GoonerW** [comment]
Lando 3.0.5 and 3.0.6 (installed via deb purposely ignoring the docker-ce dependency as describe earlier in this thread)
Docker Desktop for Windows 2.3.0.3 (whichever version each of the above Lando's come with).  (Docker not installed in WSL2)
WSL2
Files for Drupal in the WSL2 container itself and not in the Windows file system.

Running any commands in WSL2 without issue.  lando stop/start/rebuild/ssh/db-import/db-export/etc.
All the Proxy URLs are available from within Windows.

**Comment by mrweiner** [comment]
Right so both ptmkenny and I are running everything directly on WSL2. I'm running lando/docker/phpstorm inside of WSL2 via xfce -- not docker desktop/vscode tunneling on windows -- so it's definitely a different setup. In my case I'd imagine it's probably an issue regarding Ubuntu 20.04 and docker. All of the lando commands work correctly, there's just a problem with the proxies sometimes.

**Comment by GoonerW** [comment]
Glad that there’s a difference that can be pointed to.

________________________________

**Comment by dchaffin** [comment]
So, here is my .lando.yml file. Any clues to here as to why these proxy URLs aren't working?

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  site: mysite
  id: ########-####-####-####-############
proxy:
  edge:
    - mysite.lndo.site
    - mysite2.lndo.site
    - mysite3.lndo.site
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
```

As a reminder, mysite.lndo.site:{port} does work, but it changes every time and that's not fun. Though, if there's a way to specify the port to always be some number, I could handle that as well.

**Comment by dustinleblanc** [comment]
If there are random ports getting appended, you probably have something else running on port 80/443

**Comment by dchaffin** [comment]
@dustinleblanc - Indeed. I just uninstalled Lando/Docker from the Windows side of things and disabled IIS automatic startup and now my domains are largely working. I'm using Drupal's domain access and it's not using the right theme for the right domain at the moment, but I think that's another issue not really related to this. 

Thanks!

**Comment by GoonerW** [comment]
I don’t even have IIS installed.

________________________________

**Comment by TheThor** [comment]
Hi,

I have installed Lando on WSL2 and using PHPStorm from Windows. How can I connect PHPStorm to the Xdebug inside the docker container on that WSL2 instance? I tried pretty much everything except installing PHPStorm inside Ubunto.

**Comment by maxdev** [comment]
I have next setup:

1. Windows 10 Pro
2. WSL2
3. Docker for Linux inside WSL2
4. Lando inside WSL2
5. PHPStorm installed on Windows

Everything works pretty good except Xdebug. All the time I have issues with it. And I don't like the idea to run PHPStorm from WSL2.

So this is my setup, which just works, but it requires to rebuild lando project after each Windows restart to update LANDO_HOST_IP with correct Windows IP. Unfortunately I didn't find yet better solution.

1. Added this line to ~/.bashrc inside WSL2:
```
# Set correct Host IP
export HOST_IP=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')
```

2. Use this config in .lando.yml:
```
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: ${HOST_IP}
        XDEBUG_CONFIG: client_host=${HOST_IP}
```

 In ideal world it would be nice to have something like `host.windows.internal` and use it in .lando.yml instead of all these magic.

**Comment by GuyPaddock** [comment]
In the mean time, an option that's working for me is to use WSL2-based Docker with Lando installed inside WSL, and then using a fake package I created through equivs to stand-in for `docker-ce`.

https://github.com/GuyPaddock/wsl2-lando-docker-ce-equiv/releases/tag/1.0

**Comment by RobinHoutevelts** [comment]
Has anyone found a better way to run Lando in WSL by now?

**Comment by ptmkenny** [comment]
@RobinHoutevelts Lando works reasonably well in WSL2.  You can install it just as you would regularly on linux.

The only problem I have is sometimes the proxy URLs don't work upon startup, but this can usually be fixed by killing WSL (`wsl --shutdown` in powershell) and, if that doesn't work, rebuilding the image in lando (`lando rebuild`).

The comments above are issues with running the IDE in Windows and lando in WSL; if you run your IDE in WSLg (with Windows 11), then you won't have that problem.  PHPStorm has some glitches but these can be solved by killing WSL and starting it up again.

**Comment by onetrev** [comment]
I've been doing the Lando in WSL2 thing for half a year and agree with @RobinHoutevelts that it works pretty well. I also have the same occasional proxy URL issues and sometimes only seem to be fixed with a total system reboot. :(

However, I noticed a few weeks ago a [Prelease of Lando](https://github.com/lando/lando/releases/tag/v3.8.0) that has this in the changelog --> "Switched to use wsl2 backend by default instead of hyper-v1". 

So I wonder if now using Docker Desktop in Windows with Lando will be the recommended way to go when this becomes the public release?

**Comment by GoonerW** [comment]
I would doubt it, unless it solves the volume mount performance problems associated with Docker Desktop.

**Comment by GoonerW** [comment]
Further info regarding bind mounts.
https://docs.docker.com/desktop/windows/wsl/#best-practices

> To get the best out of the file system performance when bind-mounting files, we recommend storing source code and other data that is bind-mounted into Linux containers (i.e., with docker run -v <host-path>:<container-path>) in the Linux file system, rather than the Windows file system

So you'll still need to run lando within a linux container (via WSL2) rather than on the Windows host.

**Comment by onetrev** [comment]
Indeed, definitely need to have your source code in your WSL2 file system for far superior performance. Maybe I assumed incorrectly with v4 that's what you'd do. 

You can have Windows Docker installed and have your files stored in WSL2 (which is also what [MS recommends](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers)). I guess we'll see for sure when Lando v4 is released, I probably shouldn't have speculated on a prelease. :)

**Comment by GoonerW** [comment]
We avoid Docker Desktop entirely and run Docker in WSL2 directly (Much easier now with Systemd support).  We do so to avoid the licensing costs as we just need the docker daemon and not the extra functionality Docker Desktop provides.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dkmartin** [comment]
I have been running lando in wsl2 directly for some time now and it has been great! However .... I updated WSL2 through Windows store over the weekend, now none of my lando apps are working correctly. lando start gets the container running and I can load the site in my browser, then after a few minutes I get the "This site can't be reached" error. Then I have to do lando restart in order for it to work again, though after a few minutes it goes down again.

I've tried destroying and recreating the apps and the issue persists. Also the localhost urls never seem to work anymore, only the *.lndo.site url.

Any ideas what might be causing this? I was using lando v3.6.4 with ubuntu and wsl2 kept up to date and everything worked perfectly right up until the last wsl update.

**Comment by onetrev** [comment]
You were right @GoonerW. :) I should have stuck with Lando within WSL2 as I had been doing. Now that I tried installing Lando in Windows I understand what you were saying here:

> So you'll still need to run lando within a linux container (via WSL2) rather than on the Windows host.

In other words, because you should have your Docker files in Linux and accessed **from** Linux directly (not via `/mnt/c/...`), then Lando has to then actually be installed in your Linux instance.  

Long story short there's really no reason to use the Windows install of Lando. I wish the Lando docs pointed to the [WSL2 page](https://docs.lando.dev/guides/setup-lando-on-windows-with-wsl-2.html) because I'm going to guess most people want to do that (or would want to if they understood the drawbacks of the Windows install of Lando).

**Comment by GoonerW** [comment]
Correct. If you’re using WSL2 for the performance benefits it provides with native docker (install Docker directly and use Systemd to manage it), there is zero benefit to using the Windows install of Lando, or Docker Desktop itself.

If you’re not using WSL2 at all, then the argument’s moot.

**Comment by AaronFeledy** [comment]
Docker Desktop's WSL2 integration has been supported for some time now and it is recommended to be used with Lando. Additionally, Docker Engine is supported in WSL2, but Docker Desktop on Windows with WSL2 integration enabled is the recommended approach. Docs currently indicate that running Lando in WSL2 and keeping your code in the WSL2 filesystem is the most performant configuration on Windows.
