### ISSUE TITLE
lando restart: Refine the messaging.

### ISSUE THREAD

**Issue by cklosowski** [lando/lando#1726]
As a user when I run `lando restart` I'm met with a very quippy and somewhat degrading message of: `Stopping your app... just so we can start it up again ¯\_(ツ)_/¯`

I get that many of the messages for the actions are meant to be funny, but I feel like this one actually is unnecessary and could be phrased in a way that doesn't make me feel like I'm failing when restarting the app is _exactly_ what needs to happen to fix a networking issue. I travel often and bounce on and off a VPN, and sometimes I just need to run `lando restart` to get my docker machines to update their networking.

I get this is a minor issue, but just trying to improve the usability and friendly nature a bit.

**Comment by marcaddeo** [comment]
Personally I'd like to see all of this "quippy" remarks removed from Lando, but I doubt it'll happen.

**Comment by mikemilano** [comment]
Originally I didn't care for his shrug, but the little guy grew on me. 

There's something about seeing my console throw its hands up, calling me out because it has no idea I have legitimate reasons to *stop*... `just so we can start it up again`. 😄  It makes me chuckle during a low in my day, and doubles as a rubber 🦆 if I feel like explaining why I'm restarting.

Never thought I'd defend the little dude, but I admire his persistence. I mean every time I restart my app, he's there cracking jokes. Quippy? maybe (that might be a good name!) ... Degrading? no. I suspect he knows there are legit reasons to restart apps and makes that same joke over and over at his own expense.

Quippy will be missed, if removed. 😢
