### ISSUE TITLE
Lando init on existing Pantheon site causing an error

### ISSUE THREAD

**Issue by bcavenagh** [lando/lando#1763]
I can't figure out this issue I'm having when trying to lando init a site from Pantheon. When I run lando init --source pantheon --pantheon-auth "{machinetoken}" I get this and no where online can solve this. I've gone to Pantheon support and they directed me to Lando support, I went on the Lando Slack and they told me it was a Pantheon problem.. I'm at a loss. 
![Capture](https://user-images.githubusercontent.com/7342563/63902739-72540400-c9d0-11e9-9584-f74b131a0f83.PNG)

**Comment by mikemilano** [comment]
@bcavenagh I tested a `lando init` with a `pantheon` source and the project (a simple drupal site) was built successfully.

Some basics to try:
- Make sure you're running the latest version of Lando
- Restart Docker if you haven't already
- Try running `lando rebuild` if the `.lando.yml` file has already been created

If none of that works, I suspect it's something in the config or changes to the underlying images if it used to work.

Troubleshooting services:
- `lando logs` might reveal issues with a container spinning up. Target each service by name: `lando logs -s database`
- `docker ps` will show what containers/services actually started. Sometimes you can tell which one is the problem by what hasn't started

Other factors may reveal clues like:
- Has this project ever worked? What has changed since it did?
- Does it work on other systems? or is it just a problem with this one system. (Points to the local Docker/Lando install)

Sorry I don't have specifics. I just wanted to let you know we have looked at this but haven't been able to reproduce it and can't tell you specifically what is wrong at this point.
