### ISSUE TITLE
Auto lando start

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1766]
It would be nice if there was logic to `lando start` the entire app if any lando command is executed before the containers are running.  For instance, `lando drush status` starts only the appserver to provide feedback and that is great.  However, `lando drush cim -y` will not start the database container and does not fail gracefully with a helpful message such as "Hey dummy, start your app before you execute this command."

**Comment by pirog** [comment]
@uberhacker im not sure this is possible without significant slowdown to all tooling commands. it _might_ be possible to specify explicit dependencies eg the appserver requires the database be started first using docker compose-ism.

**Comment by uberhacker** [comment]
Hey @pirog: Not sure what you mean about _significant_ slowdown.  All you would need to do is check if the app is running and then `lando start`, if not prior to executing the command.  Running a command when then app hasn't started yet yields a kludgy error after a fairly significant wait anyway.  Then I would need to scratch my head a bit and then do a `lando start` anyway.  _That_ would be significantly longer than an auto start.

**Comment by pirog** [comment]
Checking that the app is running is not a trivial operation. We definitely dont want to enforce a check like that before all tooling commands. 

>  Running a command when then app hasn't started yet yields a kludgy error after a fairly significant wait anyway. 

This is certainly not true for most things and is going to be dependent on how the underlying thing (eg drush or php or yarn) works and reports errors. regardless its not something lando should try to interfere with because its going to be very different from command to command and it definitely doesnt make sense to change the handoff process of the entire tooling lifecycle to handle one class of commands for one kind of tool. 

If anything is to be done here its going to have to be using docker composes `depends_on` convention

**Comment by uberhacker** [comment]
Is `depends_on` something that can be added to the recipes?  I guess I don't understand how a simple status check is non-trivial.

**Comment by pirog** [comment]
Should be pretty easy to add them to the recipes AFAIK. Definitely better to have docker do the work instead of more or less writing the same-ish and probably-not-as-good logic into lando.

and yes, i guess you dont! ;)

**Comment by uberhacker** [comment]
@stalebot did it again!

**Comment by uberhacker** [comment]
Bonus points if we can get this to work after a browser request to the lando url.

**Comment by uberhacker** [comment]
@stalebot go away!

**Comment by uberhacker** [comment]
Unstale.

**Comment by uberhacker** [comment]
Unstale

**Comment by uberhacker** [comment]
Unstale

**Comment by uberhacker** [comment]
Unstale
