### ISSUE TITLE
Catalina Support

### ISSUE THREAD

**Issue by jserrao** [lando/lando#1770]
This product is pretty rocky on the macOS Catalina preview. Spool up a few sites and you'll probably see what I mean.

**Comment by pirog** [comment]
We dont provide support for beta versions of operating systems so thats not surprising and is something we dont plan on changing. 

also worth pointing out that lando is not a product.

**Comment by jserrao** [comment]
I know this is a macOS beta and am not asking for beta support. Catalina should be official in 3-4 weeks if the rumor mill is right, just thought you might want to get ahead of it a bit. 

If you'd like help identifying / fixing issues I've seen, let me know. Otherwise, best of luck.

**Comment by pirog** [comment]
Got it. I'd recommend being clearer and more concrete when you report issues, feedback, etc in the future. 

> This product is pretty rocky on the macOS Catalina preview. Spool up a few sites and you'll probably see what I mean. 

This is not a lot for us to go on and we generally are going to move onto other issues in these situations.

Your follow up comment is helpful though. My guess is that a lot of the issues you saw are caused by incompatibilities between Docker Desktop and Catalina, likely captured in this thread https://github.com/docker/for-mac/issues/3698, eg its likely the only thing Lando needs to do is roll a new release with the new docker when Catalina is out.

If you've found issues that you think are caused by the Lando layer of things id encourage you to open tickets for each issue with steps to replicate them. That would be the most helpful thing to us.

**Comment by JohnPett** [comment]
I am unable to install this on the latest MacOS Catalina.

Error attached:

<img width="488" alt="Screenshot 2019-10-11 at 13 10 22" src="https://user-images.githubusercontent.com/3016847/66679667-a4f74a80-ec66-11e9-852b-a449207d3b11.png">

**Comment by pirog** [comment]
We are working with Apple to make sure Lando is fully Notarized. In the meantime anyone who has this problem can use the following workaround
https://www.reddit.com/r/MacOS/comments/cgj1qs/cant_be_opened_because_apple_cannot_check_it_for/

Beyond that Lando should be 100% Catalina compatible

**Comment by jserrao** [comment]
I'm probably going to move over to the Catalina official release channel this weekend. I'll reinstall docker, macOS and lando, rebuild my apps and report back if anything Lando specific comes back.
