### ISSUE TITLE
Add minimum Lando version requirement as Lando YAML property

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1780]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1. [x] Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2. [x] Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

**Please explain your request and its importance in the form of a user story.**

*As a Lando user who works on many projects depending on Lando, I want the option to abort a Lando start if the developers Lando version is incompatible with recent Lando file changes*

**Please provide some detail on how lando can help solve this problem**

*Example:*

```bash
$ lando version
4.0.0
```

```yaml
# .lando.yml
name: my-project
min-version: 4.0.1 # define minimum supported Lando version
```

```bash
$ lando start
Sorry, this project requires Lando 4.0.1 - you're running 4.0.0
$ lando rebuild
Sorry, this project requires Lando 4.0.1 - you're running 4.0.0
```

**Is your feature request related to a problem? Please describe.**
Though Lando has improved backward compatibility with the more stable releases lately, this will help prevent failed Lando project builds or otherwise unexpected behavior.

**Describe the solution you'd like**
Adding a minimum Lando version property to `.lando.yml`.

**Describe alternatives you've considered**
I've considered hooking into the Lando events via the `.lando.yml` to attempt to output a message to the developer or otherwise abort the `lando` action.

**Comment by pirog** [comment]
@tylerssn if and/or when there is a time and place where lando has more than one stable API schemes i would probably support this

for now we definitely do not want to do something like this. once there is a stable 3.0.0 release there will no breaking api changes until a 4.0.0 and its also highly unlikely there will be any other breaking api changes on the way to that 3.0.0 stable. so we definitely dont want to add code for something that encourages people to remain on beta or rc versions of lando.

**Comment by gagathos** [comment]
@pirog I am reading this issue years later and it seems like there was a misunderstanding. I think this feature still makes sense for developers wanting to implement **new** lando features in their repos and force the other users to update lando.

Here is a usecase:

- I want to upgrade my landofile to use php 8.1
- Older version of lando only supports php 8.0

Now, as the dev making this change I might understand that I need to update lando.  But if another user is pulling the latest changes from the repo, there is nothing telling them they need to update lando to be able to support the features in the lando.yml.

This also would have been the case in the past when certain config format changes would have broken things-- that is, updating to the new config meant that older versions of lando wouldn't work anymore. SO I believe this change does the opposite of what you say, it encourages people to upgrade instead of staying on older versions.  It gives me as a developer a way to force people to upgrade instead of having them complain the local environment no longer builds for them.
