### ISSUE TITLE
Lando caches static assets

### ISSUE THREAD

**Issue by ghost** [lando/lando#1826]
I am working on the Drupal theme and I noticed that Lando caches CSS even when I try to access file immediately, e.g. `http://demo-d8.lndo.site/themes/custom/fluffiness/css/style.css` or with a paramaeter `http://demo-d8.lndo.site/themes/custom/fluffiness/css/style.css?321`.

Flushing Drupal cache does not help.

The only solution is to restart Lando. Any ideas on how to fix it?

**Comment by dutton242** [comment]
Following. I'm seeing this too and it's quite annoying. I have to restart Lando and/or restart Docker for the files to show up correctly in the browser. This is also affecting other assets like Pattern Lab files and such.

**Comment by nelsonamaya82** [comment]
Same here.

**Comment by eelkeblok** [comment]
Are you making use of the excludes feature, by any chance (i.e. opting out of local file system vs. container fs synching at the benefit of extra speed)? Not that that would completely explain all reported behaviour, but it could be a factor.

**Comment by dealancer** [comment]
@eelkeblok I am using default Lando installation, not sure how to check if these extra features enabled.

**Comment by alphex** [comment]
This just started happening to me also.

Is it related to OSX Catalina ? (10.15.2 (19C57))

I just got a new MBP 19 and It's very new and this is the first time I'm really trying to use lando on it.

About to boot up my older system and see if that does it also

**Comment by alphex** [comment]
Confirmed.

I just booted up my NOT Catalina (10.14.6) laptop, and this is not happening.
To repeat, it IS happening on my new laptop running 10.15.2.

To repeat.

* lando start
* lando pull DB and FILES from pantheon
* `gulp` in the theme directory
* make change to SCSS file
* gulp succeeds in generating CSS file.

...  On the older MBP,   you see the changes in your drupal site (and a index.html file I was using to super dummy test this)

... on the new MBP, you do not see the change.

As stated in original post.   Restarting LANDO fixes it.  (but, obviously thats not good :))

Thank you.

**Comment by dutton242** [comment]
Not sure if this is relevant or not, but I recently switched to using Pantheon's LocalDev app (which uses Lando under the hood), and it is still doing this. I'm on Catalina (10.15.2) and no easy way to test on an older version of MacOS. In fact, it seems worse now in that I have to restart Docker about every 10-15 minutes or so to have assets be able to be seen.

**Comment by gcalex5** [comment]
This is also occurring for me pretty consistently with PHP file changes. Stock Pantheon recipe using WordPress with Xdebug enabled. Have to do a combo of either restarting docker or lando to get it using updated code most of the time.

- PHP 7.3
- Lando v3.0.0-rc.23

**Comment by alphex** [comment]
Follow up to this...

I _think_ this is related.

OSX 10.15.2 (19C57)
Docker 2.1.0.5 (40693)
Lando v3.0.0-rc.23

I'm just setting up a new Drupal 8.8.2 site, and out of the box, config sync goes to somewhere in `/sites/default/files`.

I forget to change that in settings.php, so when I ran `lando drush cex -y` it gave me this

```
The active configuration is identical to the configuration in the export directory (sites/default/files/config_VuLO4v-j7tVLYCukmTF3pwkGBD19qrtQVmW7yqzO4vf4wRaqN-XhupJZm_Ze4i1kgfRZLWnmoA/sync).
sites/default/files/config_foo/sync
```

(where `foo` is that long string thats supposed to be obfuscation)

"oops" i said to my self.

I go in to my settings.php and change the things...

`$settings['config_sync_directory'] = '../config';`

I go back to my terminal, and `lando drush cex -y`

... and it tells me the same thing (active config is identical, in your sites/default/files....)

I RM RF the config directory in sites/default/files

```
$ ls -la 
total 176
drwxrwxr-x@  9 duran  staff    288 Feb  5 08:18 .
drwxr-xr-x@  9 duran  staff    288 Feb  5 08:00 ..
-rwxrwxr-x@  1 duran  staff    519 Jan 10 13:34 default.services.pantheon.preproduction.yml
-rwxrwxr-x@  1 duran  staff   6762 Feb  5 07:31 default.services.yml
-rwxrwxr-x@  1 duran  staff  30150 Feb  5 07:31 default.settings.php
drwxrwxr-x  14 duran  staff    448 Feb  5 08:26 files
-rw-r--r--   1 duran  staff    430 Feb  5 08:19 settings.local.php
-rwxrwxr-x@  1 duran  staff   7017 Jan 10 13:34 settings.pantheon.php
-rwxrwxr-x   1 duran  staff  30782 Feb  5 08:25 settings.php

$ pwd
/path/to/my/project/www/web/sites/default
```

So I run the `lando drush cex -y` again... and it gives me the same message.

I then `lando ssh`, and then `ls -la web/sites/default/files` ... and low and behold.

```
$ ls -la web/sites/default/files/
total 12
drwxrwxr-x  15 www-data dialout  480 Feb  5 03:01 .
dr-xr-xr-x   6 www-data dialout  192 Feb  5 02:22 ..
-rw-r--r--   1 www-data dialout 6148 Feb  5 02:54 .DS_Store
-r--r--r--   1 www-data dialout  543 Feb  5 02:23 .htaccess
drwxr-xr-x 157 www-data dialout 5024 Feb  5 01:33 2018-09
drwxr-xr-x 260 www-data dialout 8320 Feb  5 01:33 2018-10
drwxr-xr-x  42 www-data dialout 1344 Feb  5 01:33 2018-11
drwxrwxr-x   3 www-data dialout   96 Feb  5 12:21 2020-02
drwxrwxr-x   3 www-data dialout   96 Feb  5 02:23 config_VuLO4v-j7tVLYCukmTF3pwkGBD19qrtQVmW7yqzO4vf4wRaqN-XhupJZm_Ze4i1kgfRZLWnmoA
drwxrwxr-x 114 www-data dialout 3648 Feb  5 12:22 css
drwxrwxr-x   3 www-data dialout   96 Feb  5 02:27 google_tag
drwxrwxr-x 102 www-data dialout 3264 Feb  5 12:22 js
drwxr-xr-x   3 www-data dialout   96 Feb  5 01:33 media-icons
drwxrwxrwx   2 www-data dialout   64 Feb  5 13:20 php
drwxrwxr-x   9 www-data dialout  288 Feb  5 12:21 styles
```

After doing a `lando restart`

I `lando ssh`
and
`$ ls -la web/sites/default/files/`
and I still see the `config_VuLO4v-j7tVLYCukmTF3pwkGBD19qrtQVmW7yqzO4vf4wRaqN-XhupJZm_Ze4i1kgfRZLWnmoA` directory

Which is _NOT_ present in my actual file structure on my system.   (docker is caching this path structure?)

Running `lando drush cex` still generates the files in that `config_VuLO4v-j7tVLYCukmTF3pwkGBD19qrtQVmW7yqzO4vf4wRaqN-XhupJZm_Ze4i1kgfRZLWnmoA` directory.

I am now doing a `lando rebuild`

After a `lando rebuild` that incorrect config directory in files is now gone.

Running `lando drush cex` creates the correct config directory and places files there as expected.

Please let me know if you need more info.

**Comment by stevie-c91** [comment]
Same thing is happening here. Static assets are not always refreshing unless a restart is performed.

Running the latest version of Lando, Docker, and on OSX Mojave.

Thanks.

**Comment by dutton242** [comment]
Does anyone think this could be Docker? I could be totally wrong here (I've got only a small bit of evidence to back that up) - if I restart Docker, it seems to fix the issue as well. But, I've also experienced that if I restart Lando, that works too.

**Comment by alphex** [comment]
Also, @dutton242  -- I think all of us are on the latest OSX...  I smell something between file system changes to Catalina and Docker.   Since, restarting DOCKER or LANDO,   is of course re-initializing the file system mount.

**Comment by dutton242** [comment]
Agreed - there have been many reports that Catalina messes with tons of other apps too. Apple increased the security checks, so perhaps Docker needs to be more aware of that...? Outside of my sphere of knowledge!

**Comment by flyke** [comment]
I would like to point out that I am a windows user, and I experience this problem too.
I did update my Docker Desktop this morning and it is today that I noticed this problem of Lando caching my drupal theme css file while the actual file is updated (via gulp after scss changes).
Not 100% sure if the Docker Desktop update is responsible but I do seem to remember not having the same problem before that.

**Comment by brandenMB** [comment]
I have this issue on Drupal and WP installations. It's caching my PHP files too.

**Comment by pgraber** [comment]
Same here.  On Windows 10.   The environment was working previously (no caching);  but after a Docker Desktop update, it's exhibiting same issue as here.

**Comment by willtate** [comment]
+1 Seeing caching of php/js/css files until lando/docker restart.

**Comment by SquareBeard** [comment]
For me it's not just static assets. It started doing this after upgrading from 3.0.0-aft.1 to 3.0.0-aft.2

**Comment by pirog** [comment]
Does anyone here have concrete steps to replicate this?

**Comment by dutton242** [comment]
I'll see if I can replicate this, but, I will say after updating Lando to the latest (including Docker to the one recommended - 2.2) and also (semi-related Pantheon LocalDev to the latest), I'm not seeing this very much, if at all. If I find it happening again, I'll post here.

**Comment by ptgraber** [comment]
I updated as well on WIN10P and issue resolved.  Seems to relate to older Lando versions in use with newer Docker Desktop.

**Comment by aohlrogge** [comment]
I am still having this issue using Windows 10 and v3.0.0-rrc.3

**Comment by dutton242** [comment]
Using Pantheon LocalDev yesterday (latest version), I pulled down a Drupal 7 site to work on and it was really bad yesterday - it seemed that if I left it alone for about 10 minutes after a page refresh it would update, but that's sort of silly for local development. I had to restart Docker several times to keep working. It does appear this is more of a Docker caching issue than it is Lando or LocalDev.

**Comment by flyke** [comment]
It is even more bad since upgrading to Lando v3.0.0-rrc.3.
There must be some way to clear lando or docker cache, right ?
If anybody knows it, please tell me.

**Comment by anakinjay** [comment]
I'm having this exact issue on v3.0.0-rrc.3.   I have to quick docker and restart it to get anything to work, and then it only works for about 10 minutes, then I have to restart docker again.  It's pretty brutal.

Lando v3.0.0-rrc.3
Docker 2.2.0.5

**Comment by dkjensen** [comment]
I'm currently having the same issue

**Comment by anakinjay** [comment]
Can we get the title of this changed?  Caching PHP files is game breaking compared to caching static assets.

**Comment by pirog** [comment]
I think the better thing would be to create a new issue. I have not
personally observed this behavior so steps to replicate would be helpful.

**Comment by dutton242** [comment]
Yeah, it's really tricky to recreate because it seems so random. Some days it's fine and I can code for hours without experiencing it. Other days it seems it happens every 15-20 minutes. I'll try and see if I can find something that triggers it, but it's tough. I use gulp, not sure if anyone else is using that experiencing the same?

**Comment by pirog** [comment]
It’s also worth pointing out that Lando does not cache so this is likely an
issue with docker. We can still have an issue to track it on the lando side
but pointing people to an issue on the docker queue may be more productive

**Comment by dutton242** [comment]
Agreed, I think it is Docker, rather than Lando - since restarting Docker seems to fix.

**Comment by flyke** [comment]
Has anyone from the Lando team looked into this ?
Is there a ticket about this static assets caching on any official docker page somewhere ?
Does anyone have a working workaround ?

I am a Drupal web developer for a living. The older lando (/docker) versions really improved our workflows so much that we are using Lando for every project we have.
BUT upgrading to Lando Lando v3.0.0-rrc.3 suddenly makes my work a living hell.
It is now 10:30, I started working 2 and a half hours ago and I already needed to restart docker and then lando start again for about 30-40 times just to get some theming of a form just right.

I am open to any suggestion. For now it seems I really must look into downgrading lando or docker to a previous version. Does anyone use nginx instead of apache with a custom config for it to disable caching on a nginx level (for example https://gist.github.com/mflorence99/989ae26173b1746f7bbf) ? would that help ? Would there be a comparable method for adding an apache config file in the lando file where you could have some sort of setting of disabling all caching ?

I am really looking forward to a constructing response as web development is my full time job and the php/css caching issue is making it a hell right now.

**Comment by pirog** [comment]
@flyke no one on the Lando team has observed or experienced this issue. We have also not been given any concrete steps to replicate it which does not give us a lot to "look into it". 

As indicated above Lando does not do caching so our _best guess_  so far based on when the comments above starting being about a different issue than the OP is this is an issue with Docker Desktop. Possibly specific to Windows. If you are interested in resolving this issue for yourself and others here are a few of many helpful things you could do next:

1. Give us steps to replicate the issue: What OS are you on? What version of Lando? What does your Landofile look like? What steps would someone need to take to experience what you experienced? Does it happen every time? Does it seem random? Does it happen on all you projects or just one? etc
2. Downgrade Docker to the last 2.1.x version but **keep the same Lando version**. If this resolves your issue then we have a pretty good idea this is Docker related and can offer it as a workaround until Docker fixes things on their end.
3. Upgrade to the latest edge Lando version and see if that resolves your issue. Then we know this might actually be a problem with Lando.

We also encourage anyone else on this thread to try the above as well.

**Comment by alphex** [comment]
If this helps at all, my anecdote.

OSX 10.15.4 (19E287)
Docker 2.1.0.5 (40693)
Lando v3.0.0-rc.23

The _VAST_ majority of my projects are using the Pantheon recipe.
Since I bought this laptop (MacBook Pro (16-inch, 2019)) I have NOT had this problem.
But I had it with previous versions of Lando and Docker on an older laptop. (2015 15 inch MBP)

I am unable to update to the latest docker and lando until next week at the earliest, as I'm about to launch two different projects, and I don't want to overhaul my tooling until they're live.

I suspect it has to do with OSX + Docker, since that was the biggest thing that changed for me in the last few months (and the new hardware).

As soon as I update Docker and Lando, I'll comment more.

**Comment by pirog** [comment]
@anakinjay i appreciate that you noted that this was your opinion as these are certainly not the only common denominators. 

the application you are running (and its code, specifically) immediately comes to mind as another very very very important common denominator. 

again, we are happy to look into this but we need someone experiencing this to provide steps to replicate as suggested in https://github.com/lando/lando/issues/1826#issuecomment-621159311

**Comment by JorisVanEijden** [comment]
I have also occasionally run into this issue on windows 10.
There are no consistent reproduction steps. Something somewhere for some reason sometimes loses track of filesystem synchronization.

Changes to files made on the host machine are not reflected in the files inside the container and vice-versa.
Either a docker or a lando restart restores the normal functionality.

I'm guessing this is one of the drawbacks of using [delegated](https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated) mounts.

**Comment by smutlord** [comment]
New Lando release includes Docker Desktop `2.3.02` which _claims_ to have improvements for these things, specifically on Windows. 

If you upgrade and try it out def let us know if it seems to improve the situation at all

**Comment by RistoNiinemets** [comment]
I'm on Windows 10, been with Lando from quite the beginning and the issue started a few versions back. Tried updating, reinstalling etc - currently on Lando 3.0.2 and Docker Desktop 2.3.0.2. Occours with WordPress and Laravel recipes, both static and PHP files.

Also could not give steps to replicate, as this seems to be random.

**Comment by nelsonamaya82** [comment]
It also happens to me randomly, but now it's very frequent. I'm on a MacOS Catalina, Pantheon recipe. When I edit PHP files, sometimes it works, sometimes it doesn't, like if the PHP had no changes. The only solution is to restart Lando. And also most of the times I get Lando URLs in red, so none of them work and I have to restart it multiple times, or rebuild.

**Comment by flyke** [comment]
Apart from my solution in [this comment](https://github.com/lando/lando/issues/1826#issuecomment-621067052) above, I found another great solution. Since both Docker as Lando refuse to or are unable to add a resync button or command, I found out it is amzingly easy: as soon as you change anything on any file from inside the container, then all your files are synced again. So what I do now is to add this in the tooling section of my .lando.yml file:
```
tooling:
  refresh:
    service: appserver
    description: Refresh files in container when they are out of sync with actual files
    cmd:
    - touch resync.txt
    - rm resync.txt
    - echo "Files should be resynced now!"
```
Immediatly after you added this in your lando file, you can enter the `lando refresh` command in your terminal. No need to restart or rebuild lando. Yes this simply creates and then deletes a file and nothing else. But it executes this inside the appserver container, which then thinks 'Hey something happened here, let me refresh my files' and boom, finally a quick and easy solution for this long ongoing problem.

**Comment by jupiter23** [comment]
I also just noticed the same issue after updating my MacBook Pro (Retina, 15-inch, Mid 2015) to OSX 10.15.5.
lando v3.0.6
docker 2.3.0.3

I am working on a new D8 project and was running some yarn build scripts. The files served by lando were not getting updated. I did not have any problems with PHP files.

The tooling refresh technique above (the updated one) did not work for me.

I tried to reproduce the issue with a quick lando init loading just a js file from index.php, but the problem was not reproduced - changes in the js file were reflected on refresh. So unfortunately I am not able to provide a realistic means of reproducing my issue. I am integrating some vuejs components into a Drupal 8 site, so the steps are pretty involved.

Thankfully I did find a solution which is saving my project and allows me to keep using lando. I found that by building the tooling into lando as per https://docs.lando.dev/guides/frontend.html#adding-grunt-gulp-etc and running the yarn build script in the container the files were refreshed.

Hope this helps!

**Comment by nelsonamaya82** [comment]
That's right, I thought the refresh technique above was working for me, but it actually didn't. For now the only way that works for me is restarting Lando.

**Comment by certainlyakey** [comment]
Same bug here — PHP files get cached and the app sees the old values instead of updated ones until you do a `lando restart`.

**Comment by gunzenhauser** [comment]
Updating to Docker 2.3.0.4 and Lando 3.0.11 solved this issue for me.

**Comment by zuernBernhard** [comment]
Nope - MacOS 10.15.6 Docker 2.3.0.5 Lando v3.0.13 -> CSS File (which is delivered by Lando not routed through Drupal) is changed in Filesystem of my Mac but Lando still delivers the old one. Its a Drupal 8 Project. All caches disabled (settings.local.php, development.services.yml, ...)

**Comment by zuernBernhard** [comment]
Even when I ```lando ssh``` into the container and show the file contents with cat I see the old one.

**Comment by pirog** [comment]
Lando is not a web server so it by itself does not “deliver” static assets.

Do you mean nginx? Apache? These are important details.

**Comment by zuernBernhard** [comment]
Sry apache-2 (lando Drupal 8 recipe) - after touching a new txt file from within the app container (Lando ssh) and editing it on the host - the css file got synced - have no clue why ...

**Comment by maccyd10** [comment]
I confirm that using lando ssh and cat ./file shows old file contents
`$ docker --version
Docker version 19.03.12, build 48a66213fe`

`$ lando version
v3.0.14`

Note: bug appears to be a duplicate of https://github.com/lando/lando/issues/1761

**Comment by pirog** [comment]
Just to reiterate/summarize things a bit with an "as best as we can tell" caveat". If you `lando ssh` into the container and...

### **DO NOT** see the changes you expect then...

This is _likely_ a problem with Docker's file sharing mechanism. Usually this is caused by the file sharing daemon crashing or by having a very large amount of files. In either case you are likely going to get better support/results/etc in the Docker issue queues.

### **DO** see the changes, then...

This is _most likely_ an application caching problem _or_ a web server caching problem. The former is probably something you will need to address yourself. The latter _may_ be a problem with how Lando's underlying services eg `nginx` or `apache` are serving files. Note that if your Landofile overrides the default webserver config then it will also be something you need to address.

**Comment by RistoNiinemets** [comment]
Thanks @pirog for the summary.

I just had the issue and checked it, here's a picture of the changed file in editor and in SSH:
https://share.konekt.ee/Nx67eN

So that means, it's _likely_ a problem with Docker.
