### ISSUE TITLE
Should we add a `lando status` command?

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#183]
This is not a bug but rather a feature request.  I was thinking it might be nice if `lando status [name]` did essentially the equivalent of `docker ps -af name=$name_` where `$name` is an optional parameter that defaults to the current site if run in the project directory.  Thoughts?

Another option would be to extend the `lando info` command with additional switch options something like below:
```
-f, --format=[csv | json | table]
-r, --filter=[regex]
-s, --summary (just extract out the most important details and summarize)
```

**Comment by pirog** [comment]
👍  i think these things would be great to add!

**Comment by ccharlton** [comment]
Makes sense. Many other scripts/commands we use in tandem have a `status` health check.

**Comment by AaronFeledy** [comment]
I was pointed to this issue in a chat about adding a way to filter the `lando info` command to only show the urls for each service. I started on a solution specifically for that purpose, but it seems to make more sense to go with a more robust solution such as what's been suggested here. I'd like to get some more discussion going in this issue to determine the best path forward. Here are some of my thoughts:

Adding a `--filter` switch to the `lando info` command could achieve my goal of narrowing the list to only the URLs when I desire. It could also be used to filter to other specific pieces of information which could make it useful for other's purposes. Should this offer some built-in filter options, or does regex keep it relatively trivial for the user?

I like the idea of adding a `--format` switch to `lando info` so that we can output for our particular use case. Currently the output is JSON which is great for consuming this info with other things such as a hypothetical GUI, but may not be ideal for other use cases.

If we have the option to set the output format, I think a table format should be the default since humans are less likely to want to type the extra characters to get the more human-readable output. To the machines, who might prefer the taste of JSON, a handful of extra characters is essentially no additional effort.

I like the idea of a `lando status` command. My initial interest in this issue came from wanting a way to quickly get my URLs from an already running app. Filtering the `lando info` output seems like the easiest way to do this, but it makes for a lot of extra typing to get a quick piece of info that, in my opinion, should be fairly easy for a user to retrieve. A simple `lando status` could give us a repeat of some of that "vital" info that displays when you first start an app, as well as a few health-related bits of info.

Currently, just checking to see if an app is running seems more difficult than it should be. I have something like 20 apps, so `lando list` gives me way more than I want. Running `lando info`, which gives me all the other info about an app, doesn't tell me if it's running. Should it? Again, `lando status` could give us this.

I think this issue could probably be ultimately split up, as I think there is a need for both the added features to the info command as well as the need for a simple status command.

Please reply with any feedback on what I've said here and any additional thoughts you might have about this issue in general. As I mentioned, I'm hoping to settle on a good path forward. Once we have one, I intend to give the developers more than just my thoughts and prayers. I intend to actually get my hands dirty on this one.

**Comment by uberhacker** [comment]
@AaronFeledy: Totally in agreement with all your suggestions.  I like the human-readable by default philosphy.  We could also have the best of both worlds if we provided both `lando info --filter=...` and the equivalent `lando status` command (which is more suitable for human consumption as opposed to switch options to `lando info`).

**Comment by pirog** [comment]
just to chime in with some high level thoughts about this

1. the underlying [`app.info`](https://docs.devwithlando.io/api/api.html#landoappinfo) command should *always* return JSON
2. +1 on the default `lando info` format being some tabular data: that should happen in the CLI task implementation of `app.info` over yonder https://github.com/lando/lando/blob/master/plugins/lando-app/tasks/info.js
3. I think its fine to accept `--filter` as an array of fields and ignore (or warn) if any of the fields are not actually part of the app info object
4. I personally think having both `lando status` and `lando info` is confusing since they seem to provide very similar things. I think a smarter `lando info` command might be the way to go. I know @uberhacker had suggested some sort of "summary" form for `lando info` which *feels* pretty similar to what im hearing re: `lando status`. Could always make a human-readable summary of vital info the default of `lando info` and then provide a simple counter switch to provide increased levels of depth

**Comment by uberhacker** [comment]
My vision for `lando status` was along the lines of a wrapper around `docker ps`, however, if the name is too close to `lando info`, we could change it to something like `lando healthcheck` but the underlying concept is fundamentally different that `lando info`.  What I envisioned for `lando status` was to report whether the database container is running or not, for example.

**Comment by pirog** [comment]
the underlying concept for `lando info` is to provide information about
your app which definitely could include the running status of a given apps
containers so in that way i dont see why some info (eg the status of
individual containers) should be in one command and other info in another.

**Comment by uberhacker** [comment]
Can you currently get the running status of containers with `lando info`?

**Comment by pirog** [comment]
not currently, we *do* already call `docker inspect` during `lando info` so *im guessing* it would be pretty trivial to just map the container running state from `docker info` to some key on each container in `lando info`
