### ISSUE TITLE
db-import and ignore foreign key checks

### ISSUE THREAD

**Issue by daltonrooney** [lando/lando#1850]
The MySQL database in my LAMPy app contains foreign key constraints, which means the db-import command always fails. When wiping out the database, a "force" option would be nice to ignore foreign keys and then do a clean import.

**Comment by GiorgosK** [comment]
For any kind of error that we want to ignore when importing a -force option passed directly to mysql would be nice and greatly appreciated.

**Comment by pirog** [comment]
This seems like a reasonable proposal and also a good issue for first time contributors. In order to make this work i think we'd want to

1. Add a force flag to the lando DB import options - https://github.com/lando/lando/blob/master/plugins/lando-recipes/types/laemp/builder.js#L14
2. Parse and handle that option in the `db-import` script - https://github.com/lando/lando/blob/master/plugins/lando-services/scripts/sql-import.sh#L29
3. Augment the import command with the force flag if selected - https://github.com/lando/lando/blob/master/plugins/lando-services/scripts/sql-import.sh#L80 (note that this might not be supported for postgres)
4. Update the documentation so the new flag is noted as an option and with an example of usage - https://github.com/lando/lando/blob/master/docs/guides/db-import.md
5. Augment the func test/example so that it ignores errors in a dump file - https://github.com/lando/lando/tree/master/examples/sql-import

**Comment by pirog** [comment]
This should be fixed in the next Lando release
