### ISSUE TITLE
Providing latest Docker version support

### ISSUE THREAD

**Issue by blachawk** [lando/lando#1899]
I downloaded and installed the **latest release** of Lando ` lando-v3.0.0-beta.47.exe` During installation, it gave me the impression that it was going to udpate my current Docker installation. I had client version `19.03.5` installed. But it installed with Docket client version `18.03.1-ce`.

### 3 Questions

* Requesting permission to include documentation on what latest stable version of Docker comes with the latest release of Lando.  Is this possible?
* Regardless, how would I know if Docker 19.03.5 is compatiable with Lando-v3.0.0-beta.47.exe?
* Can I upgrade the installed Docker version and still enjoy all the benefits of Lando from it's latest release?

Many thanks on any feedback!

**Comment by Silic0nS0ldier** [comment]
@blachawk Lando 3 has been fairly robust across versions of Docker in my experience. As an example, I've been running Lando with the Docker Edge builds (for WSL2 support) for several months now and the only issues I've encountered have been attributed to bugs within Docker itself (to be expected in an edge build).

If I had to guess, using the bundled version is recommended purely because it has been tested. (well that and it makes support considerably easier by minimizing the number of potential causes). Newer versions should work in most cases, but wouldn't be officially supported.
