### ISSUE TITLE
NET::ERR_CERT_INVALID on Chrome on Linux 

### ISSUE THREAD

**Issue by daliborstojakovic** [lando/lando#1902]
Issue reported [here](https://github.com/lando/lando/issues/1831) on Mac is issue still on linux regardless of the fix in latest release. Tested on Ubuntu 19.10 and on lando rc23. Same issue happens. Tried also to add certificates like documented here: https://docs.lando.dev/config/security.html#trusting-the-ca but regardless site shows as not secure on Chrome.

**Comment by pirog** [comment]
@daliborstojakovic i and several members of our team who use linux + chrome are not able to replicate this.

**Comment by pirog** [comment]
@mikemilano, @labboy0276 suggested that maybe you had run into this at some point?

**Comment by mikemilano** [comment]
@pirog no, I don't have a desktop linux system at this time.

**Comment by daliborstojakovic** [comment]
@pirog Check photo. Tested today. Do you have any suggestions ?
![certificate_invalid_new](https://user-images.githubusercontent.com/4934271/70710081-b7c9e200-1cde-11ea-9ad1-e4845ffdcaa3.png)

**Comment by pirog** [comment]
@daliborstojakovic check photo.

1. This is not the same error as the one you posted eg `NET::ERR_CERT_INVALID` != `NET::ERR_CERT_AUTHORITY_INVALID`
2. This is not the same issue as https://github.com/lando/lando/issues/1831
3. This is the expected behavior and is documented here https://docs.lando.dev/config/security.html#trusting-the-ca, AFAIK users have been able to whitelist the CA using this method
4. Whitelisting our CA is not required and you can bypass the warning directly in chrome in the Advanced tab

If the above doesn't work i'd suggest using google and following any relevant instructions
for example the ones posted here: https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate?page=2&tab=Votes

**Comment by MCDELTAT** [comment]
I was able to replicate this issue, so I'd like to jump in on this and see where I can help.

Linux Mint 19.1 (Ubuntu 18.04), Lando v3.0.0-rc.23, Chrome was installed from a .deb from their official site.

I ran through some simple tests and spun up a Drupal8 site with Lando. I then followed [the instructions](https://docs.lando.dev/config/security.html#trusting-the-ca) for trusting it on my host OS and in Firefox. None worked. They all said it was invalid. Stopped Traefik router, rebooted browsers and my OS, nothing.

Verified I had a valid symlink in /etc/ssl/certs/ To get it to work I went to Settings->Advanced->Privacy & Security->Manage Certificates->Authorities->Import and then selected my symlink produced by your docs at /etc/ssl/certs/lndo.site.pem

So what can we do to make this easier? If I'm understanding it correctly in the original PR #446 you're using a cert that you ship with the binary? I've used [mkcert](https://github.com/FiloSottile/mkcert) before with some success so that might be a route to look into to fulfilling #2 from the PR referenced above.

**Comment by pirog** [comment]
@MCDELTAT its possible that chrome changed how they handle CA's. guessing they no longer look at the system store but manage their own list now. in this case i think a simple documentation update would be sufficient.

**Comment by tylerssn** [comment]
I don't have time to PR the documentation, but here's what I have.

On Ubuntu Focal (20.04), I had to take the following steps:

1. Visit in Chrome: chrome://settings/certificates
1. Select "Authorities" tab
1. Click "Import" & provide: `~/.lando/certs/lndo.site.pem`

**Important** - this will work for `domain.lndo.site` but will _not_ work for `sub.domain.lndo.site`. You will need to either modify your proxy to `sub-domain.lndo.site` or use a PEM that considers `*.domain.lndo.site`

**Comment by gitressa** [comment]
Thanks @tylerssn. It was added to the documentation May 2021 in https://docs.lando.dev/config/security.html#ubuntu-with-chrome via #2982, thanks @tebb!

**Comment by DangDinhThi** [comment]
Updated:

Via #2982 -> https://github.com/lando/lando/pull/2982/files

On the Authorities tab at chrome://settings/certificates, import `/usr/local/share/ca-certificates/LandoCA.crt` and `/usr/local/share/ca-certificates/lndo.site.crt`
