### ISSUE TITLE
Can't install Lando under Ubuntu running with Windows WSL2

### ISSUE THREAD

**Issue by greggmarshall** [lando/lando#1983]
**Tell us about your setup**

v3.0.0-rc.23 on Ubuntu 180.04 running under WSL2 on Windows 10 Professional build 19599

Docker CE 2.2.1.0 (42746)

** What I got during installation from Ubuntu shell **

`sudo dpkg -i lando-v3.0.0-rc.23.deb
Selecting previously unselected package lando.
(Reading database ... 66326 files and directories currently installed.)
Preparing to unpack lando-v3.0.0-rc.23.deb ...
Unpacking lando (3.0.0-rc.23) ...
dpkg: dependency problems prevent configuration of lando:
 lando depends on docker-ce; however:
  Package docker-ce is not installed.

dpkg: error processing package lando (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 lando`

**Comment by greggmarshall** [comment]
Nevermind, just read all the installation instructions and it is possible to ignore the dependency.

**Comment by dustinleblanc** [comment]
@greggmarshall have you got this running okay? I just got a shiny new ROG Zephyrus G14 that I was hoping to develop on and as we all know, I got a need for speed.

I've been playing around with getting Lando running under standard Windows 10 Pro mode (works but at the speed of a lightly modified Honda Civic). On a brand new machine with the new Ryzen 9 4000 series chip, the results are less than stellar. I wanted to experiment with the WSL 2 setup because Docker desktop natively supports it and it promises a huge performance increase.

Even running Lando from source in WSL2 doesn't seem to work for me. Lando can't find the daemon

**Comment by dustinleblanc** [comment]
I stand corrected, once I install Lando in the right place (not bind mounted to Windows, it works!)

**Comment by marsjaninzmarsa** [comment]
(see also #1723)

**Comment by smutlord** [comment]
Closing in favor of ^ https://github.com/lando/lando/issues/1723
