### ISSUE TITLE
Is there a way specify ssl certs to use with Proxy domains?

### ISSUE THREAD

**Issue by troseman** [lando/lando#2022]
I'd like to use my own ssl certs for our proxy domains in lando.

We have some other systems dependent on specific domain names and want to avoid having to trust the domains in browser since it has a lando cert on it by default. this would make testing from clean browser session using ajax much easier.

Is there any way to do this?

**Comment by pirog** [comment]
@troseman we arent going to create a guide for this because its very hard for us to support people trying to do this. However, if you upgrade to Lando 3.0.0 or higher you can configure this directly in the global config. We actually dogfood this for Pantheon Localdev which is a GUI product built on top of Lando.

Check out:
https://docs.lando.dev/config/proxy.html#configuration

Depending on your flow you might want to modify some combination of:
* `proxyDefaultCert`
* `proxyDefaultKey`
* `proxyCommand`
* `proxyCustom`
* `proxyPassThru`
* `proxyDomain`
