### ISSUE TITLE
After emergency update app is not responding anymore

### ISSUE THREAD

**Issue by wernerglinka** [lando/lando#2069]
I am using Pantheons localDev.

When I opened localDev, There was a message to update immediately because of a "massive upstream change". I did and now nothing works anymore. When I try to start any one of my sites I get this "Something went wrong" dialog and the app freezes.

I am dead in the water. What's going on?

**Comment by pirog** [comment]
@wernerglinka we've tested the update pathway as best as possible, if its not working then you can also do a factory reset and reinstall as a last resort. if you want more information on the breaking change you can check out
https://blog.lando.dev/2020/03/20/update-to-3-0-0-aft-2/

also might be worth posting this in the relevant localdev queues since you'll probably get more relevant and useful feedback there

**Comment by pirog** [comment]
@wernerglinka the update _should_ be backwards compatible with Docker 2.1 (at least it is with Lando) but its possible this is not the case in which case you will need to update to the latest Docker 2.2 as well.

**Comment by pirog** [comment]
@wernerglinka i would try the latest version of Localdev, just released earlier today and that may resolve your issue
