### ISSUE TITLE
Homebrew formula should not be a cask

### ISSUE THREAD

**Issue by ChrisWiegman** [lando/lando#2109]
Currently Lando is using Homebrew's GUI management application, Cask, for install. This is inappropriate at Lando is not a GUI application and restricts Homebrew installation to Mac users only. How can I help you update the Homebrew installation for a standard install after tapping the repo? This would allow much easier installation on Linux as well as Mac plus it would better conform to Homebrew's methodology.

**Comment by pirog** [comment]
@ChrisWiegman we do not manage the Lando homebrew/cask installation pathway it is maintained by someone else.

**Comment by pirog** [comment]
@ChrisWiegman looking into this a bit more, i suspect Cask was used because Lando has a dependency on Docker Desktop.app. Not sure if that best practices or not but guessing that is what the maintainer was thinking.

im closing this out in favor of the meta issue over here which seeks to bring a bunch of related tickets together so we can figure out a plan. would love to get your feedback
https://github.com/lando/lando/issues/2217
