### ISSUE TITLE
Add Lando installer without Docker

### ISSUE THREAD

**Issue by Silic0nS0ldier** [lando/lando#2169]
**Please explain your request and its importance in the form of a user story.**
As a lando user who also uses Docker, I want the option to download the Lando installer without Docker Desktop bundled to reduce time spent waiting for the download to complete.

**Please provide some detail on how lando can help solve this problem**
Linux distro packages for Lando have a dependency on Docker Desktop (more specifically, Docker Community Edition) and as such have a significantly smaller download size. Ignoring the reason why this is the case (for all I can do is speculate), having Windows and MacOS installers which don't bundle Docker Desktop would be appreciated. Particularly when Docker is updated separately (which is more likely when Docker is also used direct).

**Is your feature request related to a problem? Please describe.**
Strictly speaking no, however it is annoying. Particularly when network conditions are not favourable resulting in obscenely long download times as the installer includes a dependency that is already satisfied.

**Describe the solution you'd like**
Additional Lando installers for Windows and MacOS which don't bundle Docker.

**Describe alternatives you've considered**
Using Lando on Ubuntu (WSL2) with it working on the Windows file system (via `/mnt/c/Users/...`). On MacOS, no such alternative exists.

**Additional context**
At present the large installer size delays the install significantly as parts of the network are bottlenecked. As an example, downloading Lando v3.0.0-rcc.3 is taking over 2 hours. An installer without Docker Desktop bundled would allow me to complete the update much sooner (and avoid the risk of it taking many more days to be actually installed if I forget to complete it).

**Comment by pirog** [comment]
@Silic0nS0ldier this is highly unlikely to happen. 

1. The linux versions are bundled the way they are because there isnt a single way to install docker on all linuxes and linux package managers have built in mechanisms that allow us to specify the dependency.
2. This is not true on Windows/macOS. It is also essential on Windows/macOS that we pin to a specific version of Docker Desktop to ensure that Lando actually works. Even small changes in Docker Desktop can sometimes break Lando because Docker Destkop is much more than just the Docker Engine. 

If download speed is the problem i think the better solution would be figuring out how to make download speeds faster eg offering a download that is not throttled by GitHub.

**Comment by Silic0nS0ldier** [comment]
If the concern is having Lando break more frequently (resulting in more issue reports), there are ways to delivery it without bundling Docker while still maintaining the needed version constraint.

Windows has Chocolatey which is often used to install software (particularly for automating the process in deployment scenarios, I use this myself and it would be particularly beneficial for onboarding new starters were I work since it would be one less task to handle on their first day) lets a version requirement be specified for dependencies. e.g. https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/php/php.nuspec#L35 MacOS meanwhile has Homebrew.

As I understand it, all these package managers would allow installing Lando without requiring Docker Desktop to be downloaded potentially unnecessarily and the incompatible version risk.

While not the solution I'm hoping for, offering download mirrors is something I'm all for since it offers a chance to get a better connection with more bandwidth (and offers some redundancy should GitHub experience an outage which unfortunately happens on occasion)..

**Comment by pirog** [comment]
@Silic0nS0ldier having something you can get via chocolatey is fine (pretty sure there is already an issue for that), AFAIK we already have a third party maintaining the homebrew install pathway and this is documented. 

However, these cannot be the _default recommended_ installation pathways because we cannot assume the user has brew or chocolatey in the same way that a debian user has apt.

It's also important to note that you can always install lando from source which delegates the responsibility for grabbing dependencies to the user eg if you already have the dependencies installed this is going to be the most light weight option.

**Comment by pirog** [comment]
All that said i think a proposal like this makes the most sense:

1. Get a choloately install pathway to go with our "other package manager" install pathways eg brew and apt
2. When lando prompts you to update, check to see if the user has the needed package manager and if so instructs the user to run the associated update command with that package manager. If not, link them to the release page for the full download
3. In the installation documentation have the full package as the preferred installation pathway but list the package installer ways and highlight their usefulness in terms of speed

**Comment by Silic0nS0ldier** [comment]
My bad, misclick. 🤦

**Comment by pirog** [comment]
@Silic0nS0ldier im closing this out in favor of the meta issue over here which seeks to bring a bunch of related tickets together so we can figure out a plan. would love to get your feedback
https://github.com/lando/lando/issues/2217

**Comment by stevenlafl** [comment]
*sigh*

For posterity, and I KNOW this has to get viewed by a lot of people looking for the answer.

If you have Docker Desktop for Windows with WSL 2 integration enabled:
```
sudo dpkg -i --ignore-depends=docker-ce,iptables lando-x64-v3.19.5.deb
```

**Comment by pirog** [comment]
just to provide an update on this: One of the focuses (foci?) of Lando 4 will be improving distribution so there will be non-docker based installers/methods available.
