### ISSUE TITLE
Sort info URLs by preference

### ISSUE THREAD

**Issue by pirog** [lando/lando#2219]
We should sort the URLS surfaced in `lando info` so they are ordered by "most preferred". Generally this would mean a sort order of

1. proxy URLS before localhost ones
2. https before http

**Comment by martin-klima** [comment]
@pirog How the URLs are ordered now?

I always had http://project_name.localhost on the 1st place and we used the URL as Drupal `$base_url` in settings.php.
Suddenly the order is changed since yesterday after rebuild (I have not an idea what I changed) and we need to make sure it is sorted by some logic :)
Now I have:
```
 { service: 'appserver',
    urls:
     [ 'https://localhost:32843',
       'http://localhost:32844',
       'http://sn.localhost/',
       'https://sn.localhost/' ]
```
Thank you for info in advance.

**Comment by pirog** [comment]
@martin-klima there isnt a sorting order as far as i know and this isnt something you should be relying on.
