### ISSUE TITLE
tooling commands can't handle command substitution

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2279]
It seems that tooling commands can't handle command substitution like:
**command $(subcommand)** or **command \`subcommand\`**

https://ss64.com/bash/syntax-substitution.html

Docs state:
```
If Lando sees any combination of |, <, >, or & in any of the defined commands, it will automatically wrap the entire command in /bin/sh -c "<command>".
```

Is there a reason tooling commands aren't always executed via `/bin/sh -c`? Otherwise commands containing backticks or dollar characters should be run via `/bin/sh -c`.

What I had to do for now is to use `/bin/sh -c` "manually":
**/bin/sh -c "command $(subcommand)"**

Using Lando 3.0.3 on Windows.

**Comment by pirog** [comment]
@thasmo this should be handled in `3.0.7`. 

we cannot wrap everything in `/bin/sh -c` by default because of how node handles args and the types of tooling commands you can make. the `tl;dr` with this change though is any tooling command that does not take additional user args will be auto wrapped in `/bin/sh -c`.  while this is still not perfect it should provide a better and more consistent experience overall.
