### ISSUE TITLE
Turn off "WARN ==> You have a lot of keys!" notice

### ISSUE THREAD

**Issue by thetwopct** [lando/lando#2389]
Is it possible to turn off "WARN ==> You have a lot of keys!" or at least globally confirm I have understood the warning?

Just like the upgrade notices that were shown before I upgraded, the `WARN ==> You have a lot of keys!` notice seems to be excessively shown.

```
❯ lando stop
WARN ==> You have a lot of keys! 
This party's over :( Stopping app test1
WARN ==> You have a lot of keys! 
App test1 has been stopped!
```

```
❯ lando destroy
WARN ==> You have a lot of keys! 
? Are you sure you want to DESTROY? Yes
```

- I have maybe 9 or 10 SSH keys, that's just how many I have, I am not going to reduce this amount just for Lando. 
- We share our lando.yml files across our team, so adding all our key names to this file just to please this warning doesn't make sense as then the file will be looking for key names that don't even exist on my system.
- I could use keys:false, but I need access to one key, so that's not a solution as far as I understand
- When I start an environment, it gives me a warning now. A warning about the keys. Now I just skip over that part, so I'd probably miss a genuine warning.

Possible solutions:
- Let me confirm this is an issue once, and globally save that for all projects.
- Let me add something to the lando.yml file per project to stop the warning / confirm I have seen it.
- Just stop showing the warning after `WARN ==> You have a lot of keys!` every `WARN ==> You have a lot of keys!`  thing `WARN ==> You have a lot of keys!`  lando `WARN ==> You have a lot of keys!`  prints.

Thanks!

**Comment by pirog** [comment]
@thetwopct i think there are some improvements we can make to this, particularly around the excessive initial warnings. That said, much of what you suggest here is already possible.

1. We don't want, or recommend, you reduce your keys just for Lando. However, it is also important we warn you if you are in a situation where your keys dont work as expected. 
2. As documented in the SSH keys config page, the `keys` key is meant to be used in combination with a (user space Lando override file)[https://docs.lando.dev/config/lando.html#override-file]. This file is gitignored and is meant to be provide user-specific overrides, eg you would not put ALL the keys of ALL the users here, just yours.
3. This should be better documented but if run `lando config` you will see a `maxKeyWarning` setting. This value can be overridden in a lando [global config](https://docs.lando.dev/config/global.html#config-yml) file eg you can effectively disable the warning if you set the value to a large number.

That said i think we are down to:

1. Reduce the frequency of the warning, this was definitely not intentional
2. Document the global config setting better so users can easily alter the conditions of the warning if the warning is too much for them to handle

**Comment by thetwopct** [comment]
Awesome, thanks for response on this. I had missed the `.lando.local.yml` option, so will use that in our workflow! Thanks 🙏🏼

**Comment by pirog** [comment]
sure thing. looks like 1 and 2 from https://github.com/lando/lando/issues/2389#issuecomment-648219157 are in `master` now so those will be in the next release
