### ISSUE TITLE
Lando in WSL

### ISSUE THREAD

**Issue by UrielNicolas** [lando/lando#2406]
How do I do it?
Is it possible? Can I install everything through the WSL console or what steps do I need to do?

I did it once, but I can't find the doc (didn't save it, shame on me), but I wanted to run lando inside WSL, I tried installing docking through the console but it didn't work.
Does anyone have a guide or something?

Many thanks

**Comment by dustinleblanc** [comment]
Hey @UrielNicolas!

Yes, Lando in WSL2 essentially installs just like Lando on Linux. The big difference is that WSL2 has no init system, so you have to start docker manually when starting up WSL. https://github.com/lando/hyperdrive works really well if you are using a Ubuntu 18.04 based distro in WSL, otherwise, you might have to do some tweaks to get docker installed on the distro of your choosing. Checkout out #1723 for a lot of discussion on how people have set things up.

I can report as a both a maintainer and a daily user, it works pretty damn well!

**Comment by UrielNicolas** [comment]
> Hey @UrielNicolas!
> 
> Yes, Lando in WSL2 essentially installs just like Lando on Linux. The big difference is that WSL2 has no init system, so you have to start docker manually when starting up WSL. https://github.com/lando/hyperdrive works really well if you are using a Ubuntu 18.04 based distro in WSL, otherwise, you might have to do some tweaks to get docker installed on the distro of your choosing. Checkout out #1723 for a lot of discussion on how people have set things up.
> 
> I can report as a both a maintainer and a daily user, it works pretty damn well!

Thank you for your reply! My device is still not up to date to get the latest release of May 2020, so I need to wait a bit more for WSL2!

**Comment by JorisVanEijden** [comment]
@UrielNicolas no need to wait, you can manually update already with the update assistant: https://www.microsoft.com/en-us/software-download/windows10
