### ISSUE TITLE
Issue running "Lando Pull" — error pulling database

### ISSUE THREAD

**Issue by aimhighagency** [lando/lando#2420]
**Tell us about your setup**
`lando v3.0.0-rrc.3 OSX 10.15.4
`

**Tell us about your `.lando.yml`**
```
name: xxxx
recipe: pantheon
config:
  framework: drupal8
  site: xxxx
  id: xxxx

```
**`pantheon.upstream.yml`**
```
api_version: 1
php_version: 7.3
```

**Tell us about the command you were running**
lando pull

**Tell us about the error you got**
```
Pulling database from dev...
ERROR 1064 (42000) at line 40: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTR' at line 1
2.05KiB 0:00:04 [ 486 B/s] [<=>
```

**Tell us generally about your bug**
I was trying to pull the DB and got this error. It has worked before in the past.
I updated Docker.
I tried a `lando rebuild`

**Comment by dustinleblanc** [comment]
Hey @aimhighagency!

rrc3 is a bit out of date, could you try updating to the latest stable release and see if you still have issues? I suspect you might because I see this kind of issue pop up on people's Drupal sites all the time, and if I am not mistaken, I think it is related to some odd contents in the database, but let us know if you still have issues after updating.

**Comment by aimhighagency** [comment]
That did the trick. THAAAANK YOU!
(I thought I had recently updated lando - but I guess "recently" feels very different during these crazy times)
