### ISSUE TITLE
Unnecessary Drush warning

### ISSUE THREAD

**Issue by danepowell** [lando/lando#2550]
As a lando user using stock recipes and best practices, I don't want to see a big, scary, and annoying warning about Drush being installed globally. (_I_ know it's not really scary or indicative of a problem, but it's pretty bold and I'm sure scares some users)

I have a Drupal 9 site using a stock drupal9 recipe / .lando.yml, and with Drush 10 installed locally via Composer. When I run `lando start`, I get a big warning:

```
  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ May need site-local drush
   Lando has detected you are trying to globally install drush ^10
   This version of drush prefers a site-local installation
   We recommend you install drush that way, see:
   https://docs.drush.org/en/master/install/
```

As far as I can tell, this warning is bogus. I've done nothing to install Drush "globally" (though I do have the shim/launcher installed on my host machine), and it's installed locally as per best practice.

This seems like an unnecessary warning that shouldn't appear for folks using an out-of-the-box Lando setup.

My .lando.yml:
```
name: foo
recipe: drupal9
config:
  webroot: docroot
```

**Comment by mstrelan** [comment]
Perhaps lando could determine if a site-local drush is already installed. Or perhaps instead of saying "you are trying to globally install drush ^10" it should say something like "we have installed drush ^10 for you but you shouldn't use it". Or perhaps drush-launcher should be installed globally instead of drush.

**Comment by gitressa** [comment]
I have arrived at exactly the same three solutions in #2582 @mstrelan. I am leaning towards [not installing global Drush 10](https://github.com/lando/lando/issues/2582#issuecomment-708664774) if site-local Drush exists, for example by checking for `drush/drush` in `composer.json`. What do you think?

**Comment by mstrelan** [comment]
drush/drush could be required and not necessarily exist in the root
composer.json

**Comment by TrevorBradleyCDN** [comment]
The problem is explicit to the drupal9 recipe. If I switch back to drupal8 it goes away.  This is on a machine without a globally installed composer drush, and drush/drush:^10 installed via lando composer. 

I downloaded lando from the repo and got it up and running.  The problem appears to be in plugins/lando-recipes/types/drupaly/builder.js

```
        // Attempt to set a warning if possible
        const coercedDrushVersion = semver.valid(semver.coerce(options.drush));
        if (!_.isNull(coercedDrushVersion) && semver.gte(coercedDrushVersion, '10.0.0')) {
          options._app.addWarning(warnings.drushWarn(options.drush));
        }

```

For a drupal8 recipe, coercedDrushVersion is "8.3.5", but for drupal9 it's "^10", and it triggers the drushWarn, which throws the error we're seeing.

If I entirely remove drush locally (lando composer remove drush/drush), I still get the error, so the coercedDrushVersion must be getting its drush version from elsewhere.
I'm not sure what
It appears to be defined in lando-recipes/recipes/drupal9/builder.js , where it's hard coded to "^10":

```
module.exports = {
  name: 'drupal9',
  parent: '_drupaly',
  config: {
    confSrc: __dirname,
    defaultFiles: {},
    php: '7.3',
    drush: '^10',
  },

```
Something is messed up here. Presumably there's some code that's looking for a global composer drush that's misfiring for the drupal9 recipe, but is just fine for the drupal8 recipe.  I can "fix" it, but I'd likely be breaking something else I don't know about.

**Comment by gitressa** [comment]
See @pirog's answer in a related issue, for a possible solution: https://github.com/lando/lando/issues/2582#issuecomment-710088861.

**Comment by TrevorBradleyCDN** [comment]
The new master branch and 3.0.17 both work beautifully, and the error is gone.  Thank you!
