### ISSUE TITLE
Running a script outside of the container on the host with Lando

### ISSUE THREAD

**Issue by ayalon** [lando/lando#2571]
I'm desperatly looking for a way to run a script in an event hook outside of the container on the host.

I'm using WSL 2 and need to run a command using powershell. Inside the container, powershell is not available.

I want to start the mutagen sync process on the Windows side and this cannot be done from within the container. Do you have any suggestions how to do this?

```
  post-start:
    - powershell -File sync.ps1
```

This will be translated to

`/bin/sh powershell` run in the container. But I need this command to be run on the host.

**Comment by maskedjellybean** [comment]
I would love to know this too. Did you ever figure it out?

**Comment by ayalon** [comment]
It is not possible. We need the help of a maintainer to add this possiblity. This is the last missing puzzle to make the perfect setup together with WSL2 on Windows.

**Comment by hanoii** [comment]
yes, I also had the need. Most notably what I need this for is so that I can do something with the container but from what the host sees on `lando info`.

In a concrete example, I have a `drupal8` recipe with a rocketchat service alongside. I need to configure a setting with rocketchat so that it access the drupal url from the host (in the browser). However the Drupal URL is not always the same (I am using random ports because 80 and 443 are taking and lando keeps giving me `444` and `4433` alternatively. 

So a script in my case would do fetch the current appserver URL with lando info and then run something within the rocketchat container with this URL that will configure it properly. It's like a post-start but on the host or some way of running hosts scripts after `lando start` finishes.

**Comment by ayalon** [comment]
A short hint / documentation how this could be achieved qould be great.

**Comment by AleMadLei** [comment]
DDev has this feature
https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/

**Comment by AleMadLei** [comment]
DDev has this feature
https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/
