### ISSUE TITLE
lagoon `lando init` improvements

### ISSUE THREAD

**Issue by pirog** [lando/lando#2644]
@mikemilano lets review this after we wrap up #2450. The fact that we are able to do a `lando init --source lagoon` is impressive given the complexity of authentication. However, there are a few things we should consider longer term

1. Do we need to prompt for an email _before_ the user is given a public key to copy/paste? Seems like we could cut out that step and then once auth happens grab the email from a `whoami` call? This way we can avoid a step and perhaps more importantly avoid reconciling the user entered email from the actual canonical email associated with the key.
2. It would be great to get the init working by passing in a key non-interactively so we can test this flow
3. Is there a process for key cleanup? eg what happens when newly entered emails never get authed? is there a way to remove them from the list? This might also be avoided by the change proposed in 1.
4. How do we auth against other lagoon instances?

**Comment by thom8** [comment]
1> We don't need to prompt for an email as a key can only be associated with a single user account in Lagoon. Would be nice to be able to pass another key to use for authentication.

4> We'd need to pass in the API/SSH endpoints + SSH port for the lagoon CLI to to authenticate against other lagoon instances.

**Comment by pirog** [comment]
Thanks for the feedback @thom8, that aligns with what we'd like to do to polish it up!

**Comment by thom8** [comment]
Run into a bit of a bug with the search functionality -->

```
23:30 $ lando init
? From where should we get your app's codebase? lagoon
? Select a Lagoon account xxxx
Starting landoinitlandoinit_init_1 ... done
Connection to ssh.lagoon.amazeeio.cloud closed.
Killing landoinitlandoinit_init_1 ... done
? Which project? aERROR ==> undefined is not a function
  Searching...
```

As soon as I enter a character to search it throws the error `undefined is not a function`, could be due to me have access to a very large number of projects.

**Comment by pirog** [comment]
Ahhh interesting! That definitely might be a bug on our end since we only have one project to test with!

**Comment by mikemilano** [comment]
@pirog @thom8  Regarding email: A single Lagoon account is a combination of email and host. A Lando SSH key for Lagoon is also a combination of email and host.

As a contractor, it was common for me to have different accounts for a single hosting provider. To support this case, something besides the host is required to make the distinction. Since Lagoon accounts are based on email addresses, I went with that.

A user with 2 accounts will get the appropriate project list by selecting the appropriate email address (and default host behind the scenes), which is a 1 to 1 relation to the key we asked them to add to their Lagoon account.

When we add support for the alternate Lagoon hosts, we can show the host along with the email address.

**Comment by pirog** [comment]
@mikemilano i think the point being made is that the "email" part can be divined AFTER a key is authed against a host eg in order to auth against a given lagoon host you only need a key, an email is not required. Once that auth has happened you can then use the API to determine what account/email the key's public component was added to and this is the email that is stored in lando, as opposed to the one the user currently enters. I _think_ right now a user could type in an email, add the public key to an account with a DIFFERENT email and then end up with a stored key that is associated with the incorrect email?

@thom8 correct me if im wrong here.

**Comment by mikemilano** [comment]
@pirog had a reply typed out but most not have sent. I understand the desired behavior now, thanks for clarifying. It will take some extra work to manage the key between when we create it and when we know who the user is, but it's not much.

I have a fix for the autocomplete issue, but it involves code that has been refactored for the push/pull effort. 
To avoid conflict, I'll include it in that effort since it is near complete.

**Comment by pirog** [comment]
@mikemilano sounds good! i think we can wait on the improvements suggested here until the next dev cycle. I spun up this ticket just to get a head start on making sure those improvements make sense and are desirable.

The autocomplete bug referenced by @thom8 we should definitely fix though. I'll review your fix as part of the push/pull stuff.

**Comment by thom8** [comment]
> @mikemilano i think the point being made is that the "email" part can be divined AFTER a key is authed against a host eg in order to auth against a given lagoon host you only need a key, an email is not required. Once that auth has happened you can then use the API to determine what account/email the key's public component was added to and this is the email that is stored in lando, as opposed to the one the user currently enters. I _think_ right now a user could type in an email, add the public key to an account with a DIFFERENT email and then end up with a stored key that is associated with the incorrect email?
> 
> @thom8 correct me if im wrong here.

This is correct Lagoon will not allow a key to be added to multiple accounts, therefore the key auth will determine the account. There's the possibility that a key is transferred to another account but it can never attached to more than one.
