### ISSUE TITLE
Lando MEAN now urls not working

### ISSUE THREAD

**Issue by nrome-n** [lando/lando#2646]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*Example: v3.0.0-rc.2 on Windows 10 Professional*

v3.0.14 on Mac OS 10.15.7

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: lamp2
recipe: lamp
config:
  php: '5.6'
  webroot: www
  database: mysql
  xdebug: true
```

```
name: lando_node
recipe: mean
config:
  webroot: .
  node: 10
  port: '32784'
  command: npm start
  # command: su - node -c '/var/www/.npm-global/bin/ghost run -d /app/src -D'
  ssl: true
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

*Example:*

```bash
lando init --sourcer remote --recipe lamp --webroot web
lando start
# Edited my lando.yml as above
lando rebuild -y
```
package.json
```
  },
  "author": "n_nets_team",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  },
  "scripts": {
    "start": "node app.js"
}

}
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Example:*

```bash
lando php -e "phpinfo();" -vvvv
```
 I am not going and error lando  APPSERVER URLS all in red and not working 
and new to lando and node but my code is running fine 
```
 NAME            lando_node                         
 LOCATION        /Volumes/nromex/Project/nrome/node 
 SERVICES        appserver, database                
 APPSERVER URLS  http://localhost:32777             
                 https://localhost:32778            
                 http://lando_node.lndo.site/       
                 https://lando_node.lndo.site/     
```
log
```
appserver_1  | lando 17:43:58.67 INFO  ==> Lando handing off to: /bin/sh -c npm start
appserver_1  | 
appserver_1  | > learn_node@1.0.0 start /app
appserver_1  | > node app.js
appserver_1  | 
appserver_1  | Server ON! 
```

**Tell us generally about your bug**

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?
not sure not the docs are clear on how to set up. yes, can't run my node app

**Comment by nrome-n** [comment]
just to be clear an not sure that this is a dug but NO Error is showing. that is not not the normal behaviors but not sure a this my first lando project

**Comment by pickettd** [comment]
On my machine (Win 10) I had this same problem (and today is also my first time using lando). I think I got the MEAN recipe to work, but I had to setup the bindAddress to be 0.0.0.0 in order to get MEAN urls to be accessible from my host machine. It was a strange issue, because I did not have to do this for the urls to work when I tested the getting-started LAMP recipe. There were two ways I was able to get MEAN urls to work.

Option 1) In my index.js file for node/express, I was able to use `app.listen(2368, '0.0.0.0');` and that seemed to get the host able to access the MEAN url (after restarting the appserver).

Option 2) I was able to follow the instructions at https://docs.lando.dev/config/security.html#_1-changing-the-bind-address (and keep the index.js ExpressJS code as `app.listen(2368);`) - but I did use `lando poweroff` and `lando start` after changing the global config.

Note that in the [MEAN recipe example page](https://github.com/lando/lando/tree/master/examples/mean), the test cases that runs uses the script `lando ssh -s appserver -c "curl -L localhost:2368"` which was working (because node was working inside the container) - it is just that I couldn't reach the appserver from my host browser until I made a change for the bindaddress.

**Comment by pickettd** [comment]
I think I ran into this same problem today (and I thought it was the same issue as https://github.com/lando/lando/issues/2465 ). Today is my first time trying lando and the getting-started LAMP example worked fine for me (Win10 host). But when I tried the MEAN recipe I could not get my host machine's browser to connect to a node/express server in lando. I was able to use `lando ssh -s appserver` and curl to verify that once inside the appserver, curl was able to connect properly and the service was running. I did try several things with bindaddress and HOST=0.0.0.0 because I've had to do that before with docker-compose projects and node. However I think just clearing my docker cache of images (as mentioned in issue 2465) did actually fix the problem.

**Comment by reynoldsalec** [comment]
As stated by @pickettd, clearing your docker cache of image or restarting Docker are good debugging tricks if you're having trouble connecting to your app.

Also make sure you're not being impacted by this issue: https://docs.lando.dev/help/dns-rebind.html
