### ISSUE TITLE
Specify local directory with "--remote-options"

### ISSUE THREAD

**Issue by klonos** [lando/lando#2752]
So I have this:

```bash
lando init \
  --source remote \
  --remote-url https://github.com/drupal/drupal.git \
  --remote-options="--branch 8.9.x --depth 1"
```

...which is the equivalent of `git clone --branch 8.9.x --depth 1 https://github.com/drupal/drupal.git`

How do I specify the local directory to clone into? i.e.:

`git clone --branch 8.9.x --depth 1 https://github.com/drupal/drupal.git my-custom-dir`

**Comment by pirog** [comment]
I _think_ there is a `--dir` flag you can use for this purpose. We've got plans to address this and other less-than-ideal parts of the `lando init` experience in the next major Lando version

**Comment by klonos** [comment]
>I _think_ there is a `--dir` flag you can use for this purpose.

Unfortunately no 😞 ...see: https://git-scm.com/docs/git-clone

All other parameters have a `--` flag, but specifying the directory to clone into is a "plain", flag-less parameter at the end of `git clone`. Glad to see that this is on your radar though, so I'll wait for it to be implemented. Thanks 🙏

**Comment by pirog** [comment]
@klonos i meant on the lando side eg `lando init --dir somefir`, it might be undocumented

**Comment by blue928** [comment]
Would like to +1 this.

I'm new to Lando and when running lando init --with-some-options one would think that with the directory specified by`--webroot` flag, --remote-url would automatically clone that into the specified webroot directory.

As it's designed now, it seems to either be a bug, or at the very least doesn't make sense as it always clones it into the same dir as .lando.yml file. IMO this renders using lando init pretty useless, no? Especially for Drupal 8+ projects where docroot is web and the directory directly above it is for composer and other non-public essential files.

This means no matter what, I still have to go in and edit the .lando.yml file and provide custom tooling that provides a command specifically to run "git clone my@project.git <DESIRED_DIR>" which seems to be an unnecessary step.

+1 for --remote-options dir=<mydir> defining into what directory the files should be placed, or even better, if --webroot is present as an option, the code logic will always clone it into there (or place source files from whatever source there) rather than the default '.' directory. Otherwise, I don't see the point of specifying webroot at all when you just have to manually move files or cd into webroot to manually to run git, which, doing so, renders the option --github-repo or --remote-url useless?

**Comment by pirog** [comment]
`lando init` tries to do too much and this probably accounts for some of the weird behavior with certain intention and options combinations. Our plan is to split it up into 3-4 separate commands which likely will some if not all of the concerns addressed in this thread.
