### ISSUE TITLE
Bind to port 80 / 443 not possible

### ISSUE THREAD

**Issue by sgurlt** [lando/lando#2787]
Hey guys,

I just started to use lando and ran into the issue that binding to port 80 is not possible. I am on MacOS Big Sur (11.1).
After downloading Lando and applying it to my code base i ran 'lando start'.

Here are some vitals:

```
Here are some vitals:

 NAME            cs-integrations_tests-drupal_8
 LOCATION        /Users/sebastian.gurlt/Work/Edge-Box/automated-tests/lando/cs-integrations_tests-drupal_8
 SERVICES        appserver, database
 APPSERVER URLS  https://localhost:55069
                 http://localhost:55070
                 http://cs-integrations_tests-drupal_8.lndo.site/
                 https://cs-integrations_tests-drupal_8.lndo.site/
```

The two bottom urls are red and not reachable.
I checked the docs and followed the advice within the proxy section:

```
sudo lsof -n -i :80 | grep LISTEN

com.docke 24942 sebastian.gurlt   78u  IPv4 0x11d36363cb750e29      0t0  TCP 127.0.0.1:http (LISTEN)
```

After that i ran `lando stop` and checked again.

```
lando stop
This party's over :( Stopping app cs-integrations_tests-drupal_8
Killing csintegrationstestsdrupal8_database_1  ... done
Killing csintegrationstestsdrupal8_appserver_1 ... done
App cs-integrations_tests-drupal_8 has been stopped!

sudo lsof -n -i :80 | grep LISTEN

com.docke 24942 sebastian.gurlt   78u  IPv4 0x11d36363cb750e29      0t0  TCP 127.0.0.1:http (LISTEN)
```

I continued with `docker ps`

```
docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS         PORTS                                                                     NAMES
74ca27bb8da7   traefik:2.2.0   "/lando-entrypoint.s…"   57 minutes ago   Up 8 minutes   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:55062->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1
```

What i can see from here is that `landoproxyhyperion5000gandalfedition_proxy_1` is bound to port 80 and 443, but the ports are not working in combinaton with the lando sites.

What i tried for now:
- Stop all containers end restart (`docker stop $(docker ps -a -q)`)
- `lando rebuild`

Both without any luck.

Any advice what I could have been doing wrong?

Here is my `.lando.yml`

```
name: cs-integrations_tests-drupal_8
recipe: drupal8
config:
  webroot: docroot
```

**Comment by dustinleblanc** [comment]
Hey @sgurlt! One thing to note is that unless you run `lando poweroff`, we keep the proxy up and bound to whatever ports it bound to when starting.

I do wonder if the issue you are seeing with access to the proxy routes might be related to the really long dash + underscore app name?

What do you see in the browser when you visit it? Can you try with a shorter and simpler name like `cs-integrations` or `cs-integrations-tests-d8`?

Thanks!

**Comment by sgurlt** [comment]
Hey @dustinleblanc,
thanks you for the quick answer :) 

When i open up the shown URL: http://cs-integrations_tests-drupal_8.lndo.site/

I am facing: 
![image](https://user-images.githubusercontent.com/8554668/103617471-99a8d280-4f2e-11eb-90fa-10bbdb2027ea.png)

What i just tried 5 minutes ago and ended up good was a different URL for my appserver:

```
name: cs-integrations_tests-drupal_8
recipe: drupal8
config:
  webroot: docroot
  drush: "^9"
proxy:
  appserver:
    - default-export.localhost
    - default-import.localhost
...
```

I am still facing the red URLs:

![image](https://user-images.githubusercontent.com/8554668/103617694-fefcc380-4f2e-11eb-8939-72ff1e56b23e.png)

But the page is loading without and issues :-)

Is there something else I should check so that I could support the community?

**Comment by dustinleblanc** [comment]
If .localhost is resolving, my guess is that the issue is with DNS. `*.lndo.site` is an on-the-web resolver that redirects to localhost, you probably have something setup to locally to resolve .localhost (either hosts file or DNSMasq, etc). If you want to automatically use .localhost as your TLD, I'd recommend just configuring Lando to do so: https://docs.lando.dev/config/proxy.html#configuration

I'd pick something like `lando.localhost` as your domain, and then each project would automatically get `project.lando.localhost` as it's proxy route.

The preferred solution would be to resolve the DNS issue and just use the default proxy addresses, but everyone's situation is different

**Comment by wesleymusgrove** [comment]
I think I've been running into the same thing.  I'm developing "offline" with a custom domain name that's being resolved by my hosts file.

I've got a really simple Landofile
```
name: my-first-drupal8-app
recipe: drupal8
config:
  webroot: .
proxy:
  appserver:
    - drupal.lando
```
I added this entry into my hosts file:
```
127.0.0.1 drupal.lando
```

When I run `lando start`, it assigns those random ports instead of defaulting to port 80/443.
```
 NAME                    my-first-drupal8-app
 LOCATION             C:\lando\drupal
 SERVICES               appserver, database
 APPSERVER URLS  https://localhost:32796
                               http://localhost:32797
                               http://drupal.lando/
                               https://drupal.lando/
```

Are the localhost domains supposed to be assigned ports 32796/32797 instead of 80/443?

Or is that correct and http://drupal.lando is supposed to work on port 80 and https://drupal.lando is supposed to work on port 443?

The weird thing I'm noticing is that my custom domains work if I use the ports 32796/32797 instead of 80/443.
![image](https://user-images.githubusercontent.com/1711791/105320356-ad3d7580-5b8b-11eb-8e29-7cbe4e6036e1.png)

In Docker Desktop it's showing that those ports 80/443 are "not binded".
![image](https://user-images.githubusercontent.com/1711791/105320573-efff4d80-5b8b-11eb-9254-fb9b042c85a7.png)

I don't think it's because I have other services running that are taking up ports 80/443 and blocking Lando from using them because if I run the Docker getting started app that specifies the port bindings... it works.
```
docker run -d -p 80:80 docker/getting-started
```

I can see that port 80 is bound correctly.
![image](https://user-images.githubusercontent.com/1711791/105320829-48cee600-5b8c-11eb-9f31-8f63575916d2.png)

Also if I open that getting started app up in the browser, it's definitely using port 80.
![image](https://user-images.githubusercontent.com/1711791/105320975-74ea6700-5b8c-11eb-9f42-810cc8b17714.png)

So what's going on with Lando and why can't it bind to port 80/443 when a issuing a regular `docker` command can?
