### ISSUE TITLE
Upgrading from v3.0.26 to v3.0.27, no more *.lndo.site URLs

### ISSUE THREAD

**Issue by jazty** [lando/lando#2934]
After updating from v3.0.26 to v3.0.27 I don't have *.lndo.site URLs for any of my projects.

Steps to reproduce:

- Update Lando to v3.0.27;
- Rebuild project;
- Only see localhost URLs:  ie. https://localhost:49187, http://localhost:49188

Expected results:
- Would see *.lndo.site URLs: ie. http://project.lndo.site, https://project.lndo.site

Also, trying to access the project.lndo.site URLs doesn't work, so it's not like they simply aren't printing in the "Vitals" summary.

OS: Fedora 33
Docker version: 20.10.5

**Comment by uberhacker** [comment]
I can back up @jazty's claim.

**Comment by uberhacker** [comment]
I also tried `rm -rf ~/.lando && lando rebuild -y` but the issue remained.

**Comment by serundeputy** [comment]
so far we have confirmed the issue on `drupal7`, `drupal8` sites.

**Comment by mikemilano** [comment]
@serundeputy, @dustinleblanc, and I have tested various projects. It seems to be isolated to `drupal7`, `drupal8`, and `drupal9` recipes.

- Reproducible on recipes `drupal7`, `drupal8`, `drupal9`
- Not reproducible so far on anything else, including Acquia/Pantheon/Platform recipes running Drupal apps. Integration tests have included the following:
  - Acquia d8
  - Platform d7, d8, d9
  - Pantheon d8

Note that integrations extend `_drupaly`  just as `drupal7`, `drupal8`, and `drupal9` do. Just calling that out because I'd otherwise expect it to be at that parent level if it is in fact specific to Drupal.

**Comment by mikemilano** [comment]
@jazty @uberhacker Manually declaring the proxy in your `.lando.yml` file seems to be a workaround while we get this sorted out.

```
name: mysite
recipe: drupal8
proxy:
  appserver:
    - mysite.lndo.site
    - www.mysite.lndo.site
```

**Comment by rubenvarela** [comment]
Okay, not crazy. 

I can confirm this too on D7 and D9. 

Going the proxy route. Thanks @mikemilano

**Comment by serundeputy** [comment]
If you are swapping in `nginx` for `apache` you will want:

```yaml
proxy:
  appserver_nginx:
    - myste.lndo.site
    - www.mysite.lndo.site
```

**Comment by pirog** [comment]
Alright, going to roll a hotfix release with this in a moment!
