### ISSUE TITLE
Adding Strapi to recipes

### ISSUE THREAD

**Issue by denics** [lando/lando#2988]
As strapi.io is gaining visibility as headless CMS and can be used, for example, to support other CMS in the task of managing datasets, I was wondering if it could be added to Lando recipes.

**Comment by reynoldsalec** [comment]
If there's a Strapi-savy developer out there interested in creating this recipe, LMK. it'll probably make the most sense to do this on the Lando v4 API, since that's now nearing readiness for making individual services and soon should be a good platform for all new recipes...making things on v3 seems like an invitation for having to re-do your work :)
