### ISSUE TITLE
Is it possible to separate webserver access and error logs with `lando logs`?

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#315]
Feature/Enhancement Request
===========================
It would be nice to isolate errors from access log entries to help identify bugs easier with something like `lando logs -s appserver --errors`.

**Comment by pirog** [comment]
@uberhacker not saying that this is impossible but because `lando logs` is a light wrapper around `docker logs`, and because `docker logs` does not provide this kind of functionality its not trivial for us to do this.

AFAIK `docker logs` just surfaces what is written to `stdout` and `stderror` and doesn't have any knowledge of specific service log files. This design makes sense to me given that i'm not exactly sure how docker (or lando) could reliably discover log files like this given that default log set up varies a good deal from service to service and this setup is additionally alterable by the user. 

If you've got a specific suggestion on how we could get around that i am definitely all ears because it would be a pretty cool featue (and provide a level up of the underlying func provided by `docker logs`)

**Comment by pirog** [comment]
@uberhacker did some more research on this and until docker provides a better interface for log access i dont think this is possible in the way you envision it.

**Comment by gregpymm** [comment]
I have found that piping through a "grep" command can be helpful to filter out only what you want...
`lando logs -f | grep WARNING`
