### ISSUE TITLE
Spin off Pantheon recipe into its own plugin

### ISSUE THREAD

**Issue by pirog** [lando/lando#3196]

**Comment by sk33lz** [comment]
@pirog I currently cannot get PHP 8.0 working at all in Lando for a Pantheon site locally if I set the PHP version to PHP 8 using the pantheon recipe. I take it this issue is to resolve that?

I've tried setting it as `8.0` and `"8.0"` in the pantheon.yml and the .lando.yml file to no avail. The only way I was able to get Lando to even try building the site was to remove the `php_version` setting in the pantheon.yml, but then PHP gets set to `7.0.x` even if `php: "8.0"` is set in the .lando.yml. Otherwise I am told `ERROR ==> php version 8 is not supported`. Removing that from the pantheon.yml obviously would also set the wrong version in the Pantheon environments.

One of the tests I did I saw it look for this manifest and fail:
```
devwithlando/pantheon-appserver:8.0-3
```

I looked and it doesn't appear there is a Docker tag released yet for the [devwithlando/pantheon-appserver](https://hub.docker.com/r/devwithlando/pantheon-appserver/tags) image for 8.0.

Please advise. Thanks!

**Comment by pirog** [comment]
As far as I know we dont support php 8.0 for the pantheon recipe yet.

**Comment by sk33lz** [comment]
Thanks for the speedy reply Mike. I'll keep an eye on this issue as it progresses. It was mainly a recon mission at this point to see if PHP 8 worked with the Pantheon recipe. I was just reporting back what I saw here because I saw this issue open related to moving the Pantheon recipe to a plugin.

**Comment by pirog** [comment]
no prob. 

yah i think one of the main reasons we want to spin this out into its own repo is so we can just ramp up contribution. i think the pantheon stuff has fallen behind a bit and we need to catch up

**Comment by bwood** [comment]
Apologies for responding to a closed topic, but [it appears that Pantheon supports php 8.0 now](https://pantheon.io/docs/php-versions#verify-current-php-versions) and I am not finding another issue related to the plans for the pantheon recipe.

**Comment by sk33lz** [comment]
The Lando [3.6.0 release](https://github.com/lando/lando/releases/tag/v3.6.0) resolves the PHP 8.0 issue. The new pantheon plugin mentioned in this issue [added PHP 8.0 support](https://github.com/lando/pantheon/issues/5) prior to that release in the [0.5.1 release](https://github.com/lando/pantheon/releases/tag/v0.5.1).
