### ISSUE TITLE
how do i update php version?

### ISSUE THREAD

**Issue by himanshurathore29** [lando/lando#3224]
I want to update the modules using lando composer on my drupal website but when I try to do it then the error is coming that the php version is old please update it

 Problem 1
    - laminas/laminas-feed 2.14.1 requires php ^7.3 || ~8.0.0 -> your PHP version (7.2.34) does not satisfy that requirement.

**Comment by neclimdul** [comment]
Assuming you don't have anything too customized, you'll just need to update your .lando.yml file with the version you want and then running `lando rebuild` to get an updated php container.

**Comment by reynoldsalec** [comment]
@himanshurathore29 this example is from the Drupal 9 docs, but this should work on pretty much any Lando PHP recipe: https://docs.lando.dev/config/drupal9.html#configuration

Going to close this out since the OP's question should be answered, but feel free to follow up on the Lando Slack if you have further questions: https://launchpass.com/devwithlando

**Comment by videohead** [comment]
Extra special thanks to Lando for breaking all of their anchor links, so you end up back at the root of the doc.
