### ISSUE TITLE
Lando command don't write nothing in terminal

### ISSUE THREAD

**Issue by nonodev96** [lando/lando#3266]
Lando command don't write nothing in terminal, i try to reinstall lando and docker but not work, and reinstall with brew and reboots, in this moment i use macOS Monterey 12.1  
I'm confused and I don't know what to do :(
🤷‍♂️ 🤔 🤷‍♀️

```zsh
❯ lando
❯ lando version
❯ lando poweroff
❯ lando start
❯ ll .lando
ls: .lando: No such file or directory
❯ lando init
❯ lando help
❯ lando list
```

version -> 3.6.0

**Comment by reynoldsalec** [comment]
@nonodev96 was your original installation using homebrew? I would try the official installer if it was...the homebrew recipe isn't officially supported.

**Comment by nonodev96** [comment]
Yes i use the original version of github [v3.3.0](https://github.com/lando/lando/releases/tag/v3.3.0) and

**Comment by labboy0276** [comment]
@nonodev96 have you tried a complete purge of docker and lando to see if that addresses the issue?

https://docs.lando.dev/basics/uninstalling.html

**Comment by nonodev96** [comment]
Yes, uninstall everything from docker and lando, reboot and reinstall with dmg and nothing.
The folder `~/.lando` was never created.

The script `uninstall.command` don't finish for this command `lando poweroff`. I remove the file with `sudo rm -rf /usr/local/bin/lando`

I tried with sudo but is lock

```
❯ lando
❯ sudo lando
Lando should never ever ever be run as root...
   ___ __                          ______
  / (_) /_____   ___ _  _____ ____/ / / /
 / / /  '_/ -_) / -_) |/ / -_) __/_/_/_/
/_/_/_/\_\\__/  \__/|___/\__/_/ (_|_|_)

```

**Comment by nonodev96** [comment]
I finally formatted my Mac 🥲 and now works

**Comment by brendan-holly-modea** [comment]
I was experiencing this same issue, removing and reinstalling docker + lando repeatedly. The issue was a variable in my `.zshrc` file: `export NODE_OPTIONS=--max_old_space_size=4096`. Lando is written in Node, and removing this line fixed the issue. If you've already completely reset + uninstalled docker and lando, removed `.lando` and `.docker`, and reinstalled try renaming any `.` profiles and/or modifying any custom node settings and then restart your terminal!

A big thank you to @rubenvarela for helping me troubleshoot this!
