### ISSUE TITLE
Displayed URLs for an app could be organized and sorted by service + desireablility, rather than being all in one long list

### ISSUE THREAD

**Issue by Senpai** [lando/lando#327]
When Lando finishes starting up an app, it displays a list of all available URLs. Instead of displaying them as:

```
URLS
https://localhost:32817                                  
http://localhost:32818                                   
https://localhost:32821                                  
http://localhost:32820                                   
http://appname.lndo.site                                     
https://appname.lndo.site
```

...we could group and sort them more like this for usability and comprehension as to their purpose(s):

```
Vanity URLS
https://appname.lndo.site                                     
http://appname.lndo.site

Web Service URLS
https://localhost:32817                                  
http://localhost:32818                                   

Cache Service URLS
https://localhost:32821                                  
http://localhost:32820                                   
```

**Comment by serundeputy** [comment]
@pirog @Senpai 
Branch: `327-org-urls`
This separates out the app URLS into `Vanity URLS` and `Localhost URLS` looking for some feedback on how to differentiate the localhost URLS by service.

**Comment by pirog** [comment]
My bad, i should have clarified this ticket before moving it into current sprint. Did not anticipate @serundeputy's quick draw. 

So i think @Senpai is def right that we need to organize the urls better however. I don't see a lot of utlity in a "vanity urls" category. It doesn't tell us anything we don't already know. I think the org should be purely on a service to service level.

```
Service A URLS
https://appname.lndo.site                                     
http://appname.lndo.site
https://localhost:32817                                  
http://localhost:32818 

Service B URLS
https://localhost:32817                                  
http://localhost:32818                                   

Service C URLS
https://localhost:32821                                  
http://localhost:32820  
```

Ultimately the important thing that is being satisfied here is matching up what URLs can be used for what services. Within each service we should definitely have the vanity urls sorted to the top since you likely are going to want to use those before the localhost ones.

@serundeputy, for some direction here:

Looking at https://github.com/lando/lando/tree/327-org-urls i think there are two important things to note

1. You might want to move your logic over to https://github.com/lando/lando/blob/327-org-urls/plugins/lando-core/lib/scan.js#L30 so you dont have the same logic in two places
2. You might want to look at `app.info` which SHOULD already have urls grouped by service (eg you should be able to loop through `app.urls` and use `app.info` to determine which service each url belongs to, it then might be worth adding that info to each url in `app.urls` so you can "theme" them easily when you grab them in the respective task file)
