### ISSUE TITLE
Badly formatted public keys can bork DB Pulls

### ISSUE THREAD

**Issue by porkloin** [lando/lando#335]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

macOS 10.12.6 (Sierra) with lando v.3.0.0-beta.14

**Tell us about your `.lando.yml`**

```name: testsite
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: testsite
  id: e2a1b189-7fd9-4460-be33-4c49d8017c69
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

```
lando pull
....
```
lines skipped
```
....
Logged in as myuser@myuser.com
Detected that testsite is a drupal8 site
Checking for /user/.lando/keys/pantheon.lando.id_rsa
Downloading drush aliases...
 [notice] Aliases file written to ~/.drush/pantheon.aliases.drushrc.php.
@pantheon.testsite.multidevbranch
Clearing remote cache to shrink db size
key_load_public: invalid format
Cache rebuild complete.                                                     [ok]
 [notice] OK >> multidevbranch-testsite.pantheonsite.io responded
Pulling database...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'key_load_public: invalid format






/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@C' at line 1
1.59KiB 0:00:10 [ 150 B/s] [ <=>                                               ]

Pull complete!
```

**Tell us generally about your bug**

Using `lando pull` to restore a db from a Pantheon remote fails due to an issue with the pubkey generated by lando at ~/.lando/keys, lando's scripts, or something else. stdout error messages of `key_load_public: invalid format` appear to get included in whatever mysql command lando is issuing, causing a syntax error on the first line of the DB, which in turn causes the D8 site to bork. Manual database restore works completely fine.

I've purged and re-created `~/.lando/keys/pantheon.lando.id_rsa` using `ssh-keygen -t rsa` (and replaced the corresponding pubkey in my Pantheon account) but the issue continues nonetheless, which leads me to believe it isn't an issue with the key itself?

Tested in both `bash` and `fish` shells, same issue regardless.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

I don't think so.

Does this bug prevent you from using lando?

No, but using the built-in `lando pull` functionality would be really nice 👍

**Comment by pirog** [comment]
@porkloin im guessing the pantheon key is fine since it looks like it is actually connecting and pull the database. It's possible one of your other keys is in a bad state (https://docs.lndo.io/config/services.html#ssh-keys). I would check to see if that is the case. If so we can provide some stricter key filtering to make sure only good keys are being loaded.

Also, are you seeing this only on a DB pull or do you get the bad format on a code/files pull via lando pull as well?

**Comment by porkloin** [comment]
D'oh - as soon as I cleared out my .ssh dir of other keys it worked fine. Malformed pubkey somewhere in my other keys must have been causing the problem.

That is interesting, nonetheless, since an error with a key that isn't actually being used can cause the mysql db restore to fail.

Thanks for the tip 😉

**Comment by pirog** [comment]
@porkloin awesome! We've got a script that loads up user keys into each container so they can use their own keys if they want (https://github.com/lando/lando/blob/master/plugins/lando-services/scripts/load-keys.sh). 

I think we just need to make this filtering stricter to avoid keys that are not formatted correctly. I'm going to rename this issue and move it into our backlog since im guessing i can reproduce this now.

thanks so much for the bug report!

**Comment by pirog** [comment]
@porkloin weird, wasn't able to replicate this with a bad key... going to try on a Drupal8 site and see if its specific to that framework

**Comment by pirog** [comment]
@porkloin still can't replicate this but going to add in an additional guard regardless
