### ISSUE TITLE
How to force appserver to run on a specific port?

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#347]
Documentation Request
===========================

I'm running a Drupal 8 Pantheon recipe app on Windows 10 Pro with beta 17.

When I start my app, it lists the localhost ports:

```
 SERVICES  appserver, nginx, database, cache, edge_ssl, edge, index, mailhog
 URLS      https://localhost:32782
           http://localhost:32783
           https://localhost:32785
           http://localhost:32784

```

However, when I run `lando restart`, the ports change.  This is annoying because I have to specify the port in `.behat.yml` to get behat tests to run on Windows, so if possible, I would like to fix the port; is that possible?

I checked the [config documentation](https://docs.lndo.io/config/config.yml) but I didn't see what I was looking for.

**Comment by serundeputy** [comment]
@ptmkenny 
If you specify the lando app URL in `BEHAT_PARAMS` var in your `.lando.yml` file should get you going: https://github.com/lando/lando-pantheon-ci-workflow-example/blob/master/.lando.yml#L13

docs: https://docs.lndo.io/tutorials/lando-pantheon-workflow.html

Let us know if that helps.

**Comment by pirog** [comment]
@ptmkenny the ports are assigned by docker itself so we dont have much control over that. 

that said you can definitely fix them using advanced service config (https://docs.lndo.io/config/services.html#advanced-service-configuration) or by setting up a URL like @serundeputy suggested using our proxy (https://docs.lndo.io/config/proxy.html)

im closing this because how to do this is already documented
