### ISSUE TITLE
Read from stdin for db-import

### ISSUE THREAD

**Issue by Crell** [lando/lando#349]
Feature/Enhancement Request
===========================

*As a lando user working on a live site with large database, I want to be able to stream a database dump into lando db-import via stdin so I don't need an intermediary file*

The lando db-import command is great, but you can't pipe into it through stdin.  If I'm importing a large database from a remote server, I can mysqldump (or a wrapped version of it if my web host supports it) to stdout, which I want to then pipe into stdin on db-import.  That way I don't need to double my disk usage with another copy of the DB dump, even if it's compressed.

What I want to be able to do:

`mysqldump -u me -p -h remote.server.com mydb | lando db-import`

**Comment by pirog** [comment]
@Crell was actually meaning to get around to something like this so thanks for surfacing this. As a good related improvement we might want to provide a `--stdout` to `db-export` so users can dump the db directly into stdout. Always amusing when you can do things like

```
lando db-export --stdout | lando db-import
```

Was also super stoked to see 
https://docs.platform.sh/gettingstarted/local/lando.html

Hopefully at some point we can provide a baked in recipe for `platform.sh` since I think it would be super easy for lando to just read in a users `.platform.app.yaml/services.yaml/routes.yaml` and translate them into relevant lando things behind the scenes without needing a complex `.lando.yml`

**Comment by Crell** [comment]
Agreed, a native Platform.sh recipe would be great.  Working incrementally, though, I'd say the "Read from stdin on import" is step 1, a --stdout flag for db-export is step 2, and a full recipe integration is step 3+.

**Comment by pirog** [comment]
So, i've added a `--stdout` flag to `db-export` and **VERY** basic functionality to read from stdin for `db-import`. 

The former works great but i think the latter might not be a completely thing to do due to either a weakness in `dockerode` or `docker` itself when it comes to reading from `stdin`.

I'm going to close this ticket out when we merge this stuff and open up a new ticket with more details.

**Comment by Crell** [comment]
Roger.  Where's the new issue so I can follow it?

**Comment by pirog** [comment]
@Crell sorry for the delay here... BadCamp things ;)

I've spun up another issue with a rough sketch of my current thinking here:
https://github.com/lando/lando/issues/429
