### ISSUE TITLE
PHPStorm, Xdebug, and macOS- how to handle prepend.php?

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#364]
Trying to run Xdebug through PhpStorm using PHP cli on Lando appserver PHP on macOS.

How I set it up

Preferences -> Languages & Frameworks -> PHP -> CLI interpreter (click 3 dots to add)
Add interpreter (+ icon)
Server: Add server (Docker, accept defaults for Mac)
Image name: devwithlando/pantheon-appserver:7.0-fpm

When you save this, it should show PHP version: your version + Xdebug: 2.5.5.

After this, save all settings and then click the phone icon (listen for debugging) on the PHPStorm debug toolbar.  Then go to your site in Lando and click the Jetbrains Chrome extension to start debugging.

PHPStorm will then connect with Chrome, but complain:

`Cannot find a file with path '/srv/includes/prepend.php' in project`

It wants me to set the path mappings to show it where `prepend.php` is, but unfortunately, this file doesn't exist in my project.  In Kalabox, I remember this file was part of the project folder, but in Lando, it's not present.  So how to get around this?

**Comment by NickDaelemans** [comment]
What if you add path mappings in PHPStorm for the docroot? I didn't change my PHP CLI interpreter. Only added path mappings and it worked. You can add those on the configuration of your Xdebug server.

**Comment by dnotes** [comment]
Same error here. Here's something that works for me, but I have to say this fix was a bit difficult to find.

1. Add the pantheon recipe folder to the include paths. Open Preferences > Languages & Frameworks > PHP, click the "+" button at the bottom of the list, and manually type in the name of the folder. On my machine it's /Users/[username]/.lando/services/config/pantheon.
2. Go to Preferences > Languages & Frameworks > PHP > Servers, select "appserver", ensure that "Use path mappings" is checked, and ensure that your project folder is mapped to the "/app" absolute path on server. If you don't have the "appserver" server, do step 3 first then come back here. I don't know how that gets created because I sure didn't do it.
3. Start the debugger listening and open the site for debugging.
4. When the error occurs, click the "Debugger" tab next to the active "Console" tab in the Debugging tools area.
5. Click the link to fix the path mappings.
6. Choose the Include path that you manually typed in earlier, and point it at /srv/includes on the server.
7. Restart the debugger. Does it work? Mine did.

I'm not sure, but you might have to do something about it wanting to start on the first line if the script is outside the project (Preferences > Languages & Frameworks > PHP > Debug). I don't think so though.

**Comment by shaal** [comment]
PHPStorm, Xdebug + Ubuntu
Thank you for this solution, it also fixes that same issue in Ubuntu

**Comment by ultimike** [comment]
Original notes for the solution shared by @dnotes: https://www.drupaleasy.com/blogs/ultimike/2018/01/setting-xdebug-lando-and-phpstorm

There's a bit more info, screenshots, and additional comments there.

-mike

**Comment by AndrewLCM** [comment]
@ultimike I'm afraid the instructions you wrote are out-of-date.  I tried following them and almost immediately what I was seeing didn't match your screenshots.

Any chance we could get this updated?

**Comment by ultimike** [comment]
@AndrewLCM I'm using an older version of PhpStorm - is that the issue?

**Comment by square360-douglas** [comment]
@ultimike thanks for the tutorial, but I see differences too. The method to enable xdebug in lando file seems out of date WRT the docs:
```yml
config:
  xdebug: true
```
Also, I have no appserver available in my phpstorm project. Perhaps I initialised my project differently or perhaps it is php version.

**Comment by labboy0276** [comment]
@square360-douglas 

You add xdebug like this:

```
config:
  xdebug: true
```

**Comment by aaron-capellic** [comment]
I've found that I have to add appserver manually like this:
![image](https://user-images.githubusercontent.com/33872996/40121218-1108f4c4-58ef-11e8-85cd-72b596a959f7.png)

**Comment by square360-douglas** [comment]
@aaron-capellic thanks, I have added a server manually although my settings differ (my site is available on http://sitelive.lndo.site:8000). In any case, I have created another issue for me setup, I'm going slightly off topic for this thread #964

**Comment by synterra** [comment]
@dnotes steps still work, but the path you want is to include is `/Users/[youruser]/.lando/config/pantheon`. which drops the `includes` from the path. Then you can map `prepend.php` appropriately when you get the error.

Also, it's advised that you put the xdebug config line in a `.lando.local.yml` file instead of the root `.lando.yml` file if you have multiple devs working on the same project. You should `.gitignore` that file as well.

**Comment by lucasgrecco** [comment]
For those who still having problems, here my workaround.
On your root directory, you just need to create this path  **/srv/includes** and add the **prepend.php** file.
In linux, **prepend.php** is located in **/home/YOUR_USER/.lando/config/pantheon**

**Comment by lucasgrecco** [comment]
Here is the server conf.
![Screenshot from 2019-05-31 09-58-03](https://user-images.githubusercontent.com/246178/58707329-fde6d600-838a-11e9-81df-5acbbcf9104a.png)
