### ISSUE TITLE
Appserver URLs: name using subdomain doesn't work

### ISSUE THREAD

**Issue by benoitchantre** [lando/lando#3689]
In .lando.yml, I have a name using  subdomain, :

```yml
name: sub.project

recipe: wordpress
```

The expected appserver URLs are
http://sub.project.lndo.site
https://sub.project.lndo.site

This works with the latest stable version, but not with v3.21 beta.9

Appserver URLs with v3.21 beta.9 are
http://subproject.lndo.site (no subdomain)
https://subproject.lndo.site (no subdomain)

**Comment by pirog** [comment]
@benoitchantre im going to close this because im pretty sure its another flavor of this https://github.com/lando/core/issues/119

unsure yet if this is a bug or regardless the recommended way to use subdomains is via the proxy and not with clever app naming :) 
https://docs.lando.dev/core/v3/proxy.html

**Comment by benoitchantre** [comment]
Thank you @pirog. Works via proxy as suggested.
