### ISSUE TITLE
Command lando start times out

### ISSUE THREAD

**Issue by akasophistikat** [lando/lando#3717]
Hello,

When I run `lando start` on my project I get this error, `[TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED`

I simply run the same command over and over until lando starts.

```
Let's get this party started! Starting app my-project...
[+] Running 1/0
 ✔ Container landoproxyhyperion5000gandalfedition_proxy_1  Running                                                                                                                                     0.0s 
[+] Running 7/7
 ✔ Container myproject_appserver_1        Running  
 ✔ Container myproject_index_1            Running   
 ✔ Container myproject_cache_1            Running   
 ✔ Container myproject_appserver_nginx_1  Running   
 ✔ Container myproject_edge_1             Running   
 ✔ Container myproject_edge_ssl_1         Running     
 ✔ Container myproject_database_1         Running    
[+] Healthchecking 1/1
 ✔ Healthcheck myproject_database_1  Passed                          

Your app is starting up... See scanning below for real time status
In the meantime, here are some vitals:

 NAME      my-project
 LOCATION  /Users/pantheon/my-project
 SERVICES  appserver_nginx, appserver, database, cache, edge_ssl, edge, index 
 URLS                                                                         
  ⚠ APPSERVER NGINX URLS
    ✖ https://localhost:50516 [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
    ✖ http://localhost:50517 [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
  ⚠ EDGE SSL URLS
    ✖ https://localhost:50519 [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
  ⚠ EDGE URLS
    ✖ http://localhost:50518 [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
    ✖ http://my-project.lndo.site/ [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
    ✖ https://my-project.lndo.site/ [TIMEOUT] TIMEOUT OF 10000 MS EXCEEDED
```

For more context...

* Lando is connected to Pantheon
* I have another pantheon site and I can start that project without the timeout error
* If I poweroff, I still have to go through the same process
* If I rebuild, same issue
* If I delete the project and start fresh, same issue

Where can I adjust this 10000 MS threshold? I am assuming its due to my project being big in size. Or is this an expected message and I should continue to run the command until it starts.

**Comment by AaronFeledy** [comment]
What you're seeing is Lando's "scanner" that runs after lando has started up. The scanner tries to load your application, so a large application that has a lot of work to do to respond on the first load might take a lot of time. Running the command over and over may actually make things worse because lando has already started. Your best bet is probably just to open the site in your browser and let it fully load once. Check the scanner docs for the options you can set: https://docs.lando.dev/core/v3/scanner.html#other-options

You'll probably add something like this in your landofile:
```
services:
  edge:
    scanner:
      timeout: 15000
  edge_ssl:
    scanner:
      timeout: 15000
```
I believe the timeout is the time it waits before retrying. I think the default is 3000ms, so you may want to try something like 15000 to give it a fair shot at starting before it makes another request.
