### ISSUE TITLE
newb question: comparison to Vagrant?

### ISSUE THREAD

**Issue by jeff-h** [lando/lando#387]
Sorry to ask such a basic question, but can someone explain to me how this project compares to Vagrant? Particularly since Vagrant 2.0 now supports Docker as a provider?

**Comment by pirog** [comment]
Lando is often compared to Vagrant but i think this comparison only goes so far. There are of course many high level and technical differences between the two but the simplest differentiating factor is revealed in their primary value propositions.

> Vagrant is a tool for building and managing virtual machine environments in a single workflow.

> Lando is for developers who want to easily specifiy and quickly spin up the services and tools needed to develop their projects.

Which is to say the focus of Lando is geared towards the quickest and easiest way to get developers' projects ready for development not in supporting a myriad of ways that can be accomplished. 

If you've used Vagrant in the past and were frustrated with it then Lando might be good for you since it's generally easier to use. Beyond that i'd encourage you to try them both and see which is a better fit for you.

**Comment by jeff-h** [comment]
Thanks! I have been looking into many various possibilities in this space and it has gotten confusing indeed, so your answer certainly helps.
