### ISSUE TITLE
What are SSH keys actually used for?

### ISSUE THREAD

**Issue by jrabbit** [lando/lando#411]
From my understanding ssh keys are mounted into all containers as part of mounting /home/$user into /user and configured to be used in /etc/ssh/ssh_config but NOT in `lando ssh` which actually execs/attaches to the container. Why are the keys needed in the container for other users? The whole /user mount is pretty problematic in my eyes. A configuration option to disable this and document it further on https://docs.devwithlando.io/config/ssh.html would be ideal for me.

**Comment by pirog** [comment]
@jrabbit im not sure exactly what you mean by "why are the keys needed in the container for other users?". I'd also like to hear specifically what you think is problematic about the `/user` mount esp given that Lando is a local development environment that is meant to be run only on your computer.

To provide a little more background on some things:

* `lando ssh` is actually just `docker exec -it CONTAINERNAME bash` behind the scenes so it's not really a true `ssh`. We just name it that because its probably the easiest way to communicate what the experience is going to be like. I am **pretty sure** that if you `lando ssh` into a container then your keys are available for usage in the same way. Eg if i `lando ssh` into the appserver container and set up an `ssh` tunnel to run `rsync` or something, then it's going to try the keys that lando has injected.
* The reasons for the automated injection and loading of a users ssh keys are 1.) so lando can provide a seamless experience with services like Pantheon or GitHub that require SSH keys to be set up correctly behind the scenes. 2) so users who want to do more advanced lando things eg scripting out a deployment pipeline or grabbing data from a remote source can use their existing SSH keys instead of having to deal with the considerable hassle required to manage keys inside of a docker container.

We're definitely open to providing an option to completely disable the mounting and loading of the `ssh` keys, since its not super hard to do this we just havent really heard a compelling reason use case yet.
