### ISSUE TITLE
Feature request: `lando self-update`?

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#430]
It would be nice to have the ability to update Lando to the latest release automagically.  I currently do this with the one-liner `cd /path/to/lando/source && git fetch --all && git checkout $(git tag -l | sort -Vr | head -1) && npm install` since I installed the source.  I imagine it would be a bit more challenging with package installs.

**Comment by pirog** [comment]
@uberhacker turns out this sort of thing is pretty tricky with a packaged up node application. That said i'm super keen to get as many people on the latest version as possible since that 

1. Actually gives users the best project
2. Makes our support load more manageable 

What i'm going to do instead is:

1. Bug the hell out of people who are not up to date (a la terminus)
2. Change our default github issue template so that the first thing is UPDATE AND TRY AGAIN before you report and IF YOU ARE ON AN OLD VERSION YOUR ISSUE IS LESS LIKELY TO BE ANSWERED
