### ISSUE TITLE
"lando terminus drush" gives error when "terminus drush" works OK

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#455]
Bug Report
==========

Lando beta-21 on Win10

According to the [terminus docs:](https://pantheon.io/docs/terminus/commands/)

> remote:drush Runs a Drush command remotely on a site's environment. | remote:drush <site>.<env> -- <drush_command>  The double-dash (--) signifies the end of the Terminus options. Everything that comes after the double-dash is interpreted as positional parameters (arguments) and passed to Drush.
> -- | --

Using a locally installed terminus, this command works:

`terminus remote:drush edosensei.dev -- cim -y`

But when I try to do the same thing with lando,

`lando terminus remote:drush mysite.dev -- cim -y`

 I get an error:

```
exec request failed on channel 0
 [notice] Command: edosensei.dev -- drush [Exit: 255]
 [error]
```

If I do this (remove the --):

`lando terminus remote:drush mysite.dev cim -y`

Then the command works, but the `-y` flag is ignored and I have to type `y` manually.

**Comment by pirog** [comment]
@ptmkenny yeah i think this is just an unfortunate consequence of both `lando` and `terminus` using the `--` separator. Lando is likely stripping out everything to the right of `--` and assuming it is intended for it and not terminus. 

I don't think there is much way to get around this beyond fundamentally changing either how `lando` or `terminus` works. I think the workaround for this is to just invoke drush directly using your alias instead of going through terminus. 

```
lando drush @mysite.pantheon.dev cim -y
```

**Comment by callumgare** [comment]
I don't think this should be closed yet. If it can't be fixed then the error message should be changed to be more intelligible or at least documentation improved. After all, isn't this one of the main reasons for having terminus built into lando? I've been figuring I'd screwed up some config or something and it was only by chance I found this github issue.
