### ISSUE TITLE
Documentation addition: Note how to change tmp directory

### ISSUE THREAD

**Issue by davisshaver** [lando/lando#481]
Similar to https://github.com/kalabox/kalabox/issues/1349, the temporary directory may need to be changed in local environment.

Personally I went with...
```
if ( isset( $_ENV['PANTHEON_ENVIRONMENT'] ) && 'lando' === $_ENV['PANTHEON_ENVIRONMENT'] ) {
    define( 'WP_TEMP_DIR', '/tmp');
} else if ( defined( 'PANTHEON_BINDING' ) ):
    define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
endif;
```

Compared to default

```
if ( defined( 'PANTHEON_BINDING' ) ):
    define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
endif;
```

Maybe this should be noted on an existing doc? Suggestions?

**Comment by pirog** [comment]
@davisshaver i think this is something that should "just work" on Lando. That said, i **thought** it already "just worked" so going to investigate.

**Comment by pirog** [comment]
@davisshaver ok so we were already handling this but i changed it to be a little more robust eg instead of creating our own temp directory we just symlink to the normal `/tmp`. I **think** this should resolve your issue and will be in the next release. You may need to `lando rebuild` for it to take effect. 

If that doesn't do it please reopen.
