### ISSUE TITLE
Correct settings to XDebug in VSCode and Lando (drupal 8 recipe)

### ISSUE THREAD

**Issue by MatthieuScarset** [lando/lando#626]
Hi Lando team, and thanks a lot for this great tool! :smile: 

I managed to run XDebug + Lando + Visual Studio Code (VSCode) so I'd like to share my configuration here hoping that it can help other dev.

Related issue: https://github.com/felixfbecker/vscode-php-debug/issues/222
Setting files: https://gist.github.com/MatthieuScarset/0c3860def9ff1f0b84e32f618c740655

Thanks!

**Comment by pirog** [comment]
@MatthieuScarset oh very cool! Any ambition to turn this into something we can use in our docs?

**Comment by MatthieuScarset** [comment]
Sure thing... can you please point me to the right place where I could add it?
thanks!

**Comment by pirog** [comment]
I'd spin up a new markdown file in here https://github.com/lando/lando/tree/master/docs/tutorials and craft a tutorial about "using lando with vscode". Doesn't have to be comprehensive, just dump what you've done in there and hopefully over time we can incrementally build it up!

**Comment by pirog** [comment]
@MatthieuScarset going to close this due to lack of activity but feel free to reopen if you submit a PR!

**Comment by dawidnawrot** [comment]
I would add that opCache has to be disabled in order to make xdebug fuctional fully. OpCache cache some local variables and there variables are not accssible in IDE (whether it's a VSC or PHPStorm), so we can add an extra setting in php.ini file to disable it or even better disable opcache in settings.local.php file by providing: `ini_set('opcache.enable', 0);` expression.
