### ISSUE TITLE
Documentation: Offline development for linux & windows

### ISSUE THREAD

**Issue by carl-alberto** [lando/lando#637]
Would like to contribute back a doc detailing the offline development for linux and windows machine setup but seems I don't have any clue where to start coz main doc: https://docs.devwithlando.io/tutorials/offline-dev.html only outlines Mac, any recommended place to get started? Thanks!

**Comment by pirog** [comment]
@carl-alberto not exactly sure what you mean but that doc lives over at https://github.com/lando/lando/blob/master/docs/tutorials/offline-dev.md. Feel free to add Windows and Linux specific instructions to go along with it.

**Comment by jonathanjfshaw** [comment]
I'd appreciate that @carl-alberto, I've been bitten by this, took me a while to figure out why I was getting weird errors.

**Comment by pirog** [comment]
@carl-alberto @jonathanjfshaw going to close this due to lack of activity but feel free to reopen if you've got something actionable!

**Comment by marceldobrica** [comment]
Hello.
I'm working on Ubuntu. If you may accept using localhost as domain instead of lndo.site simple add config.yml in .lando directory with line proxyDomain: localhost.

Now lando will work offline too.
I really like localhost as proxyDomain... in fact is the real one.... no other changes in any other file/configuration.
