### ISSUE TITLE
p.sh cli install error

### ISSUE THREAD

**Issue by mattpaz** [lando/lando#650]
lando version **v3.0.0-beta.36** via MacOS Sierra (10.12.5) 

An excerpt of the `.lando.yml` file is included below.
```
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
tooling:
  # The following entry creates a `lando platform` command that will run
  # any Platform CLI command from inside the container if desired.
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
```

With it I seem to experience an attempt that results in two separate failed installs.
Excerpts of the error are included below ...  

```

verbose: Exec curl -sS https://platform.sh/cli/installer | php on jnjmdc_appserver_1 in mode attach
debug: With opts {"AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"Cmd":["/bin/sh","-c","curl -sS https://platform.sh/cli/installer | php"],"Env":[],"DetachKeys":"ctrl-p,ctrl-q","Tty":true,"User":"www-data"} {"hijack":false,"stdin":true,"Detach":false,"Tty":true}

# Platform.sh CLI configuration
export PATH='/var/www/.platformsh/bin':"$PATH"
. '/var/www/.platformsh/shell-config.rc'
verbose: Exec curl -sS https://platform.sh/cli/installer | php completed
debug: With result ID=e116f26b70dff1bece2b681e1b60787bc59873c337fd32720f589c7a0f310411, Running=false, ExitCode=1, tty=true, entrypoint=/bin/sh, arguments=[-c, curl -sS https://platform.sh/cli/installer | php], privileged=false, user=www-data, OpenStdin=true, OpenStderr=true, OpenStdout=true, CanRemove=false, ContainerID=08d8a4ce613b39ba66935622e186cedfce6d94215ef4bd74d07b9cad3f1ee30b, DetachKeys=EBE=, Pid=9447
error: message=Platform.sh CLI installer
```

```
# Platform.sh CLI configuration
export PATH='/var/www/.platformsh/bin':"$PATH"
. '/var/www/.platformsh/shell-config.rc'
, code=1
```
I received this after both `lando start` (after destroying) and `lando rebuild`

**Comment by serundeputy** [comment]
Thanks for reporting @mattpaz 

I can confirm this error is thrown when starting an app.  I tried on `v3.0.0-beta.36` and downgrading to `v3.0.0-beta.35` but the error happens on both versions.

I dug into the [platfrom-cli](https://github.com/platformsh/platform-cli) a bin and found that 20 days ago the installer was refactored to detect if `bash` or `zsh` are available before loading in certain files: https://github.com/platformsh/platformsh-cli/commit/a6a348bbacfc69afeb3679ee8d51d6600a592ce3#diff-e96945190ee925e175b0ef90403d40aaR5

In `lando` depending on `sh` or `/bin/bash` `$HOME` is returning different values so that may have something to do with this, but I've not been able to figure out how to definitively check this hypothesis.

**Comment by serundeputy** [comment]
This is the same issue as https://github.com/lando/lando/issues/646

closing so we can consolidate efforts; I'll make a ref to this issue and copy my comment over.
