### ISSUE TITLE
Support/Feature Request: Can I rebuild without pulling images?

### ISSUE THREAD

**Issue by martin-klima** [lando/lando#681]
Support/Feature Request
===============
At first, many thanks for Lando!

Example: I have specified versions for all images in .lando file, e.g.:
```
  database:
    type: mysql:5.5  
  appserver:
    type: php:5.6  
```
and I already have these images loaded and stored locally since previous `lando start` commands.

**When I need to rebuild environment via `lando rebuild`, can I prevent lando from pulling the same already locally available images from the internet?**

If yes, please, tell me how. 
If no, please consider add some new option for `lando rebuild`, like --no-pull, or --prefer-local-images.

Thank you.

**Comment by serundeputy** [comment]
@martin-klima thanks for the report!

does `lando restart` not meet your needs for this use case?

if not can you specify why you need `rebuild` over `restart` an in particular `rebuild` sans pulling images ... as far as I know the primary use case for `rebuild` is to re-pull the images.

**Comment by martin-klima** [comment]
@serundeputy Thank you for reaction. I used `lando rebuild` in many cases, when restart doesn't help, e.g. after change of PHP or MySQL version. I realized, that for all of critical cases, when restart doesn't help, I can use `lando destroy` + `lando start` and Lando will use already downloaded images without pulling them from internet. Of course, I have to remember export databases, because all containers are destroyed. 

From docs about `lando rebuild`: Most app services allow data to persist between rebuilds...", so I still think, that would be great to have useful option for developers to do rebuild without a pulling images.

**Comment by pirog** [comment]
@martin-klima so i think its unlikely we will support something like this and here is why:

1. `rebuild` should only pull a new image from the docker hub if there is a new one available, otherwise it will use the local one
2. In almost all cases if there is an updated image available you are going to want to get it because
3. You an def use `image:version` if you want to lock down to an older image that is unlikely to update
4. `rebuild` is one of our best mechanisms to make sure our users are using the latest and greatest stuff and this REALLY helps cut down support time, which frees us up for new features and bug fixes

Somewhat related, id check out https://github.com/lando/lando/issues/683 which discusses some changes to how we decide to run build steps which might make `lando restart` closer in line with what you are envisioning for rebuild here

**Comment by pirog** [comment]
@JorgeSivil Docker based local dev solutions are probably not good choices if your internet sucks
