### ISSUE TITLE
Remove yarn.lock from the repo?

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#714]
Maybe I'm way off base here but am I right in assuming that including yarn.lock in the repo is going to cause more trouble than it's worth?  I would like to hear the arguments for including it verses not including it.

**Comment by serundeputy** [comment]
> 1. It will cause a merge conflict nightmare with pending PRs

this is only true if the PR changed `yarn.lock` in the first place, many (most?) will not touch npm packages and thus not hit `yarn.lock`

> 2. Anytime you need to update, the file will need to be removed first

Isn't only true of developers running lando from source? If so, that is fine if we are running from bleeding edge source we just deal with that (my opinion).

> 3. It assumes semantic versioned dependencies will introduce breaking changes

This is definitely true; people break stuff sometimes, software development is the process of introducing bugs into working code ;) and even they didn't introduce a bug upstream it could change the way an app interacts with it and break our app.


> Don't specify version ranges in package.json

You have to allow for ranges in `package.json` so that yarn can figure out a working set of packages.  Then once that is figured yarn creates a `yarn.lock` that has 'locked' specific versions that are known to work together.

I'm not married to the idea of having `yarn.lock` in or out, but so far the evidence I see has me leaning to leave it in. I'm open to evidence to change my mind, but I haven't seen anything that convinces me so far.

**Comment by dustinleblanc** [comment]
I also vote for leaving it in, and given that @pirog committed, I am guessing he's on that train too 😄 

Fwiw, @uberhacker, I do see merge conflicts as a potential if a PR gets stale, however it's not hard to recompile the lockfile and repush, and I think that the lockfile is essentially doing number 3 above in it's use. We also don't want to encourage a ton of changes to the required packages in the first place since its *far* to easy to start requiring our way into oblivion (I know this siren song all too well). The reasons to remove it aren't compelling enough to me to remove it.

However, I *do* really love that you are thinking about the DX here, we want contributors. Addressing our stance on this in dev documentation is likely a good outcome from raising the question. I am passionate about making things easy and fun to do, so I love this kind of discussion, thanks for opening the issue! I'll leave it open for a bit to get some more comments, especially from @pirog when he's around, then we'll make an official decision and decide on an action item (do or doc...there is no try).

**Comment by pirog** [comment]
the `yarn.lock` file can definitely be a pain in the ass to manage but its benefits far outweigh that consideration. 

`runs build -> gets not asked for upstream update -> deploy release -> breaks thousands of peoples local dev environment` is to be avoided at literally any cost

**Comment by uberhacker** [comment]
This is the way I see it.  Most users will install via the packaged binary versions which will be thoroughly tested before release anyway, right?  Most users will not be installing from source and if they do, they're probably developers anyway.  Each time the code is changed, as a developer, I must delete the `yarn.lock` file before my changes take effect.  Just sayin`. :)

**Comment by pirog** [comment]
@uberhacker you definitely dont need to blow out the entire `yarn.lock` file when code changes. i dont think ive ever needed to do that.

**Comment by uberhacker** [comment]
Any time I add something to `package.json`, I need to blow away `yarn.lock`.  I have the same issue with composer and it's something that really makes these dependency managers not elegant.

**Comment by pirog** [comment]
havent had that issue. generally `yarn add MYDEP` is worth doing since it will add to package.json and also update the lockfile.

either way, and regardless of whatever hassle, its extremely critical we peg all our dependencies so the lockfile is definitely staying.

**Comment by uberhacker** [comment]
If you really need to lock down the dependencies, you should also commit the vendor directory.  Either omit both or include both is probably the best approach.  I'm in the omit both camp but that's just me.

**Comment by dustinleblanc** [comment]
No need to commit node_modules, this is exactly what a lockfile is for. The conflicts one gets from the lockfile changing only happens when different branches alter the dependency chain and need to merge. This is easily avoidable by being stingy with our dependencies. Yarn is particularly good about this, it will even detect conflicts in the lockfile and fix them for you. If you get a conflict, `git rebase` followed by `yarn`  and `git commit` (possibly with an ammend) should fix it. The slight inconvenience of occasionally having to do that is paid back in spades in the reduced time to install deps on developer machines, in CI, and the stability of a static dependency tree. This doesn't even mention the massive difference in time to execute all git ops vs committing vendor code.

**Comment by pirog** [comment]
all of that ^

**Comment by uberhacker** [comment]
You could make the argument that builds are much faster if the vendor stuff is already in the repo.  The problem with including any of this stuff is when architecture specific settings sneak in, you can have a real conflict mess on your hands.  Anyway, I will give this a rest.  This whole argument makes me very tired.  I just don't like the way it's engineered.
