### ISSUE TITLE
Postgres example needs work

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#770]
Our examples directory contains a postgres example that has issues. The postgres service does not start up properly and we don't include a tooling entry for `pgsql`

**Comment by pirog** [comment]
@dustinleblanc makes sense re: tooling entry. I don't think any of the examples that are straight up single-service implementations include "tooling" entries. We could consider changing that but since we repurpose (include) the example lando files in the docs i wanted to try to keep teh examples as  clean as possible esp if they are focused on a singular thing.

going to see what the issue is here with the spin up
