### ISSUE TITLE
How to run script in backound in the container?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#840]
How to run script in background? This works if I run it from inside the container:

    nohup /bin/bash /app/.lando_scripts/rsync.sh > /dev/null 2>&1 &

but not from "run_as_root:" or "scripts:" parameter.

**Comment by pirog** [comment]
@hkirsman `run_as_root` (available in beta.37+) and `scripts` are both tested and commonly used eg they work. My guess is you probably are doing something weird in the invocation. Have you tried to `lando logs` the container and see what is happening? 

It's also helpful if you post your landofile.

**Comment by hkirsman** [comment]
All scripts run fine just that it's not possible to run any commands in background.

My lando config is:

    name: drupal-7-benchmark
    recipe: drupal7
    config:
      webroot: .
      xdebug: false
      php: '7.0'
      conf:
        php: .lando_config/php.ini
        server: .lando_config/httpd.conf
    
    services:
      appserver:
        portforward: 8080
        overrides:
          services:
            ports: ['8080:80']
        run_as_root:
          - "/bin/bash /app/.lando_scripts/setup.sh"

**Comment by pirog** [comment]
@hkirsman you can definitely run things in the background since we do this for a lot of landos built in scripts like https://github.com/lando/lando/blob/master/plugins/lando-engine/scripts/user-perms.sh, 

You might be better off configuring a custom entrypoint, or using `scripts` instead of `run_as_root`.

It's also worth pointing out, since i have considerable experience on the file sharing issue and have run various local dev projects using various file sharing "solutions" (syncthing, rsync, unison) that its almost always not worth the effort to implement the "faster" solution. 

That all said, if def encourage you to give it a shot and would highly recommend using unison instead of rsync.

**Comment by GDrupal** [comment]
I'm having the exact same issue.... s there a work around? the link in the response seems dead.
