### ISSUE TITLE
Feature request: Directly drush instead of lando drush

### ISSUE THREAD

**Issue by truls1502** [lando/lando#851]
I have the latest version of Lando v3.0.0-beta.39, and the site is running fine which was imported from Pantheon with database and files. 

However, I have a question, do I need to use for example `lando drush cc all`? Can't I use directly command such as `drush cc all` without lando in beginning?

**Comment by pirog** [comment]
@truls1502 if you want to take advantage of lando's containerized tooling then yes you do. We will never support "on host" tooling since the problems with that model are one of the reasons lando exists in the first place.

That said you obviously can use whatever you want and im sure its possible to use your host drush but if it doesnt start with `lando` then we don't support it and your mileage may vary.

**Comment by truls1502** [comment]
How about making an alias like _**ldrush**_? So we can write for example `ldrush status` instead of `lando drush status`? Is it possible to have an inbuilt alias and what do you think?

**Comment by pirog** [comment]
@truls1502 we arent going to support something like this. The main reason is because its fairly easy for a user to define their own command aliases via bash or otherwise if they need to.

**Comment by truls1502** [comment]
Sure. I just was asking, I was thinking maybe it would be nice to have already included in Lando-package. Sure, we can let the user to define this by themselves.

**Comment by pirog** [comment]
@truls1502 i hear you but as a general design pattern we try not to add extra complexity to lando since its already pretty complicated as it is especially if its something the user can do pretty trivially on their end. 

Also, people seem to be pretty particular around how they name their aliases so i'd like to not wade into that hornets nest ;)
