### ISSUE TITLE
lando drush sql-cli is not working

### ISSUE THREAD

**Issue by akalata** [lando/lando#898]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta39 on OSX High Sierra

**Tell us about your `.lando.yml`**

```yml
name: [name]
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: [name]
  id: [hash]
  php: '7.1'
```

pantheon.yml:

```yml
api_version: 1
php_version: 7.1
```

**Tell us about the command you were running**

```bash
drush sql-cli
```

**Tell us about the error you got**

```bash
$ lando drush sql-cli -vvv
 [preflight] Config paths: /app/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /app/drush/sites,/app/drush/sites
 [preflight] Commandfile search paths: /app/vendor/drush/drush/src
 [bootstrap] Bootstrap to max [0.26 sec, 7.29 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.27 sec, 7.42 MB]
 [bootstrap] Change working directory to /app [0.27 sec, 7.42 MB]
 [bootstrap] Initialized Drupal 8.5.1 root directory at /app [0.27 sec, 7.42 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.28 sec, 7.94 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.28 sec, 7.94 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.28 sec, 7.94 MB]
 [debug] Add service modifier [0.29 sec, 8.21 MB]
Calling proc_open(mysql --defaults-file=/tmp/drush_w6r1sr --database=pantheon --host=database --port=3306);
```

**Tell us generally about your bug**

`drush sql-cli` hangs at "Calling proc_open...". Other drush commands that I've tried (`drush cr`, `drush status`) work fine.

**Tell us more**

I am at least able to `lando mysql -u username -ppassword` to access the db via the command line.

**Comment by ccjjmartin** [comment]
@akalata This issue might be related to the upstream issues that the `mysql:latest` docker container was having.  The fix for this was to default lando containers to using a specific version of mysql `mysql:5.7` (you could pick a different one if you wish):
https://github.com/lando/lando/pull/911

You could either add this to your .lando.yml file if you don't want to upgrade:
```
services:
  database:
    type: mysql:5.7
```

Then `lando rebuild -y` or `lando destroy -y`

Or try upgrading to the latest version of lando following the upgrade notes here:
https://github.com/lando/lando/releases/tag/v3.0.0-beta.42

Hope this fixes it for you.  A lot of my co-workers have been hitting this issue.  I somehow seem to have avoided this though.

**Comment by akalata** [comment]
Thanks @ccjjmartin. I was hit by the `mysql:latest` issue yesterday on a different project. That one was causing D8 to fail entirely (and the database container to not launch successfully), so I don't think that it's the cause here.

I'm wishing I hadn't sanitized the site details in my report, since now I'm not sure which site it was. 

I just tested the one I'm 90% sure it was, and it's working... thinking I might have had a mismatched version of core and drush that was making things weird.
