### ISSUE TITLE
Cannot trigger lando commands in a git hook

### ISSUE THREAD

**Issue by drupov** [lando/lando#904]
It's not possible for me to trigger any lando command, when called from a git hook.

I have a very basic .lando file:
```
name: test
recipe: drupal7
config:
  webroot: www
```

and a single pre-commit hook like this
```
05:31:12 {master} ~/Desktop/test$ cat .git/hooks/pre-commit
#!/bin/bash

echo "Output of 'lando'"
lando -- -v

echo "Output of 'lando drush'"
lando drush -- -v
```

I run `lando start` then add any file change and execute
```
05:32:18 {master} ~/Desktop/test$ git add .
05:32:25 {master} ~/Desktop/test$ git commit

Output of 'lando'
info: Bootstraping...
info: Configuring app plugin
info: Configuring engine plugin
info: Configuring proxy plugin
info: Initializing proxy plugin
info: Configuring services plugin
info: Initializing app plugin
info: Initializing engine plugin
info: Initializing events
info: Initializing init framework
info: Initializing recipes plugin
info: Initializing services
info: Initializing tooling plugin
info: Initializing core plugin
info: Bootstrap completed.
info: Initializing cli
info: App test is ready!
Usage: lando <command> [args] [options] [-- global options]

Commands:
  composer                 Run composer commands
  config                   Display the lando configuration
  db-export [file]         Export a database. Resulting file: {DB_NAME}.TIMESTAMP.gz
  db-import [file]         Import into database.
  destroy [appname]        Destroy app in current directory or [appname]
  drush                    Run drush commands
  info [appname]           Prints info about app in current directory or [appname]
  init [method]            Initialize a lando app, optional methods: github, pantheon
  list                     List all lando apps
  logs [appname]           Get logs for app in current directory or [appname]
  mysql                    Drop into a MySQL shell
  php                      Run php commands
  poweroff                 Spin down all lando related containers
  rebuild [appname]        Rebuilds app in current directory or [appname]
  restart [appname]        Restarts app in current directory or [appname]
  share [appname]          Get a publicly available url
  ssh [appname] [service]  SSH into [service] in current app directory or [appname]
  start [appname]          Start app in current directory or [appname]
  stop [appname]           Stops app in current directory or [appname]
  version                  Display the lando version

Global Options:
  --help, -h  Show help
  --verbose, -v, -vv, -vvv, -vvvv  Change verbosity of output

Unknown argument: -v
Output of 'lando drush'
info: Bootstraping...
info: Configuring app plugin
info: Configuring engine plugin
info: Configuring proxy plugin
info: Initializing proxy plugin
info: Configuring services plugin
info: Initializing app plugin
info: Initializing engine plugin
info: Initializing events
info: Initializing init framework
info: Initializing recipes plugin
info: Initializing services
info: Initializing tooling plugin
info: Initializing core plugin
info: Bootstrap completed.
info: Initializing cli
info: App test is ready!
```

I've added a screenshot for better visibility.

![selection_304](https://user-images.githubusercontent.com/1836325/38942475-27197048-432f-11e8-9573-d0ce8073ad03.jpg)

This is a very simplified example, the main point is that my projects' setup I cannot execute a script on pre-commit that is available only inside the container, so I need the lando prefix for it.

Thanks for any help!

**Comment by dustinleblanc** [comment]
Hi @drupov It isn't clear to me what isn't working here. `lando -- -v` is likely not going to work because we require an argument and you get a non-zero exit code if you don't pass one, also the -v is not recognized in that case, as your output indicates. The output of lando drush seems related to passing the `-- -v` as Lando is giving you a verbose output of `lando drush`. 

I assume that if you try to run a real drush command, things don't work correctly, but they do if you use it manually? Greater context should help here. I also wouldn't use `#!/bin/bash` directly because I believe it can cause problems with binaries not being available on your path. I would use `#!/usr/bin/env sh` or something like that. Not sure it would matter here, but it feels like a better approach for this kind of thing.

**Comment by dustinleblanc** [comment]
Hey @drupov I imagine that your main issue here is that Lando isn't showing up in your path [when running in a non-interactive mode](https://stackoverflow.com/questions/39186854/bash-script-cant-execute-go-command). Initially I thought I remembered something about the shebang line impacting that, but I honestly don't know if that's the case. It could have to do with how you have Lando installed, or how you've added it's install path to your `$PATH`, but more than likely, that's part of the problem.

I've also seen reports that some of our output doesn't behave with stdout, xargs, and piping, so that's also a possibility. I'd suggest trying to see if you can make the Lando command write the filesystem rather than echoing to stdout. That might confirm that the commands are running, just not visible to the terminal.

**Comment by jordangidoin** [comment]
hey,
I see the same problem.
My $ PATH is the same though

**Comment by dustinleblanc** [comment]
@jordangidoin are you running a shell script that calls lando? Can you dump the `$PATH` global in that script and confirm Lando is in that path?

**Comment by jordangidoin** [comment]
of course

`/usr/local/Cellar/git/2.17.0/libexec/git-core:/usr/local/Cellar/git/2.17.0/libexec/git-core:/Users/jordangidoin/.rvm/gems/ruby-2.5.1/bin:/Users/jordangidoin/.rvm/gems/ruby-2.5.1@global/bin:/Users/jordangidoin/.rvm/rubies/ruby-2.5.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jordangidoin/.rvm/bin`

My post-merge file : 

```
#!/usr/bin/env sh

source ~/.bash_profile

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

function changed {
  echo "$changed_files" | grep "^$1" > /dev/null 2>&1
}


echo '---- execute post merge ----'

if changed 'htdocs/composer.json'; then
  echo "composer.json changed"
  composer install
fi

if changed 'htdocs/content/themes/socomore-theme/assets/'; then
  echo "Assets change"
  cd htdocs/content/themes/socomore-theme
  lando gulp build
fi

if changed 'htdocs/content/themes/socomore-theme/package.json'; then
  echo "Assets change"
  cd htdocs/content/themes/socomore-theme
  lando npm install
fi
```

**Comment by dustinleblanc** [comment]
Hmm, @jordangidoin what you've got there looks fine, though I don't see where in the script you are dumping the path. I assume `which lando` returns `/usr/local/bin/lando` which should put it in the path there. Any idea on my second theory? That this just isn't showing output? Can you confirm a situation where this *should* alter the filesystem and very clearly does not? Thanks for helping debug and think through it!

**Comment by dustinleblanc** [comment]
@jordangidoin yeah that output indicates that Lando is trying to do some stuff, as that looks like a Lando error. Maybe try using something like `lando command  &> lando.log` in the bash script so you can take a loot at all output?

**Comment by jordangidoin** [comment]
@dustinleblanc  I have already tried but nothing more is displayed ....

**Comment by drupov** [comment]
If I put only `lando &> lando.log` into my pre-commit file the content of lando.log is
```
Usage: lando <command> [args] [options] [-- global options]

Commands:
  composer                 Run composer commands
  config                   Display the lando configuration
  db-export [file]         Export database from a service
  db-import [file]         Import <file> into database service
  destroy [appname]        Destroy app in current directory or [appname]
  drush                    Run drush commands
  info [appname]           Prints info about app in current directory or [appname]
  init [method]            Initialize a lando app, optional methods: github, pantheon
  list                     List all lando apps
  logs [appname]           Get logs for app in current directory or [appname]
  my_script                Run my script
  mysql                    Drop into a MySQL shell on a database service
  php                      Run php commands
  poweroff                 Spin down all lando related containers
  rebuild [appname]        Rebuilds app in current directory or [appname]
  restart [appname]        Restarts app in current directory or [appname]
  share [appname]          Get a publicly available url
  ssh [appname] [service]  SSH into [service] in current app directory or [appname]
  start [appname]          Start app in current directory or [appname]
  stop [appname]           Stops app in current directory or [appname]
  version                  Display the lando version

Global Options:
  --help, -h  Show help
  --verbose, -v, -vv, -vvv, -vvvv  Change verbosity of output

You need at least one command before moving on
```

If my pre-commit file contains only `lando drush &> lando.log` the lando.log file is empty.

I've setup a small repo to be able to reproduce it: https://github.com/drupov/lando-git-hook

**Comment by dustinleblanc** [comment]
I'm guessing you simply can't consume the output of the Docker container, but I am not sure.

**Comment by wss-chadical** [comment]
I'm seeing similar behavior.
When calling lando from a shell script just by itself it's fine.
But, if we do a "lando wp --version" from the script it does the following:
1. executes the command successfully
2. does not produce any output to the console, or via  "&> lando.log"
3. immediately forces an exit from the calling script. (no additional shell code will execute after the lando call)

**Comment by westonruter** [comment]
> I'm guessing you simply can't consume the output of the Docker container, but I am not sure.

I'm seeing a similar thing. I have a `.git/hooks/pre-commit` that looks like the following (I've supplied the absolute path to `lando`, so it's not a `PATH` problem):

```bash
#!/bin/bash

set -e
set -x

/usr/local/bin/lando wp post list

/usr/local/bin/lando wp option update blogname "$BLOG_TITLE"

echo "Pre-commit hook completed\n"
```

If I try doing a commit, the result is:

![image](https://user-images.githubusercontent.com/134745/50610791-0e9d2980-0e89-11e9-9b5e-2a736d6b8785.png)

Note that there is no output from the `wp` commands. Also, note that the commands execute much more quickly than expected. In fact, I have to add the `sleep` command in there in order to see that updated title.

If, however, I try directly invoking that `pre-commit` hook, then I get the expected result output:

![image](https://user-images.githubusercontent.com/134745/50611040-dba76580-0e89-11e9-8eb6-e5c1139b9641.png)

What's more is that I don't have to include the `sleep` command to see `lando wp option get blogname` return the expected result.

So, what seems to be happening here is that when Lando is running in a subshell, it is as if the command is sent to run in the background (`&`) meaning that as soon as the command is run it continues on to the next Bash command. As part of this, the output seems to be getting redirected elsewhere.

Additionally, I've found another issue in that quoted strings get munged when invoking `lando` in a script, for example:

![image](https://user-images.githubusercontent.com/134745/50611101-101b2180-0e8a-11e9-95db-19b5dee4260d.png)

**Comment by westonruter** [comment]
Just to note that this is still not working in v3-RC2. Given a `.git/hooks/pre-commit` that contains:

```bash
lando phpunit
```

I'm getting the following message when I try a `git commit`:

```
the input device is not a TTY
```

**Comment by pirog** [comment]
@westonruter ill give this a try later.

Is `the input device is not a TTY` different than you were getting before?

**Comment by westonruter** [comment]
@pirog The `the input device is not a TTY` message is new as of 3rc2. In 3rc1 I believe the commands would run, but they would not block, meaning the `pre-commit` hook would exit regardless of the exit codes of the `lando` commands inside of it. Now however it seems the commands fail to run at all. For example, if I have the following in my `pre-commit` hook:

```bash
if lando wp core is-installed; then echo "Core is installed"; else echo "Core is not installed"; fi
```

Then I get “Core is not installed” when doing `git commit`. 🚫

If, however, I directly call `bash .git/hooks/pre-commit` or paste the above onto the command line, then I get “Core is installed”. ✅

**Comment by pirog** [comment]
@westonruter makes sense. 

I'm guessing the blocking/exit code thing is **_probably_** fine now but we don't do any `TTY` detection at all when we set up the underlying `docker exec` and `docker-compose exec`.

Guessing we can just piggyback off of node's https://nodejs.org/api/tty.html and use that to set things appropriately. 

Thanks for posting this since im pretty sure there is way more than git hooks where this sort of thing will happen.

**Comment by westonruter** [comment]
Why would the lack of blocking and exit code fine? This severely limits the ability to use `lando` in scripts.

**Comment by pirog** [comment]
@westonruter sorry, "fine now" meaning it should work as expected in the latest releases once the `TTY` detection is improved. Not "fine now" meaning what you just said.

**Comment by pirog** [comment]
Ok this should be resolved in 
https://github.com/lando/lando/releases/tag/v3.0.0-rc.8
