### ISSUE TITLE
XDebug causes semi-random 500 Server Error

### ISSUE THREAD

**Issue by chrisroane** [lando/lando#921]
On a large Drupal 7 pantheon site, this error started to popup all the time:
https://www.dropbox.com/s/62jnvod3qg2oawf/Screenshot%202018-04-27%2006.59.28.png?dl=0

I was using beta40, but downgraded to beta39, but the problem still happens. A few notes on this:

- This has been happening for a while, but it recently started to happen very frequently. I had found a temporary fix that used to always fix this by adding an "exit;" call to the end of the index.php file, but that no longer fixes the problem. Before it didn't happen that much, but it now has become a major problem and makes the lando local box not usable.
- We scoured the logs and couldn't find anything. This includes watchdog and lando logs.
- I used xdebug and it doesn't look like the problem is being triggered by code directly.
- We "think" this might be caching related, but playing/disabling certain cache modules doesn't solve the problem. We have a suspicion in might be a varnish issue.
- Usually restarting the lando box fixes it for a few page requests. Also, sometimes waiting a few minutes and refreshing will make the error go away.
- I've heard from other developers that this is also happening for them in lando using the pantheon recipe, so I don't think it is unique to this project. But I will mention this db is pretty massive for this project.
- Here are the caching modules we are using: cache_consistent, entitycache, imagecache_token, panels_content_cache, pathcache, phpfastcache. Here is the [cache settings](https://gist.github.com/chrisroane/9730181afc2d0b6c0fd1c9f9bc94ea2d) we are setting for all pantheon environments, including lando.

Lando: beta39
Docker: Version 18.03.0-ce-mac60 (23751)
OS: MacOS High Seirra 10.13.4

We really like lando, but this has gotten to a point where if we can't solve this issue, we will have to switch to something else. Any ideas in where this problem might be at.

**Comment by dustinleblanc** [comment]
Frontline Med is definitely a beast of a site! @chrisroane I haven't run into any of these issues, but I am admittedly light on real site development at the moment.

I have been seeing some issues with 503s for folks who are using the advanced page cache on D7 due to some header size issues, but that is the only thing that sounds related.

If we can get a way to reliably reproduce this it will definitely help. Short of being able to reproduce, just helping your team get past the issue is a good first step.

Does changing your PHP version around make any difference? You mentioned other devs with issues on the Pantheon recipe, can you try to correlate that a bit? Do they share code? Is there a specific set of shared circumstances?

I am quite surprised there is nothing in the logs. When PHP/Nginx 500s, there is usually something somewhere I'd think. Have you tried bypassing Varnish?

**Comment by chrisroane** [comment]
@dustinleblanc I'll try to narrow this down to a small D7 site to see if I can replicate. I'll also play with php and maybe bypassing varnish to see if that helps.

@sryanb I know you mentioned you were seeing this on other projects? Do you have any info in where you were seeing this? We have another dev on this project that is on Linux that is seeing the problem too.

**Comment by idpokute** [comment]
Mine is Wordpress on Pantheon, when I rebuild lando image on Windows 10, I can see the 500 error.

**Comment by ccjjmartin** [comment]
@chrisroane I recently learned that part of the upgrade process during the "breaking" changes is to remove your home directories `.lando` directory which stores some Pantheon configuration.  I am wondering if you have some old config is still there that needs to be wiped out.  You might also try upgrading to version beta43 of lando as it fixes some other known critical issues.  A reset on Docker for Mac wouldn't hurt either.

I would be interested to hear if the appserver is responding directly (localhost:port url) as opposed to the varnish server (lndo.site url).

I recently wrote a script to trim the db down for another client that was on the larger side (25GB).  Maybe you could consider this to see if the db size is affecting things?

Since we are specifically dealing with Pantheon, I ran into some 500 errors when using DrupalVM on large sites in the past due to header size as @dustinleblanc mentions:
https://github.com/geerlingguy/drupal-vm/pull/1156 but it spit out a 502 error not 500 ... might be something to look at.

The above recommendations above assume that you had a working site at some point.  I have also seen missing db credentials and bad syntax in settings.php cause this.

**Comment by chrisroane** [comment]
@ccharlton Yesterday I uninstalled docker and upgraded lando and still got the same error. I also wiped out the ~/.lando directory before the upgrade. I was still getting that same error.

The db size is a really good point. It is interesting though that we weren't having this kind of problem using drupalvm. But it could be something specific to lando. Can you share your script that you created to trim down the db and I can give that a shot? Maybe if I just wipe out the quiz data that will save enough space.

I attempted to disable all caching on the site, but I had issues disabling redis via the config in settings.php (was getting db errors). My gut is still that this has something to do with caching, but I'm not 100% sure yet. I'll post here with my results.

**Comment by chrisroane** [comment]
Update: I haven't been able to test this in a minimal way to try to narrow down what is going on....but I have discovered that when I add "exit;" to the end of the drupal index.php file, and when I use the edge_ssl url directly (that looks like: https://localhost:32778/ )....the problem hasn't popped up for me in lando.

I'm a little confused at what using the edge_ssl url directly would do and why the hack on index.php would fix it. But at least this isn't stopping us in our tracks with this project.

**Comment by dustinleblanc** [comment]
@chrisroane yeah those are head scratcher fixes, I can't imagine why they would help. Have you had a chance to grok the header sizes on the pages that are tanking? What I'd be most interested in would be cache tags. Since the db is huge, and there is a chance some of that data is taxonomies that could get tacked onto to request headers, that's my best hunch. Changing the entry point could make sense to stop issues because the different entrypoints could have different buffer sizes, etc (hitting nginx directly, vs hitting varnish).

Definitely a bummer though, hopefully we can get to the other side

**Comment by sturtus** [comment]
I'm having the same issue.  Otherwise I get a 500 error every time it either loads https or attempts to present the site as administrator even in http. Incognito fixed the issue when using the lndo.site edge. I also removed my https redirect script copied from the Pantheon redirects kb page and loaded the site in an Incognito window. So no https, and no old cookies is only way to avoid 500 error AFAICT. 

This is after a complete Docker reinstall, deletion of my .lando folder, installing latest Lando, and full reboot of system.

**Comment by chrisroane** [comment]
Thanks @sturtus . It sounds like this could be an https issue.

Switching between the edge_ssl url and lando url seems to temporarily resolve the issue for me. But it seems to happen eventually at both urls and is pretty annoying.

I did some testing today and loaded 10,000 nodes into a vanilla D7 site using devel generate. It loads very quickly, and I can't seem to replicate the problem there after loading many urls. My gut feeling is that maybe this is because of the size of the db or something unique to this project (maybe redis integration or something)? But I can't quite confirm exactly what is going on.... this seems like a deeper server issue that I'm not very experienced with. Other people using lando on other projects don't encounter this problem at the company.

I'll keep this issue updated if I find out more information. But at this point I'm going to figure out a backup local environment if this issue persists, or we might need to go back to drupalvm.

**Comment by chrisroane** [comment]
Thanks @sryanb.

After much testing, I was able to pinpoint the exact problem. When I had config->xdebug equal to true, I was seeing this error. When I turned that off and rebuilt the box, the error went away. I also confirmed that it isn't the size of the db causing the problem.

What I ended up doing was adding a custom php.ini file to .lando.yml that looks like this:

```
services:
  appserver:
    config:
      conf: lando/php.ini
```
I enabled the xdebug settings, but I can't seem to get vscode to work with xdebug. But the main thing so far is that this error appears to not be happening for me anymore. Maybe xdeubg is causing problems on really large sites? But why would it then still produce the error when using a very trimmed down version of the site without any real content?

If you get this error, I would first try to disable xdebug and rebuild lando. That is what appears to have worked for me. I will keep you posted if the error pops up again.

**Comment by dustinleblanc** [comment]
@chrisroane thanks for updating with your findings. @sryanb thanks for pointing the discussion the right way. I've tagged this issue to help focus the conversation should we be able to make any related improvements. The extra sleuthing is really useful!

FWIW, I hate XDebug and MUCH prefer PsyShell for my debugging needs. It is so much simpler. It is unfortunately quite hard to use when not running a CLI based server 😢

**Comment by betweenbrain** [comment]
@chrisroane is there any chance that you could post your complete, working `.lando.yml` and `php.ini` files? I'm running into similar issues and would like to submit a documentation PR to clarify what is needed for the Pantheon recipe. Thanks!

**Comment by ccjjmartin** [comment]
@betweenbrain Here is some documentation that you may consider contributing to / use it to get started (I tried it recently but it didn't work fully for me): https://github.com/lando/lando/blob/master/docs/tutorials/lando-with-vscode.md

Original issue that created those docs: https://github.com/lando/lando/issues/626

**Comment by betweenbrain** [comment]
@ccjjmartin Thanks! Yes, the docs and issue #626 were my starting point in this journey. Unfortunately, it doesn't work as it is documented as the Pantheon recipe doesn't support a custom `php.ini` per https://github.com/lando/lando/issues/986#issuecomment-391401941. I'm still struggling to get it to work with the Pantheon recipe, but the LAMP recipe hasn't beeb an issue.
