### ISSUE TITLE
Is it possible to configure the varnish service for external (our of lando) websites? 

### ISSUE THREAD

**Issue by hanoii** [lando/lando#981]
Feature Request
===============

I am not a full lando user, but I appreciate the simplified orchestration rather than using docker composer. I use small bits of it, like solr to run stand alone instance of services. 

I would like to use varnish to configure a local dev static cache to tune up some caching but it seems varnish is just meant to be used within other recipes.

Could it be possible to configure a backend that not a container but a native webserver on my host?

**Comment by dustinleblanc** [comment]
Hey @hanoii!

🤔 while I think this is possible (running varnish inside a container to proxy a host application), you are going to have to super DIY things. Inside the container, there is an environment called `LANDO_HOST_IP` that you might be able to use to do some fancy here. Set Varnish to proxy `LANDO_HOST_IP:3000` for instance to proxy something running on port 3000 on the host.

Not sure if that would work, but I guess it's worth a try!

**Comment by pirog** [comment]
@hanoii since this not a supported use case, or something we plan to support, the best advice i can give is that *i think* `backends`, which is the relevant config option for connecting our varnish service to a backend, can be ANY hostname or IP so you might be able to "trick" lando into using a non-lando service. 

If do end up getting it to work id love to hear what you did
