### ISSUE TITLE
Pantheon Drupal 8 Composer no CI

### ISSUE THREAD

**Issue by dirkhacker** [lando/lando#995]
Pantheon has added workflow for Drupal 8 using Composer without CI. 
https://pantheon.io/docs/guides/drupal-8-composer-no-ci/

I tested Lando with this and can only get code back to Pantheon through 'git push'. 'lando push' appears to send code in the terminal but it doesn't result in new code committed on Pantheon. 

I build a sandbox on Pantheon with this procedure and then build the site local (High Sierra) with Lando (v3.0.0-beta.45).

Also, everything executes but I received the following regularly when issuing lando commands to pantheon:
> PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0

I was able to 'lando pull' the code, db, and files. I was able to run 'lando composer require drupal/pathauto'. The only way I was able to get the new module code back to Pantheon was via 'git push'.

Can 'lando push' send code to Pantheon with this workflow?

**Comment by kclarkson** [comment]
@dirkhacker 

I was dealing with the exact same issue except for my code files were pushed but the database and files were not. One thing that I noticed in the status section of the Pantheon Dashboard is that I did not have a services.yml.  So I copied sites/default/default.services.yml to sites/default/services.yml

Then I noticed that git was not pushing the file to the server. The reason for that is because Pantheon's .gitignore file had line that ignored that file. web/sites/*/services*.yml After I commented it out I could then pus the file to the server. 

After the file was on the server I did a Lando Push, made sure to select db and files because it defaults to none and everything worked even with the same error.

**Comment by dustinleblanc** [comment]
Hey @dirkhacker!

Lando itself really shouldn't care much about how you built the site when it comes to `lando push`, but Pantheon might have issues as @kclarkson noticed when pushing certain files.

FWIW, I think `lando push` is itself an anti-pattern, especially when dealing with a Drupal 8 workflow where configuration management is a part of Drupal core. I'd recommend using Git only to push changes.
